DROP TABLE IF EXISTS shipment_settings_details_restricted_locations;

CREATE TABLE IF NOT EXISTS shipment_settings_details_restricted_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid uuid,
    shipment_settings_details_id bigint NOT NULL,
    FOREIGN KEY (shipment_settings_details_id) REFERENCES shipment_setting(id),
    restricted_locations varchar NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by INT,
    updated_by INT,
    CONSTRAINT ShipmentSettings_restricted_unloc UNIQUE (restricted_locations, shipment_settings_details_id),
    is_deleted BOOLEAN DEFAULT FALSE
);