DROP TABLE IF EXISTS tenant_products_transport_mode;

CREATE TABLE IF NOT EXISTS tenant_products_transport_mode (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     guid uuid,
     tenant_product_id bigint NOT NULL,
     FOREIGN KEY (tenant_product_id) REFERENCES tenant_products(id),
     transport_mode varchar NOT NULL,
     created_at TIMESTAMP,
     updated_at TIMESTAMP,
     created_by INT,
     updated_by INT,
     CONSTRAINT tenant_products_transport_mode_mapping UNIQUE (transport_mode, tenant_product_id),
     is_deleted BOOLEAN DEFAULT FALSE
);