CREATE TABLE IF NOT EXISTS mawb_hawb_link (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    mawb_id BIGINT NOT NULL,
    hawb_id BIGINT NOT NULL,
    tenant_id integer,
    created_at timestamp  NOT NULL,
    created_by integer,
    updated_at timestamp  NOT NULL,
    updated_by integer,
    is_deleted BOOLEAN DEFAULT FALSE
);