package com.dpw.runner.shipment.services.dto.patchrequest;

import com.dpw.runner.shipment.services.commons.requests.CommonRequest;
import com.dpw.runner.shipment.services.commons.requests.IRunnerRequest;
import com.dpw.runner.shipment.services.dto.request.*;
import com.dpw.runner.shipment.services.entity.enums.GenerationType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.openapitools.jackson.nullable.JsonNullable;

import java.time.LocalDateTime;
import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ShipmentSettingsPatchRequest extends CommonRequest implements IRunnerRequest {
    private Long id;
    private Long tenantId;
    private JsonNullable<Boolean> autoUpdateShipmentAWB;
    private JsonNullable<Boolean> autoUpdateShipmentBL;
    private JsonNullable<Boolean> houseBillNumberLock;
    private JsonNullable<Boolean> restrictHblGen;
    private JsonNullable<Boolean> printPhoneNumber;
    private JsonNullable<String> housebillPrefix;
    private JsonNullable<String> housebillNumberGeneration;
    private JsonNullable<Integer> footerColumns;
    private JsonNullable<Boolean> isAutoPopulateShipType;
    private JsonNullable<Boolean> partialCloningEnabled;
    private JsonNullable<Boolean> shipConsolidationContainerEnabled;
    private JsonNullable<Boolean> autoAttachConsolidation;
    private JsonNullable<Boolean> multipleShipmentEnabled;
    private JsonNullable<Boolean> enableRouteMaster;
    private JsonNullable<Boolean> arApFlag;
    private JsonNullable<Boolean> shipmentTiCargesLinkage;
    private JsonNullable<Integer> cooldownTime;
    private JsonNullable<Integer> advancePeriod;
    private JsonNullable<Boolean> autoEventCreate;
    private JsonNullable<Boolean> shipmentLite;
    private JsonNullable<Boolean> billingLite;
    private JsonNullable<Boolean> restrictedLocationsEnabled;
    private JsonNullable<Boolean> isAtdAtaAutoPopulateEnabled;
    private List<String> restrictedLocations;
    private JsonNullable<String> shipmentConsoleImportApproverRole;
    private JsonNullable<GenerationType> shipmentIdGenerationType;
    private JsonNullable<String> shipmentIdGenerationPrefix;
    private JsonNullable<Integer> shipmentIdGenerationCounter;
    private JsonNullable<Boolean> lowMarginApproval;
    private List<HblTermsConditionTemplateRequest> hblTermsConditionTemplate;
    private List<HblTermsConditionTemplateRequest> hblHawbBackPrintTemplate;
    private JsonNullable<Boolean> inlineEnabled;
    private JsonNullable<Boolean> carrierMandatory;
    private JsonNullable<Integer> weightVolumeDecimalPlace;
    private JsonNullable<String> dpwDateFormat;
    private JsonNullable<String> weightChargeableUnit;
    private JsonNullable<String> volumeChargeableUnit;
    private JsonNullable<String> measurementChargeableUnit;
    private JsonNullable<String> temperatureUnit;
    private JsonNullable<String> defaultTransportMode;
    private JsonNullable<String> defaultContainerType;
    private JsonNullable<String> defaultShipmentType;
    private JsonNullable<String> emailHost;
    private JsonNullable<Long> emailPort;
    private JsonNullable<Boolean> emailUseSsl;
    private JsonNullable<String> emailFrom;
    private JsonNullable<String> emailUserName;
    private JsonNullable<String> emailPassword;
    private JsonNullable<Boolean> emailIsfAsmResponse;
    private JsonNullable<String> defaultFailureEmailIds;
    private JsonNullable<Boolean> shipmentLock;
    private JsonNullable<String> orgPrefix;
    private JsonNullable<Boolean> orgCodeLock;
    private JsonNullable<Boolean> countryPrefix;
    private GenerationType orgNumberGeneration;
    private JsonNullable<Boolean> unLocoCodeEnabled;
    private JsonNullable<Boolean> enableOrgAddressUpdate;
    private JsonNullable<Boolean> allowFreeTextAddress;
    private JsonNullable<Boolean> isConsolidator;
    private JsonNullable<Boolean> mergeContainers;
    private JsonNullable<Boolean> bolNumberLock;
    private JsonNullable<Boolean> isShowMBL;
    private JsonNullable<Boolean> consolidationLite;
    private JsonNullable<Boolean> containerEventBulkUpload;
    private JsonNullable<String> bolNumberPrefix;
    private GenerationType bolNumberGeneration;
    private JsonNullable<Boolean> isMandateDocType;
    private JsonNullable<String> houseMainPage;
    private JsonNullable<String> hblFooter;
    private JsonNullable<Boolean> printAfterEachPage;
    private JsonNullable<String> seawayMainPage;
    private JsonNullable<String> shipTruckWayBillMainPage;
    private JsonNullable<String> consTruckWayBillMainPage;
    private JsonNullable<String> shipTruckDriverProof;
    private JsonNullable<String> consTruckDriverProof;
    private JsonNullable<String> commercialInvMainPage;
    private JsonNullable<String> packingListMainPage;
    private JsonNullable<String> customsInsMainPage;
    private JsonNullable<String> airwayMainPage;
    private JsonNullable<String> canMainPage;
    private JsonNullable<String> canBackPrint;
    private JsonNullable<String> arrivalNotice;
    private JsonNullable<String> freightCertification;
    private JsonNullable<String> preAlertDoc;
    private JsonNullable<String> manifestPrint;
    private JsonNullable<String> containerManifestPrint;
    private JsonNullable<String> seaImportShipmentManifest;
    private JsonNullable<String> seaExportShipmentManifest;
    private JsonNullable<String> seaImportConsoleManifest;
    private JsonNullable<String> seaExportConsoleManifest;
    private JsonNullable<String> airImportShipmentManifest;
    private JsonNullable<String> airExportShipmentManifest;
    private JsonNullable<String> airImportConsoleManifest;
    private JsonNullable<String> airExportConsoleManifest;
    private JsonNullable<String> proofOfDelivery;
    private JsonNullable<String> pickupOrder;
    private JsonNullable<String> deliveryOrder;
    private JsonNullable<String> bookingConfirmation;
    private JsonNullable<String> costalDocument;
    private JsonNullable<String> shippingInstruction;
    private JsonNullable<String> consolidatedPackingList;
    private JsonNullable<String> awbLable;
    private JsonNullable<String> cargoManifest;
    private JsonNullable<String> packingListMainPageAir;
    private JsonNullable<String> freightCertificationAir;
    private JsonNullable<String> preAlertAir;
    private JsonNullable<String> bookingConfirmationAir;
    private JsonNullable<String> pickupOrderAir;
    private JsonNullable<String> deliveryOrderAir;
    private JsonNullable<String> canMainPageAir;
    private JsonNullable<String> canBackPrintAir;
    private JsonNullable<String> customsInsMainPageAir;
    private JsonNullable<String> commercialInvMainPageAir;
    private JsonNullable<String> arrivalNoticeAir;
    private JsonNullable<String> hawb;
    private JsonNullable<String> mawb;
    private JsonNullable<String> awbNeutral;
    private JsonNullable<String> csr;
    private JsonNullable<String> shippingRequestMainPage;
    private JsonNullable<String> shippingRequestAir;
    private JsonNullable<String> seaShippingInstructionMainPage;
    private JsonNullable<String> defaultEmailTemplate;
    private JsonNullable<Integer> decimalPlaces;
    private JsonNullable<Integer> hblApprovalRole;
    private JsonNullable<Boolean> cargoFinanceBooking;
    private JsonNullable<Boolean> unicoBlObject;
    private HblLockSettingsRequest hblLockSettings;
    private JsonNullable<Boolean> customisedSequence;
    private List<TenantProductsRequest> tenantProducts;
    private List<ProductSequenceConfigRequest> productSequenceConfig;
    private HawbLockSettingsRequest hawbLockSettings;
    private MawbLockSettingsRequest mawbLockSettings;
    private JsonNullable<Integer> hblMultipleOriginalApproval;
    private JsonNullable<Boolean> hblApprovalFlow;
    private JsonNullable<Boolean> isShipmentLevelContainer;
    private JsonNullable<Boolean> restrictBlRelease;
    private JsonNullable<Integer> restrictBlApprovalRole;
    private JsonNullable<Boolean> eManifest;
    private JsonNullable<String> isfFileMainPage;
    private JsonNullable<String> cancelledBLSuffix;
    private JsonNullable<Integer> volumeDecimalPlace;
    private JsonNullable<Integer> weightDecimalPlace;
    private JsonNullable<Boolean> restrictBLEdit;
    private JsonNullable<Boolean> restrictAWBEdit;
    private JsonNullable<Boolean> regulatedAgent;
    private JsonNullable<String> raNumber;
    private JsonNullable<LocalDateTime> raExpiry;
    private JsonNullable<String> transportOrderRoad;
    private JsonNullable<Boolean> disableBlPartiesName;
    private JsonNullable<Boolean> airDGFlag;
    private JsonNullable<Boolean> iataTactFlag;
    private JsonNullable<Boolean> enableLclConsolidation;
    private JsonNullable<String> bookingOrder;
    private JsonNullable<String> bookingOrderForMbl;
    private JsonNullable<String> bookingOrderAir;
    private JsonNullable<String> bookingOrderAirForMawb;
    private JsonNullable<String> transportInstructionPickupOrder;
    private JsonNullable<String> transportInstructionDeliveryOrder;
    private JsonNullable<Boolean> enablePartyCheckForConsolidation;
    private JsonNullable<String> csd;
    private JsonNullable<Boolean> hideManifest;
    private JsonNullable<LocalDateTime> isEntityTransferPrerequisiteEnabledDate;
    private JsonNullable<Boolean> isEntityTransferPrerequisiteEnabled;
    private JsonNullable<Boolean> isNetworkTransferEntityEnabled;
    private JsonNullable<Boolean> eventsRevampEnabled;
    private JsonNullable<Boolean> isAutomaticTransferEnabled;
    private JsonNullable<Boolean> isNteAdditionalEmailsEnabled;
    private JsonNullable<Boolean> isAwbRevampEnabled;
    private JsonNullable<Boolean> isRunnerV3Enabled;
    private JsonNullable<Boolean> isExternalFileTransferEnabled;
}
