package com.dpw.runner.shipment.services.dto.patchrequest;

import com.dpw.runner.shipment.services.commons.requests.CommonRequest;
import com.dpw.runner.shipment.services.commons.requests.IRunnerRequest;
import com.dpw.runner.shipment.services.dto.request.AdditionalDetailRequest;
import com.dpw.runner.shipment.services.dto.request.BookingCarriageRequest;
import com.dpw.runner.shipment.services.dto.request.ContainerRequest;
import com.dpw.runner.shipment.services.dto.request.ELDetailsRequest;
import com.dpw.runner.shipment.services.dto.request.EventsRequest;
import com.dpw.runner.shipment.services.dto.request.FileRepoRequest;
import com.dpw.runner.shipment.services.dto.request.JobRequest;
import com.dpw.runner.shipment.services.dto.request.NotesRequest;
import com.dpw.runner.shipment.services.dto.request.PackingRequest;
import com.dpw.runner.shipment.services.dto.request.PartiesRequest;
import com.dpw.runner.shipment.services.dto.request.PickupDeliveryDetailsRequest;
import com.dpw.runner.shipment.services.dto.request.ReferenceNumbersRequest;
import com.dpw.runner.shipment.services.dto.request.RoutingsRequest;
import com.dpw.runner.shipment.services.dto.request.ServiceDetailsRequest;
import com.dpw.runner.shipment.services.dto.request.ShipmentOrderRequest;
import com.dpw.runner.shipment.services.dto.request.TruckDriverDetailsRequest;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.openapitools.jackson.nullable.JsonNullable;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ShipmentPatchRequest extends CommonRequest implements IRunnerRequest {
    private AdditionalDetailRequest additionalDetail;
    private JsonNullable<String> additionalTerms;
    private JsonNullable<String> assignedTo;
    private JsonNullable<Boolean> autoUpdateWtVol;
    private List<BookingCarriageRequest> bookingCarriagesList;
    private JsonNullable<String> bookingNumber;
    private JsonNullable<String> bookingReference;
    private JsonNullable<String> bookingType;
    private JsonNullable<Boolean> cargoFinanceBooking;
    private CarrierPatchRequest carrierDetails;
    private JsonNullable<BigDecimal> chargable;
    private JsonNullable<String> chargeableUnit;
    private PartiesRequest client;
    private PartiesRequest consignee;
    private PartiesRequest consigner;
    private JsonNullable<String> consolRef;
    private JsonNullable<Boolean> containerAutoWeightVolumeUpdate;
    private List<ContainerRequest> containersList;
    private JsonNullable<String> direction;
    private JsonNullable<Long> documentationPartner;
    private List<ELDetailsRequest> elDetailsList;
    private JsonNullable<String> entryDetail;
    private List<EventsRequest> eventsList;
    private List<FileRepoRequest> fileRepoList;
    private JsonNullable<String> financeClosedBy;
    private JsonNullable<LocalDateTime> financeClosedOn;
    private JsonNullable<BigDecimal> freightLocal;
    private JsonNullable<String> freightLocalCurrency;
    private JsonNullable<BigDecimal> freightOverseas;
    private JsonNullable<String> freightOverseasCurrency;
    private JsonNullable<String> goodsDescription;
    private JsonNullable<String> houseBill;
    private JsonNullable<Long> id;
    private JsonNullable<String> incoterms;
    private JsonNullable<String> innerPackUnit;
    private JsonNullable<Integer> innerPacks;
    private JsonNullable<Boolean> intraBranch;
    private JsonNullable<Boolean> isDomestic;
    private JsonNullable<Boolean> isLocked;
    private JsonNullable<Boolean> isNotifyConsigneeEqual;
    private JsonNullable<Boolean> isShipmentReadOnly;
    private JsonNullable<String> jobType;
    private List<JobRequest> jobsList;
    private JsonNullable<String> lockedBy;
    private JsonNullable<String> marksNum;
    private JsonNullable<String> masterBill;
    private JsonNullable<BigDecimal> netWeight;
    private JsonNullable<String> netWeightUnit;
    private JsonNullable<Integer> noOfPacks;
    private List<NotesRequest> notesList;
    private List<PackingRequest> packingList;
    private JsonNullable<String> packsUnit;
    private JsonNullable<String> paymentTerms;
    private List<PickupDeliveryDetailsRequest> pickupDeliveryDetailsList;
    private JsonNullable<Integer> prevShipmentStatus;
    private JsonNullable<Long> receivingBranch;
    private List<ReferenceNumbersRequest> referenceNumbersList;
    private JsonNullable<String> route;
    private List<RoutingsRequest> routingsList;
    private JsonNullable<Long> salesAgent;
    private JsonNullable<String> serviceType;
    private List<ServiceDetailsRequest> servicesList;
    private JsonNullable<String> shipmentCompletedBy;
    private JsonNullable<LocalDateTime> shipmentCompletedOn;
    private JsonNullable<String> shipmentId;
    private JsonNullable<String> shipmentType;
    private JsonNullable<String> source;
    private JsonNullable<Long> sourceTenantId;
    private JsonNullable<Integer> status;
    private JsonNullable<String> transportMode;
    private JsonNullable<List<Long>> triangulationPartnerList;
    private JsonNullable<Long> triangulationPartner;
    private List<TruckDriverDetailsRequest> truckDriverDetails;
    private JsonNullable<BigDecimal> volume;
    private JsonNullable<String> volumeUnit;
    private JsonNullable<BigDecimal> volumetricWeight;
    private JsonNullable<String> volumetricWeightUnit;
    private JsonNullable<BigDecimal> weight;
    private JsonNullable<String> weightUnit;
    private JsonNullable<String> jobStatus;
    private JsonNullable<BigDecimal> goodsValue;
    private JsonNullable<String> goodsValueCurrency;
    private JsonNullable<BigDecimal> insuranceValue;
    private JsonNullable<String> InsuranceValueCurrency;
    private JsonNullable<String> entryRefNo;
    private JsonNullable<String> flightStatus;
    private JsonNullable<Boolean> containsHazardous;
    private JsonNullable<String> fmcTlcId;
    private JsonNullable<String> commodity;
    private JsonNullable<Long> orderNumber;
    private JsonNullable<String> orderManagementId;
    private JsonNullable<String> orderManagementNumber;
    private List<ShipmentOrderRequest> shipmentOrders;
    private JsonNullable<Boolean> isNetworkFile;
    private JsonNullable<Boolean> isReceivingBranchManually;
}
