# This is a SecretProviderClass example using system-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
  namespace: $NAMESPACE_NAME
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    # Set to true for using managed identity
    userAssignedIdentityID: $USER_ASSIGNED_IDENTITY_ID     # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: kv-cargorunner-prod
    cloudName: "AzurePublicCloud"                   # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: shipment-service-prod-SECRET
          objectType: secret
          objectVersion: ""       
    tenantId: 2bd16c9b-7e21-4274-9c06-7919f7647bbb         # The tenant ID of the key vault