package com.dpw.runner.shipment.services.commons.constants;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class AuditLogConstants {

        private AuditLogConstants(){}
    public static final String AUDIT_LOG_API_HANDLE = "/api/v2/audit-log";

    public static final String AUDIT_LOG_LIST_SUCCESSFUL = "Successful Audit Log Data List Retrieval";

    public static final String AUDIT_LOG_DOWNLOAD_SUCCESSFUL = "Successful Audit Log Data Download";

        public static final String TRANSPORT_MODE = "transportMode";
        public static final String TRANSPORT_MODE_VALUE = "Transport Mode";
        public static final String SHIPMENT_ID_VALUE = "Shipment Id";
        public static final String SHIPMENT_ID = "shipmentId";
        public static final String IS_DOMESTIC = "isDomestic";
        public static final String IS_DOMESTIC_VALUE = "Is Domestic";
        public static final String CHARGEABLE_UNIT = "chargeableUnit";
        public static final String CHARGEABLE_UNIT_VAL = "Chargeable Unit";
        public static final String NET_WEIGHT_VAL = "Net Weight";
        public static final String NET_WEIGHT = "netWeight";
        public static final String NET_WEIGHT_UNIT_VAL = "Net Weight Unit";
        public static final String NET_WEIGHT_UNIT = "netWeightUnit";
        public static final String VOYAGE_VAL = "Voyage";
        public static final String OLD_VALUE = "oldValue";
        public static final String NEW_VALUE = "newValue";
        public static final Map<String, String> ShipmentsFieldNameToDisplayNameMap;
        static {
                Map<String, String> map = new HashMap<>();
                map.put("houseBill", "House Bill");
                map.put(TRANSPORT_MODE, TRANSPORT_MODE_VALUE);
                map.put("direction", "Direction");
                map.put("shipmentType", "Shipment Type");
                map.put("containersList", "Containers List");
                map.put("status", "Status");
                map.put("source", "Source");
                map.put("jobType", "Job Type");
                map.put("serviceType", "Service Type");
                map.put("masterBill", "Master Bill");
                map.put("bookingReference", "Booking Reference");
                map.put("consolRef", "Consol Ref");
                map.put("salesAgent", "Sales Agent");
                map.put("paymentTerms", "Payment Terms");
                map.put("incoterms", "Incoterms");
                map.put(SHIPMENT_ID, SHIPMENT_ID_VALUE);
                map.put(IS_DOMESTIC, IS_DOMESTIC_VALUE);
                map.put("assignedTo", "Assigned To");
                map.put("additionalTerms", "Additional Terms");
                map.put("goodsDescription", "Goods Description");
                map.put("bookingCarriagesList", "Booking Carriages List");
                map.put("elDetailsList", "El Details List");
                map.put("eventsList", "Events List");
                map.put("fileRepoList", "File Repo List");
                map.put("packingList", "Packing List");
                map.put("referenceNumbersList", "Reference Numbers List");
                map.put("routingsList", "Routings List");
                map.put("servicesList", "Services List");
                map.put("truckDriverDetails", "Truck Driver Details");
                map.put("weight", "Weight");
                map.put("weightUnit", "Weight Unit");
                map.put("volume", "Volume");
                map.put("volumeUnit", "Volume Unit");
                map.put("volumetricWeight", "Volumetric Weight");
                map.put("volumetricWeightUnit", "Volumetric Weight Unit");
                map.put("chargable", "Chargable");
                map.put(CHARGEABLE_UNIT, CHARGEABLE_UNIT_VAL);
                map.put(NET_WEIGHT, NET_WEIGHT_VAL);
                map.put(NET_WEIGHT_UNIT, NET_WEIGHT_UNIT_VAL);
                map.put("noOfPacks", "No Of Packs");
                map.put("packsUnit", "Packs Unit");
                map.put("innerPacks", "Inner Packs");
                map.put("innerPackUnit", "Inner Pack Unit");
                map.put("freightLocal", "Freight Local");
                map.put("freightLocalCurrency", "Freight Local Currency");
                map.put("freightOverseas", "Freight Overseas");
                map.put("freightOverseasCurrency", "Freight Overseas Currency");
                map.put("autoUpdateWtVol", "Auto Update Wt Vol");
                map.put("containerAutoWeightVolumeUpdate", "Container Auto Weight Volume Update");
                map.put("marksNum", "Marks Num");
                map.put("entryDetail", "Entry Detail");
                map.put("isLocked", "Is Locked");
                map.put("lockedBy", "Locked By");
                map.put("isNotifyConsigneeEqual", "Is Notify Consignee Equal");
                map.put("bookingType", "Booking Type");
                map.put("cargoFinanceBooking", "Cargo Finance Booking");
                map.put("bookingNumber", "Booking Number");
                map.put("route", "Route");
                map.put("sourceTenantId", "Source Tenant Id");
                map.put("documentationPartner", "Documentation Partner");
                map.put("triangulationPartnerList", "Triangulation Partner List");
                map.put("triangulationPartner", "Triangulation Partner");
                map.put("receivingBranch", "Receiving Branch");
                map.put("intraBranch", "Intra Branch");
                map.put("prevShipmentStatus", "Prev Shipment Status");
                map.put("isShipmentReadOnly", "Is Shipment Read Only");
                map.put("shipmentCreatedOn", "Shipment Created On");
                map.put("shipmentCompletedBy", "Shipment Completed By");
                map.put("shipmentCompletedOn", "Shipment Completed On");
                map.put("financeClosedBy", "Finance Closed By");
                map.put("financeClosedOn", "Finance Closed On");
                map.put("goodsValue", "Goods Value");
                map.put("goodsValueCurrency", "Goods Value Currency");
                map.put("insuranceValue", "Insurance Value");
                map.put("InsuranceValueCurrency", "Insurance Value Currency");
                map.put("jobsList", "Jobs List");
                map.put("consolidationList", "Consolidation List");
                map.put("shipmentAddresses", "Shipment Addresses");
                map.put("jobStatus", "JobStatus");
                map.put("entryRefNo", "Entry Ref No");
                map.put("flightStatus", "Flight Status");
                map.put("containsHazardous", "Contains Hazardous");
                map.put("fmcTlcId", "Fmc Tlc Id");
                map.put("commodity", "Commodity");
                map.put("orderNumber", "Order Number");
                map.put("orderManagementId", "Order Management Id");
                map.put("orderManagementNumber", "Order Management Number");
                map.put("customerCategory", "Customer Category");
                map.put("contractId", "Contract Id");
                map.put("contractType", "Contract Type");
                map.put("clientCountry", "Client Country");
                map.put("consignorCountry", "Consignor Country");
                map.put("consigneeCountry", "Consignee Country");
                map.put("notifyPartyCountry", "Notify Party Country");
                map.put("salesAgentEmail", "Sales Agent Email");
                map.put("salesBranch", "Sales Branch");
                map.put("sourceGuid", "Source Guid");
                map.put("consigneeDpsAddressId", "Consignee Dps Address Id");
                map.put("clientDpsAddressId", "Client Dps Address Id");
                map.put("consignorDpsAddressId", "Consignor Dps Address Id");
                map.put("notifyPartyDpsAddressId", "Notify Party Dps Address Id");

                map.put("additionalDetails", "Additional Details");
                map.put("additionalDetails.expiryDate", "Expiry Date");
                map.put("additionalDetails.inspection", "Inspection");
                map.put("additionalDetails.airwayBillDims", "Airway Bill Dims");
                map.put("additionalDetails.shipperCOD", "Shipper COD");
                map.put("additionalDetails.shipperCODPM", "Shipper CODPM");
                map.put("additionalDetails.phase", "Phase");
                map.put("additionalDetails.spotRate", "Spot Rate");
                map.put("additionalDetails.spotRateType", "Spot Rate Type");
                map.put("additionalDetails.efreightStatus", "Efreight Status");
                map.put("additionalDetails.importExportShipmentLock", "Import Export Shipment Lock");
                map.put("additionalDetails.CHAJobNumber", "CHA Job Number");
                map.put("additionalDetails.ADCode", "AD Code");
                map.put("additionalDetails.BEType", "BE Type");
                map.put("additionalDetails.customLocation", "Custom Location");
                map.put("additionalDetails.customCity", "Custom City");
                map.put("additionalDetails.isImportClearance", "Is Import Clearance");
                map.put("additionalDetails.isExportClearance", "Is Export Clearance");
                map.put("additionalDetails.IGMFileNo", "IGM File No");
                map.put("additionalDetails.IECode", "IE Code");
                map.put("additionalDetails.branchSINumber", "Branch SI Number");
                map.put("additionalDetails.andesStatus", "Andes Status");
                map.put("additionalDetails.andesResponseDate", "Andes Response Date");
                map.put("additionalDetails.andesStatusResponseText", "Andes Status Response Text");
                map.put("additionalDetails.tipoDocumentNotifyParty", "Tipo Document Notify Party");
                map.put("additionalDetails.tipoDocumentConsignee", "Tipo Document Consignee");
                map.put("additionalDetails.tipoDocumentConsignor", "Tipo Document Consignor");
                map.put("additionalDetails.andesTicket", "Andes Ticket");
                map.put("additionalDetails.warehouseId", "Warehouse Id");
                map.put("additionalDetails.activityType", "Activity Type");
                map.put("additionalDetails.hsnNumber", "Hsn Number");
                map.put("additionalDetails.IGMFileDate", "IGM File Date");
                map.put("additionalDetails.IGMInwardDate", "IGM Inward Date");
                map.put("additionalDetails.inwardDateAndTime", "Inward Date And Time");
                map.put("additionalDetails.lineNumber", "Line Number");
                map.put("additionalDetails.subLineNumber", "SubLine Number");
                map.put("additionalDetails.localLineNumber", "Local Line Number");
                map.put("additionalDetails.SMTPIGMNumber", "SMTPIGM Number");
                map.put("additionalDetails.SMTPIGMDate", "SMTPIGM Date");
                map.put("additionalDetails.isInland", "Is Inland");
                map.put("additionalDetails.ownership", "Ownership");
                map.put("additionalDetails.ownershipName", "Ownership Name");
                map.put("additionalDetails.passedBy", "Passed By");
                map.put("additionalDetails.passedByPerson", "Passed By Person");
                map.put("additionalDetails.lgdStatus", "Lgd Status");
                map.put("additionalDetails.isCmsHBLSent", "Is Cms HBL Sent");
                map.put("additionalDetails.isCreditOverrideApproved", "Is Credit Override Approved");
                map.put("additionalDetails.freeDays", "Free Days");
                map.put("additionalDetails.supplierInvoiceNumber", "Supplier Invoice Number");
                map.put("additionalDetails.supplierInvoiceDate", "Supplier Invoice Date");
                map.put("additionalDetails.invoiceValue", "Invoice Value");
                map.put("additionalDetails.assessValue", "Assess Value");
                map.put("additionalDetails.CIFValue", "CIF Value");
                map.put("additionalDetails.totalDuty", "Total Duty");
                map.put("additionalDetails.externalNotes", "External Notes");
                map.put("additionalDetails.bondedWarehouseId", "Bonded Warehouse Id");
                map.put("additionalDetails.releaseType", "Release Type");
                map.put("additionalDetails.houseBillType", "House Bill Type");
                map.put("additionalDetails.onBoard", "On Board");
                map.put("additionalDetails.onBoardDate", "On Board Date");
                map.put("additionalDetails.deliveryMode", "DeliveryMode");
                map.put("additionalDetails.original", "Original");
                map.put("additionalDetails.copy", "Copy");
                map.put("additionalDetails.BLChargesDisplay", "BL Charges Display");
                map.put("additionalDetails.BLExporterShipment", "BL Exporter Shipment");
                map.put("additionalDetails.screeningStatus", "Screening Status");
                map.put("additionalDetails.paidPlace", "Paid Place");
                map.put("additionalDetails.placeOfIssue", "Place Of Issue");
                map.put("additionalDetails.placeOfSupply", "Place Of Supply");
                map.put("additionalDetails.dateOfIssue", "Date Of Issue");
                map.put("additionalDetails.dateOfReceipt", "Date Of Receipt");
                map.put("additionalDetails.goodsCO", "Goods CO");
                map.put("additionalDetails.BOENumber", "BOE Number");
                map.put("additionalDetails.BOEDate", "BOE Date");
                map.put("additionalDetails.WBLPrinted", "WBL Printed");
                map.put("additionalDetails.draftPrinted", "Draft Printed");
                map.put("additionalDetails.shipmentId", SHIPMENT_ID_VALUE);
                map.put("additionalDetails.customDeclType", "Custom Decl Type");
                map.put("additionalDetails.agentReference", "Agent Reference");
                map.put("additionalDetails.bLTermsandConditionsId", "BL Terms And Conditions Id");
                map.put("additionalDetails.blComments", "Bl Comments");
                map.put("additionalDetails.cargoTerms", "Cargo Terms");
                map.put("additionalDetails.cargoTermsDescription", "Cargo Terms Description");
                map.put("additionalDetails.bLRemarks", "BL Remarks");
                map.put("additionalDetails.bLRemarksDescription", "BL Remarks Description");
                map.put("additionalDetails.summary", "Summary");
                map.put("additionalDetails.isSummaryUpdated", "Is Summary Updated");

                map.put("additionalDetails.ownershipOrg", "Ownership Org");
                map.put("additionalDetails.ownershipOrg.entityId", "Ownership Org: Entity Id");
                map.put("additionalDetails.ownershipOrg.entityType", "Ownership Org: Entity Type");
                map.put("additionalDetails.ownershipOrg.type", "Ownership Org: Type");
                map.put("additionalDetails.ownershipOrg.orgCode", "Ownership Org: Org Code");
                map.put("additionalDetails.ownershipOrg.addressCode", "Ownership Org: Address Code");
                map.put("additionalDetails.ownershipOrg.orgData", "Ownership Org: Org Data");
                map.put("additionalDetails.ownershipOrg.addressData", "Ownership Org: Address Data");
                map.put("additionalDetails.ownershipOrg.isAddressFreeText", "Ownership Org: Is Address Free Text");

                map.put("additionalDetails.notifyParty", "Notify Party");
                map.put("additionalDetails.notifyParty.entityId", "Notify Party: Entity Id");
                map.put("additionalDetails.notifyParty.entityType", "Notify Party: Entity Type");
                map.put("additionalDetails.notifyParty.type", "Notify Party: Type");
                map.put("additionalDetails.notifyParty.orgCode", "Notify Party: Org Code");
                map.put("additionalDetails.notifyParty.addressCode", "Notify Party: Address Code");
                map.put("additionalDetails.notifyParty.orgData", "Notify Party: Org Data");
                map.put("additionalDetails.notifyParty.addressData", "Notify Party: Address Data");
                map.put("additionalDetails.notifyParty.isAddressFreeText", "Notify Party: Is Address Free Text");

                map.put("additionalDetails.importBroker", "Import Broker");
                map.put("additionalDetails.importBroker.entityId", "Import Broker: Entity Id");
                map.put("additionalDetails.importBroker.entityType", "Import Broker: Entity Type");
                map.put("additionalDetails.importBroker.type", "Import Broker: Type");
                map.put("additionalDetails.importBroker.orgCode", "Import Broker: Org Code");
                map.put("additionalDetails.importBroker.addressCode", "Import Broker: Address Code");
                map.put("additionalDetails.importBroker.orgData", "Import Broker: Org Data");
                map.put("additionalDetails.importBroker.addressData", "Import Broker: Address Data");
                map.put("additionalDetails.importBroker.isAddressFreeText", "Import Broker: Is Address Free Text");

                map.put("additionalDetails.exportBroker", "Export Broker");
                map.put("additionalDetails.exportBroker.entityId", "Export Broker: Entity Id");
                map.put("additionalDetails.exportBroker.entityType", "Export Broker: Entity Type");
                map.put("additionalDetails.exportBroker.type", "Export Broker: Type");
                map.put("additionalDetails.exportBroker.orgCode", "Export Broker: Org Code");
                map.put("additionalDetails.exportBroker.addressCode", "Export Broker: Address Code");
                map.put("additionalDetails.exportBroker.orgData", "Export Broker: Org Data");
                map.put("additionalDetails.exportBroker.addressData", "Export Broker: Address Data");
                map.put("additionalDetails.exportBroker.isAddressFreeText", "Export Broker: Is Address Free Text");

                map.put("additionalDetails.sendingForwarder", "Sending Forwarder");
                map.put("additionalDetails.sendingForwarder.entityId", "Sending Forwarder: Entity Id");
                map.put("additionalDetails.sendingForwarder.entityType", "Sending Forwarder: Entity Type");
                map.put("additionalDetails.sendingForwarder.type", "Sending Forwarder: Type");
                map.put("additionalDetails.sendingForwarder.orgCode", "Sending Forwarder: Org Code");
                map.put("additionalDetails.sendingForwarder.addressCode", "Sending Forwarder: Address Code");
                map.put("additionalDetails.sendingForwarder.orgData", "Sending Forwarder: Org Data");
                map.put("additionalDetails.sendingForwarder.addressData", "Sending Forwarder: Address Data");
                map.put("additionalDetails.sendingForwarder.isAddressFreeText", "Sending Forwarder: Is Address Free Text");

                map.put("additionalDetails.receivingForwarder", "Receiving Forwarder");
                map.put("additionalDetails.receivingForwarder.entityId", "Receiving Forwarder: Entity Id");
                map.put("additionalDetails.receivingForwarder.entityType", "Receiving Forwarder: Entity Type");
                map.put("additionalDetails.receivingForwarder.type", "Receiving Forwarder: Type");
                map.put("additionalDetails.receivingForwarder.orgCode", "Receiving Forwarder: Org Code");
                map.put("additionalDetails.receivingForwarder.addressCode", "Receiving Forwarder: Address Code");
                map.put("additionalDetails.receivingForwarder.orgData", "Receiving Forwarder: Org Data");
                map.put("additionalDetails.receivingForwarder.addressData", "Receiving Forwarder: Address Data");
                map.put("additionalDetails.receivingForwarder.isAddressFreeText", "Receiving Forwarder: Is Address Free Text");

                map.put("additionalDetails.traderOrSupplier", "Trader Or Supplier");
                map.put("additionalDetails.traderOrSupplier.entityId", "Trader Or Supplier: Entity Id");
                map.put("additionalDetails.traderOrSupplier.entityType", "Trader Or Supplier: Entity Type");
                map.put("additionalDetails.traderOrSupplier.type", "Trader Or Supplier: Type");
                map.put("additionalDetails.traderOrSupplier.orgCode", "Trader Or Supplier: Org Code");
                map.put("additionalDetails.traderOrSupplier.addressCode", "Trader Or Supplier: Address Code");
                map.put("additionalDetails.traderOrSupplier.orgData", "Trader Or Supplier: Org Data");
                map.put("additionalDetails.traderOrSupplier.addressData", "Trader Or Supplier: Address Data");
                map.put("additionalDetails.traderOrSupplier.isAddressFreeText", "Trader Or Supplier: Is Address Free Text");

                map.put("additionalDetails.eTailor", "eTailor");
                map.put("additionalDetails.eTailor.entityId", "eTailor: Entity Id");
                map.put("additionalDetails.eTailor.entityType", "eTailor: Entity Type");
                map.put("additionalDetails.eTailor.type", "eTailor: Type");
                map.put("additionalDetails.eTailor.orgCode", "eTailor: Org Code");
                map.put("additionalDetails.eTailor.addressCode", "eTailor: Address Code");
                map.put("additionalDetails.eTailor.orgData", "eTailor: Org Data");
                map.put("additionalDetails.eTailor.addressData", "eTailor: Address Data");
                map.put("additionalDetails.eTailor.isAddressFreeText", "eTailor: Is Address Free Text");

                map.put("additionalDetails.borrowedFrom", "Borrowed From");
                map.put("additionalDetails.borrowedFrom.entityId", "Borrowed From: Entity Id");
                map.put("additionalDetails.borrowedFrom.entityType", "Borrowed From: Entity Type");
                map.put("additionalDetails.borrowedFrom.type", "Borrowed From: Type");
                map.put("additionalDetails.borrowedFrom.orgCode", "Borrowed From: Org Code");
                map.put("additionalDetails.borrowedFrom.addressCode", "Borrowed From: Address Code");
                map.put("additionalDetails.borrowedFrom.orgData", "Borrowed From: Org Data");
                map.put("additionalDetails.borrowedFrom.addressData", "Borrowed From: Address Data");
                map.put("additionalDetails.borrowedFrom.isAddressFreeText", "Borrowed From: Is Address Free Text");

                map.put("additionalDetails.sendingAgent", "Sending Agent");
                map.put("additionalDetails.sendingAgent.entityId", "Sending Agent: Entity Id");
                map.put("additionalDetails.sendingAgent.entityType", "Sending Agent: Entity Type");
                map.put("additionalDetails.sendingAgent.type", "Sending Agent: Type");
                map.put("additionalDetails.sendingAgent.orgCode", "Sending Agent: Org Code");
                map.put("additionalDetails.sendingAgent.addressCode", "Sending Agent: Address Code");
                map.put("additionalDetails.sendingAgent.orgData", "Sending Agent: Org Data");
                map.put("additionalDetails.sendingAgent.addressData", "Sending Agent: Address Data");
                map.put("additionalDetails.sendingAgent.isAddressFreeText", "Sending Agent: Is Address Free Text");

                map.put("additionalDetails.receivingAgent", "Receiving Agent");
                map.put("additionalDetails.receivingAgent.entityId", "Receiving Agent: Entity Id");
                map.put("additionalDetails.receivingAgent.entityType", "Receiving Agent: Entity Type");
                map.put("additionalDetails.receivingAgent.type", "Receiving Agent: Type");
                map.put("additionalDetails.receivingAgent.orgCode", "Receiving Agent: Org Code");
                map.put("additionalDetails.receivingAgent.addressCode", "Receiving Agent: Address Code");
                map.put("additionalDetails.receivingAgent.orgData", "Receiving Agent: Org Data");
                map.put("additionalDetails.receivingAgent.addressData", "Receiving Agent: Address Data");
                map.put("additionalDetails.receivingAgent.isAddressFreeText", "Receiving Agent: Is Address Free Text");

                map.put("carrierDetails", "Carrier Details");
                map.put("carrierDetails.shippingLine", "Shipping Line");
                map.put("carrierDetails.vessel", "Vessel");
                map.put("carrierDetails.voyage", VOYAGE_VAL);
                map.put("carrierDetails.flightNumber", "Flight Number");
                map.put("carrierDetails.aircraftType", "Aircraft Type");
                map.put("carrierDetails.aircraftRegistration", "Aircraft Registration");
                map.put("carrierDetails.truckRefNumber", "Truck Ref Number");
                map.put("carrierDetails.journeyNumber", "Journey Number");
                map.put("carrierDetails.journeyRefNumber", "Journey Ref Number");
                map.put("carrierDetails.origin", "Origin");
                map.put("carrierDetails.destination", "Destination");
                map.put("carrierDetails.originPort", "Origin Port");
                map.put("carrierDetails.destinationPort", "Destination Port");
                map.put("carrierDetails.eta", "Eta");
                map.put("carrierDetails.etd", "Etd");
                map.put("carrierDetails.ata", "Ata");
                map.put("carrierDetails.atd", "Atd");
                map.put("carrierDetails.vesselBerthingDate", "Vessel Berthing Date");
                map.put("carrierDetails.voyageOrFlightNumber", "Voyage Or Flight Number");

                map.put("deliveryDetails", "Delivery Details");
                map.put("deliveryDetails.estimatedPickupOrDelivery", "Delivery Details: Estimated Pickup Or Delivery");
                map.put("deliveryDetails.estimatedPickup", "Delivery Details: Estimated Pickup");
                map.put("deliveryDetails.estimatedDelivery", "Delivery Details: Estimated Delivery");
                map.put("deliveryDetails.requiredBy", "Delivery Details: Required By");
                map.put("deliveryDetails.portTransportAdvised", "Delivery Details: Port Transport Advised");
                map.put("deliveryDetails.actualPickupOrDelivery", "Delivery Details: Actual Pickup Or Delivery");
                map.put("deliveryDetails.actualPickup", "Delivery Details: Actual Pickup ");
                map.put("deliveryDetails.actualDelivery", "Delivery Details: Actual Delivery ");
                map.put("deliveryDetails.pickupOrDelivery", "Delivery Details: Pickup Or Delivery");
                map.put("deliveryDetails.type", "Delivery Details: Type");
                map.put("deliveryDetails.shipmentId", "Delivery Details: Shipment Id");
                map.put("deliveryDetails.dropMode", "Delivery Details: Drop Mode");
                map.put("deliveryDetails.labourCharge", "Delivery Details: Labour Charge");
                map.put("deliveryDetails.labourChargeUnit", "Delivery Details: Labour Charge Unit");
                map.put("deliveryDetails.labourDuration", "Delivery Details: Labour Duration");
                map.put("deliveryDetails.shipperRef", "Delivery Details: Shipper Ref");
                map.put("deliveryDetails.interimReceipt", "Delivery Details: Interim Receipt");
                map.put("deliveryDetails.fclAvailableDate", "Delivery Details: Fcl Available Date");
                map.put("deliveryDetails.truckWaitTimeCharge", "Delivery Details: Truck Wait Time Charge");
                map.put("deliveryDetails.truckWaitTimeChargeUnit", "Delivery Details: Truck Wait Time Charge Unit");
                map.put("deliveryDetails.truckWaitDuration", "Delivery Details: Truck Wait Duration");
                map.put("deliveryDetails.storageChargeUnit", "Delivery Details: Storage Charge Unit");
                map.put("deliveryDetails.storageChargeDuration", "Delivery Details: Storage Charge Duration");
                map.put("deliveryDetails.ucrReference", "Delivery Details: Ucr Reference");
                map.put("deliveryDetails.emptyTruckInDate", "Delivery Details: Empty Truck In Date");
                map.put("deliveryDetails.loadedTruckGateOutDate", "Delivery Details: Loaded Truck Gate Out Date");
                map.put("deliveryDetails.pickupDeliveryInstruction", "Delivery Details: Pickup Delivery Instruction");
                map.put("deliveryDetails.pickupGateIn", "Delivery Details: Pickup Gate In");
                map.put("deliveryDetails.deliveryGateIn", "Delivery Details: Delivery Gate In");
                map.put("deliveryDetails.pickupGateOut", "Delivery Details: Pickup Gate Out");
                map.put("deliveryDetails.deliveryGateOut", "Delivery Details: Delivery Gate Out");

                map.put("deliveryDetails.transporterDetail", "Delivery Details: Transporter Detail");
                map.put("deliveryDetails.transporterDetail.entityId", "Delivery Details: Transporter Detail: Entity Id");
                map.put("deliveryDetails.transporterDetail.entityType", "Delivery Details: Transporter Detail: Entity Type");
                map.put("deliveryDetails.transporterDetail.type", "Delivery Details: Transporter Detail: Type");
                map.put("deliveryDetails.transporterDetail.orgCode", "Delivery Details: Transporter Detail: Org Code");
                map.put("deliveryDetails.transporterDetail.addressCode", "Delivery Details: Transporter Detail: Address Code");
                map.put("deliveryDetails.transporterDetail.orgData", "Delivery Details: Transporter Detail: Org Data");
                map.put("deliveryDetails.transporterDetail.addressData", "Delivery Details: Transporter Detail: Address Data");
                map.put("deliveryDetails.transporterDetail.isAddressFreeText", "Delivery Details: Transporter Detail: Is Address Free Text");

                map.put("deliveryDetails.brokerDetail", "Delivery Details: Broker Detail");
                map.put("deliveryDetails.brokerDetail.entityId", "Delivery Details: Broker Detail: Entity Id");
                map.put("deliveryDetails.brokerDetail.entityType", "Delivery Details: Broker Detail: Entity Type");
                map.put("deliveryDetails.brokerDetail.type", "Delivery Details: Broker Detail: Type");
                map.put("deliveryDetails.brokerDetail.orgCode", "Delivery Details: Broker Detail: Org Code");
                map.put("deliveryDetails.brokerDetail.addressCode", "Delivery Details: Broker Detail: Address Code");
                map.put("deliveryDetails.brokerDetail.orgData", "Delivery Details: Broker Detail: Org Data");
                map.put("deliveryDetails.brokerDetail.addressData", "Delivery Details: Broker Detail: Address Data");
                map.put("deliveryDetails.brokerDetail.isAddressFreeText", "Delivery Details: Broker Detail: Is Address Free Text");

                map.put("deliveryDetails.destinationDetail", "Delivery Details: Destination Detail");
                map.put("deliveryDetails.destinationDetail.entityId", "Delivery Details: Destination Detail: Entity Id");
                map.put("deliveryDetails.destinationDetail.entityType", "Delivery Details: Destination Detail: Entity Type");
                map.put("deliveryDetails.destinationDetail.type", "Delivery Details: Destination Detail: Type");
                map.put("deliveryDetails.destinationDetail.orgCode", "Delivery Details: Destination Detail: Org Code");
                map.put("deliveryDetails.destinationDetail.addressCode", "Delivery Details: Destination Detail: Address Code");
                map.put("deliveryDetails.destinationDetail.orgData", "Delivery Details: Destination Detail: Org Data");
                map.put("deliveryDetails.destinationDetail.addressData", "Delivery Details: Destination Detail: Address Data");
                map.put("deliveryDetails.destinationDetail.isAddressFreeText", "Delivery Details: Destination Detail: Is Address Free Text");

                map.put("deliveryDetails.sourceDetail", "Delivery Details: Source Detail");
                map.put("deliveryDetails.sourceDetail.entityId", "Delivery Details: Source Detail: Entity Id");
                map.put("deliveryDetails.sourceDetail.entityType", "Delivery Details: Source Detail: Entity Type");
                map.put("deliveryDetails.sourceDetail.type", "Delivery Details: Source Detail: Type");
                map.put("deliveryDetails.sourceDetail.orgCode", "Delivery Details: Source Detail: Org Code");
                map.put("deliveryDetails.sourceDetail.addressCode", "Delivery Details: Source Detail: Address Code");
                map.put("deliveryDetails.sourceDetail.orgData", "Delivery Details: Source Detail: Org Data");
                map.put("deliveryDetails.sourceDetail.addressData", "Delivery Details: Source Detail: Address Data");
                map.put("deliveryDetails.sourceDetail.isAddressFreeText", "Delivery Details: Source Detail: Is Address Free Text");

                map.put("deliveryDetails.agentDetail", "Delivery Details: Agent Detail");
                map.put("deliveryDetails.agentDetail.entityId", "Delivery Details: Agent Detail: Entity Id");
                map.put("deliveryDetails.agentDetail.entityType", "Delivery Details: Agent Detail: Entity Type");
                map.put("deliveryDetails.agentDetail.type", "Delivery Details: Agent Detail: Type");
                map.put("deliveryDetails.agentDetail.orgCode", "Delivery Details: Agent Detail: Org Code");
                map.put("deliveryDetails.agentDetail.addressCode", "Delivery Details: Agent Detail: Address Code");
                map.put("deliveryDetails.agentDetail.orgData", "Delivery Details: Agent Detail: Org Data");
                map.put("deliveryDetails.agentDetail.addressData", "Delivery Details: Agent Detail: Address Data");
                map.put("deliveryDetails.agentDetail.isAddressFreeText", "Delivery Details: Agent Detail: Is Address Free Text");


                map.put("pickupDetails", "Pickup Details");
                map.put("pickupDetails.estimatedPickupOrDelivery", "Pickup Details: Estimated Pickup Or Delivery");
                map.put("pickupDetails.requiredBy", "Pickup Details: Required By");
                map.put("pickupDetails.portTransportAdvised", "Pickup Details: Port Transport Advised");
                map.put("pickupDetails.actualPickupOrDelivery", "Pickup Details: Actual Pickup Or Delivery");
                map.put("pickupDetails.pickupOrDelivery", "Pickup Details: Pickup Or Delivery");
                map.put("pickupDetails.type", "Pickup Details: Type");
                map.put("pickupDetails.shipmentId", "Pickup Details: Shipment Id");
                map.put("pickupDetails.dropMode", "Pickup Details: Drop Mode");
                map.put("pickupDetails.labourCharge", "Pickup Details: Labour Charge");
                map.put("pickupDetails.labourChargeUnit", "Pickup Details: Labour Charge Unit");
                map.put("pickupDetails.labourDuration", "Pickup Details: Labour Duration");
                map.put("pickupDetails.shipperRef", "Pickup Details: Shipper Ref");
                map.put("pickupDetails.interimReceipt", "Pickup Details: Interim Receipt");
                map.put("pickupDetails.fclAvailableDate", "Pickup Details: Fcl Available Date");
                map.put("pickupDetails.truckWaitTimeCharge", "Pickup Details: Truck Wait Time Charge");
                map.put("pickupDetails.truckWaitTimeChargeUnit", "Pickup Details: Truck Wait Time Charge Unit");
                map.put("pickupDetails.truckWaitDuration", "Pickup Details: Truck Wait Duration");
                map.put("pickupDetails.storageChargeUnit", "Pickup Details: Storage Charge Unit");
                map.put("pickupDetails.storageChargeDuration", "Pickup Details: Storage Charge Duration");
                map.put("pickupDetails.ucrReference", "Pickup Details: Ucr Reference");
                map.put("pickupDetails.emptyTruckInDate", "Pickup Details: Empty Truck In Date");
                map.put("pickupDetails.loadedTruckGateOutDate", "Pickup Details: Loaded Truck Gate Out Date");
                map.put("pickupDetails.pickupDeliveryInstruction", "Pickup Details: Pickup Delivery Instruction");

                map.put("pickupDetails.pickupGateIn", "Pickup Details : Pickup Gate In");
                map.put("pickupDetails.deliveryGateIn", "Pickup Details : Delivery Gate In");
                map.put("pickupDetails.pickupGateOut", "Pickup Details : Pickup Gate Out");
                map.put("pickupDetails.deliveryGateOut", "Pickup Details : Delivery Gate Out");
                map.put("pickupDetails.estimatedPickup", "Pickup Details: Estimated Pickup");
                map.put("pickupDetails.estimatedDelivery", "Pickup Details: Estimated Delivery");
                map.put("pickupDetails.actualPickup", "Pickup Details: Actual Pickup ");
                map.put("pickupDetails.actualDelivery", "Pickup Details: Actual Delivery ");

                map.put("pickupDetails.transporterDetail", "Pickup Details: Transporter Detail");
                map.put("pickupDetails.transporterDetail.entityId", "Pickup Details: Transporter Detail: Entity Id");
                map.put("pickupDetails.transporterDetail.entityType", "Pickup Details: Transporter Detail: Entity Type");
                map.put("pickupDetails.transporterDetail.type", "Pickup Details: Transporter Detail: Type");
                map.put("pickupDetails.transporterDetail.orgCode", "Pickup Details: Transporter Detail: Org Code");
                map.put("pickupDetails.transporterDetail.addressCode", "Pickup Details: Transporter Detail: Address Code");
                map.put("pickupDetails.transporterDetail.orgData", "Pickup Details: Transporter Detail: Org Data");
                map.put("pickupDetails.transporterDetail.addressData", "Pickup Details: Transporter Detail: Address Data");
                map.put("pickupDetails.transporterDetail.isAddressFreeText", "Pickup Details: Transporter Detail: Is Address Free Text");

                map.put("pickupDetails.brokerDetail", "Pickup Details: Broker Detail");
                map.put("pickupDetails.brokerDetail.entityId", "Pickup Details: Broker Detail: Entity Id");
                map.put("pickupDetails.brokerDetail.entityType", "Pickup Details: Broker Detail: Entity Type");
                map.put("pickupDetails.brokerDetail.type", "Pickup Details: Broker Detail: Type");
                map.put("pickupDetails.brokerDetail.orgCode", "Pickup Details: Broker Detail: Org Code");
                map.put("pickupDetails.brokerDetail.addressCode", "Pickup Details: Broker Detail: Address Code");
                map.put("pickupDetails.brokerDetail.orgData", "Pickup Details: Broker Detail: Org Data");
                map.put("pickupDetails.brokerDetail.addressData", "Pickup Details: Broker Detail: Address Data");
                map.put("pickupDetails.brokerDetail.isAddressFreeText", "Pickup Details: Broker Detail: Is Address Free Text");

                map.put("pickupDetails.destinationDetail", "Pickup Details: Destination Detail");
                map.put("pickupDetails.destinationDetail.entityId", "Pickup Details: Destination Detail: Entity Id");
                map.put("pickupDetails.destinationDetail.entityType", "Pickup Details: Destination Detail: Entity Type");
                map.put("pickupDetails.destinationDetail.type", "Pickup Details: Destination Detail: Type");
                map.put("pickupDetails.destinationDetail.orgCode", "Pickup Details: Destination Detail: Org Code");
                map.put("pickupDetails.destinationDetail.addressCode", "Pickup Details: Destination Detail: Address Code");
                map.put("pickupDetails.destinationDetail.orgData", "Pickup Details: Destination Detail: Org Data");
                map.put("pickupDetails.destinationDetail.addressData", "Pickup Details: Destination Detail: Address Data");
                map.put("pickupDetails.destinationDetail.isAddressFreeText", "Pickup Details: Destination Detail: Is Address Free Text");

                map.put("pickupDetails.sourceDetail", "Pickup Details: Source Detail");
                map.put("pickupDetails.sourceDetail.entityId", "Pickup Details: Source Detail: Entity Id");
                map.put("pickupDetails.sourceDetail.entityType", "Pickup Details: Source Detail: Entity Type");
                map.put("pickupDetails.sourceDetail.type", "Pickup Details: Source Detail: Type");
                map.put("pickupDetails.sourceDetail.orgCode", "Pickup Details: Source Detail: Org Code");
                map.put("pickupDetails.sourceDetail.addressCode", "Pickup Details: Source Detail: Address Code");
                map.put("pickupDetails.sourceDetail.orgData", "Pickup Details: Source Detail: Org Data");
                map.put("pickupDetails.sourceDetail.addressData", "Pickup Details: Source Detail: Address Data");
                map.put("pickupDetails.sourceDetail.isAddressFreeText", "Pickup Details: Source Detail: Is Address Free Text");

                map.put("pickupDetails.agentDetail", "Pickup Details: Agent Detail");
                map.put("pickupDetails.agentDetail.entityId", "Pickup Details: Agent Detail: Entity Id");
                map.put("pickupDetails.agentDetail.entityType", "Pickup Details: Agent Detail: Entity Type");
                map.put("pickupDetails.agentDetail.type", "Pickup Details: Agent Detail: Type");
                map.put("pickupDetails.agentDetail.orgCode", "Pickup Details: Agent Detail: Org Code");
                map.put("pickupDetails.agentDetail.addressCode", "Pickup Details: Agent Detail: Address Code");
                map.put("pickupDetails.agentDetail.orgData", "Pickup Details: Agent Detail: Org Data");
                map.put("pickupDetails.agentDetail.addressData", "Pickup Details: Agent Detail: Address Data");
                map.put("pickupDetails.agentDetail.isAddressFreeText", "Pickup Details: Agent Detail: Is Address Free Text");


                map.put("client", "Client");
                map.put("client.entityId", "Client: Entity Id");
                map.put("client.entityType", "Client: Entity Type");
                map.put("client.type", "Client: Type");
                map.put("client.orgCode", "Client: Org Code");
                map.put("client.addressCode", "Client: Address Code");
                map.put("client.orgData", "Client: Org Data");
                map.put("client.addressData", "Client: Address Data");
                map.put("client.isAddressFreeText", "Client: Is Address Free Text");

                map.put("consigner", "Consigner");
                map.put("consigner.entityId", "Consigner: Entity Id");
                map.put("consigner.entityType", "Consigner: Entity Type");
                map.put("consigner.type", "Consigner: Type");
                map.put("consigner.orgCode", "Consigner: Org Code");
                map.put("consigner.addressCode", "Consigner: Address Code");
                map.put("consigner.orgData", "Consigner: Org Data");
                map.put("consigner.addressData", "Consigner: Address Data");
                map.put("consigner.isAddressFreeText", "Consigner: Is Address Free Text");

                map.put("consignee", "Consignee");
                map.put("consignee.entityId", "Consignee: Entity Id");
                map.put("consignee.entityType", "Consignee: Entity Type");
                map.put("consignee.type", "Consignee: Type");
                map.put("consignee.orgCode", "Consignee: Org Code");
                map.put("consignee.addressCode", "Consignee: Address Code");
                map.put("consignee.orgData", "Consignee: Org Data");
                map.put("consignee.addressData", "Consignee: Address Data");
                map.put("consignee.isAddressFreeText", "Consignee: Is Address Free Text");

                // Make the map immutable
                ShipmentsFieldNameToDisplayNameMap = Collections.unmodifiableMap(map);
        }

        public static final String CONSOLIDATION_ID = "consolidationId";
        public static final String CONSOLIDATION_ID_VAL = "Consolidation Id";
        public static final String BOOKING_ID_VAL = "Booking Id";
        public static final String BOOKING_ID = "bookingId";
        public static final String ENTITY_ID_VAL = "Entity Id";
        public static final String ENTITY_TYPE_VAL = "Entity Type";
        public static final String ORG_CODE_VAL = "Org Code";
        public static final String ADDRESS_CODE_VAL = "Address Code";
        public static final String ORG_DATA_VAL = "Org Data";
        public static final String ADDRESS_DATA_VAL = "Address Data";
        public static final String IS_ADDRESS_FREE_TEXT_VAL = "Is Address Free Text";
        public static final String CONTAINER_CODE = "containerCode";
        public static final Map<String, String> ContainerFieldNameToDisplayNameMap;
        static {
                Map<String, String> map = new HashMap<>();
                map.put(CONSOLIDATION_ID, CONSOLIDATION_ID_VAL);
                map.put(BOOKING_ID, BOOKING_ID_VAL);
                map.put("loggingId", "Logging Id");
                map.put(CONTAINER_CODE, "Container Code");
                map.put("sealNumber", "Seal Number");
                map.put("descriptionOfGoods", "Description Of Goods");
                map.put(NET_WEIGHT, NET_WEIGHT_VAL);
                map.put(NET_WEIGHT_UNIT, NET_WEIGHT_UNIT_VAL);
                map.put("grossWeight", "Gross Weight");
                map.put("grossWeightUnit", "Gross Weight Unit");
                map.put("measurement", "Measurement");
                map.put("measurementUnit", "Measurement Unit");
                map.put("commodityCode", "Commodity Code");
                map.put("hsCode", "Hs Code");
                map.put("isShipperOwned", "Is Shipper Owned");
                map.put("isEmpty", "Is Empty");
                map.put("containerCount", "Container Count");
                map.put("carrierSealNumber", "Carrier Seal Number");
                map.put("shipperSealNumber", "Shipper Seal Number");
                map.put("terminalOperatorSealNumber", "Terminal Operator Seal Number");
                map.put("veterinarySealNumber", "Veterinary Seal Number");
                map.put("customsSealNumber", "Customs Seal Number");
                map.put("customsReleaseCode", "Customs Release Code");
                map.put("containerStuffingLocation", "Container Stuffing Location");
                map.put("containerComments", "Container Comments");
                map.put("grossVolume", "Gross Volume");
                map.put("grossVolumeUnit", "Gross Volume Unit");
                map.put("isReefer", "Is Reefer");
                map.put("minTemp", "Min Temp");
                map.put("minTempUnit", "Min Temp Unit");
                map.put("maxTemp", "Max Temp");
                map.put("maxTempUnit", "Max Temp Unit");
                map.put("hblDeliveryMode", "Hbl Delivery Mode");
                map.put("allocationDate", "Allocation Date");
                map.put("dgClass", "Dg Class");
                map.put("hazardous", "Hazardous");
                map.put("hazardousUn", "Hazardous Un");
                map.put("tareWeight", "Tare Weight");
                map.put("tareWeightUnit", "Tare Weight Unit");
                map.put("serialNumber", "Serial Number");
                map.put("innerPackageNumber", "Inner Package Number");
                map.put("innerPackageType", "Inner Package Type");
                map.put("packageLength", "Package Length");
                map.put("packageBreadth", "Package Breadth");
                map.put("packageHeight", "Package Height");
                map.put("isTemperatureMaintained", "Is Temperature Maintained");
                map.put("packs", "Packs");
                map.put("packsType", "Packs Type");
                map.put("marksNums", "MarksNums");
                map.put("innerPackageMeasurementUnit", "Inner Package Measurement Unit");
                map.put("pacrNumber", "Pacr Number");
                map.put("chargeable", "Chargeable");
                map.put(CHARGEABLE_UNIT, CHARGEABLE_UNIT_VAL);
                map.put("isOwnContainer", "Is Own Container");
                map.put(TRANSPORT_MODE, TRANSPORT_MODE_VALUE);
                map.put("status", "Status");
                map.put("extraParams", "Extra Params");
                map.put("remarks", "Remarks");
                map.put("allocatedWeight", "Allocated Weight");
                map.put("allocatedWeightUnit", "Allocated Weight Unit");
                map.put("allocatedVolume", "Allocated Volume");
                map.put("allocatedVolumeUnit", "Allocated Volume Unit");
                map.put("achievedWeight", "Achieved Weight");
                map.put("achievedWeightUnit", "Achieved Weight Unit");
                map.put("achievedVolume", "Achieved Volume");
                map.put("achievedVolumeUnit", "Achieved Volume Unit");
                map.put("weightUtilization", "Weight Utilization");
                map.put("volumeUtilization", "Volume Utilization");

                map.put("commodityGroup", "Commodity Group");
                map.put("isContractEnforced", "Is Contract Enforced");
                map.put("contractEnforcedQuantityLimit", "Contract Enforced Quantity Limit");
                map.put("ownType", "Own Type");
                map.put("handlingInfo", "Handling Info");
                map.put("isPart", "Is Part");
                map.put("isAttached", "Is Attached");

                map.put("pickupAddress", "Pickup Address");
                map.put("pickupAddress.entityId", ENTITY_ID_VAL);
                map.put("pickupAddress.entityType", ENTITY_TYPE_VAL);
                map.put("pickupAddress.type", "Type");
                map.put("pickupAddress.orgCode", ORG_CODE_VAL);
                map.put("pickupAddress.addressCode", ADDRESS_CODE_VAL);
                map.put("pickupAddress.orgData", ORG_DATA_VAL);
                map.put("pickupAddress.addressData", ADDRESS_DATA_VAL);
                map.put("pickupAddress.isAddressFreeText", IS_ADDRESS_FREE_TEXT_VAL);

                map.put("deliveryAddress", "Delivery Address");
                map.put("deliveryAddress.entityId", ENTITY_ID_VAL);
                map.put("deliveryAddress.entityType", ENTITY_TYPE_VAL);
                map.put("deliveryAddress.type", "Type");
                map.put("deliveryAddress.orgCode", ORG_CODE_VAL);
                map.put("deliveryAddress.addressCode", ADDRESS_CODE_VAL);
                map.put("deliveryAddress.orgData", ORG_DATA_VAL);
                map.put("deliveryAddress.addressData", ADDRESS_DATA_VAL);
                map.put("deliveryAddress.isAddressFreeText", IS_ADDRESS_FREE_TEXT_VAL);

                ContainerFieldNameToDisplayNameMap = Collections.unmodifiableMap(map);
        }

        public static final String REFERENCE_NUMBER_VAL = "Reference Number";
        public static final Map<String, String> PackingFieldNameToDisplayNameMap;
        static {
                Map<String, String> map = new HashMap<>();
                map.put(CONSOLIDATION_ID, CONSOLIDATION_ID_VAL);
                map.put(SHIPMENT_ID, SHIPMENT_ID_VALUE);
                map.put(BOOKING_ID, BOOKING_ID_VAL);
                map.put("DGGoodsId", "DG Goods Id");
                map.put("DGSubstanceId", "DG Substance Id");
                map.put("packs", "Packs");
                map.put("packsType", "Packs Type");
                map.put("weight", "Weight");
                map.put("weightUnit", "Weight Unit");
                map.put("volume", "Volume");
                map.put("volumeUnit", "Volume Unit");
                map.put("inspections", "Inspections");
                map.put("origin", "Origin");
                map.put("commodity", "Commodity");
                map.put("packingOrder", "Packing Order");
                map.put("length", "Length");
                map.put("lengthUnit", "Length Unit");
                map.put("width", "Width");
                map.put("widthUnit", "Width Unit");
                map.put("height", "Height");
                map.put("heightUnit", "Height Unit");
                map.put("marksnNums", "MarksnNums");
                map.put("flashPoint", "Flash Point");
                map.put("UNDGContact", "UNDG Contact");
                map.put("isTemperatureControlled", "Is Temperature Controlled");
                map.put("minTemp", "Min Temp");
                map.put("minTempUnit", "Min Temp Unit");
                map.put("maxTemp", "Max Temp");
                map.put("maxTempUnit", "Max Temp Unit");
                map.put("HSCode", "HS Code");
                map.put("countryCode", "Country Code");
                map.put("goodsDescription", "Goods Description");
                map.put("referenceNumber", REFERENCE_NUMBER_VAL);
                map.put("DGClass", "DG Class");
                map.put("hazardous", "Hazardous");
                map.put("commodityId", "Commodity Id");
                map.put(NET_WEIGHT, NET_WEIGHT_VAL);
                map.put(NET_WEIGHT_UNIT, NET_WEIGHT_UNIT_VAL);
                map.put("volumeWeight", "Volume Weight");
                map.put("volumeWeightUnit", "Volume Weight Unit");
                map.put("vinNumber", "Vin Number");
                map.put("containerId", "Container Id");
                map.put(TRANSPORT_MODE, TRANSPORT_MODE_VALUE);
                map.put("innerPackageNumber", "Inner Package Number");
                map.put("innerPackageType", "Inner Package Type");
                map.put(CHARGEABLE_UNIT, CHARGEABLE_UNIT_VAL);
                map.put("customsReleaseCode", "Customs Release Code");
                map.put("shipmentNumber", "Shipment Number");
                map.put("innerPacksId", "Inner Packs Id");
                map.put("innerPacksCount", "Inner Packs Count");
                map.put("commodityGroup", "Commodity Group");
                map.put("isDimension", "Is Dimension");
                map.put("isContractEnforced", "Is Contract Enforced");
                map.put("handlingInfo", "Handling Info");
                map.put("contractEnforcedQuantityLimit", "Contract Enforced Quantity Limit");

                PackingFieldNameToDisplayNameMap = Collections.unmodifiableMap(map);
        }

        public static final Map<String, String> RoutingsFieldNameToDisplayNameMap;
        static {
                Map<String, String> map = new HashMap<>();
                map.put(BOOKING_ID, BOOKING_ID_VAL);
                map.put(SHIPMENT_ID, SHIPMENT_ID_VALUE);
                map.put("leg", "Leg");
                map.put("mode", "Mode");
                map.put("routingStatus", "Routing Status");
                map.put("vesselName", "Vessel Name");
                map.put("pol", "Pol");
                map.put("pod", "Pod");
                map.put(IS_DOMESTIC, IS_DOMESTIC_VALUE);
                map.put("eta", "Eta");
                map.put("etd", "Etd");
                map.put("ata", "Ata");
                map.put("atd", "Atd");
                map.put(CONSOLIDATION_ID, CONSOLIDATION_ID_VAL);
                map.put("isLinked", "Is Linked");
                map.put("voyage", VOYAGE_VAL);
                map.put("aircraftRegistration", "Aircraft Registration");
                map.put("flightNumber", "Flight Number");
                map.put("aircraftType", "Aircraft Type");
                map.put("routeLegId", "Route Leg Id");
                map.put("vesselId", "Vessel Id");
                map.put("transitDays", "Transit Days");
                map.put("carrier", "Carrier");
                map.put("truckReferenceNumber", "Truck Reference Number");

                RoutingsFieldNameToDisplayNameMap = Collections.unmodifiableMap(map);
        }

        public static final String ENTITY_ID = "entityId";
        public static final String ENTITY_TYPE = "entityType";
        public static final Map<String, String> NotesFieldNameToDisplayNameMap;
        static {
                Map<String, String> map = new HashMap<>();
                map.put("text", "Text");
                map.put("label", "Label");
                map.put("assignedTo", "Asigned To");
                map.put(ENTITY_ID, ENTITY_ID_VAL);
                map.put(ENTITY_TYPE, ENTITY_TYPE_VAL);
                map.put("insertUserId", "Insert User Id");
                map.put("insertDate", "Insert Date");
                map.put("insertUserDisplayName", "Insert User Display Name");
                map.put(IS_DOMESTIC, IS_DOMESTIC_VALUE);
                map.put("isPublic", "Is Public");
                map.put("isActive", "Is Active");

                NotesFieldNameToDisplayNameMap = Collections.unmodifiableMap(map);
        }

        public static final Map<String, String> BookingCarriageFieldNameToDisplayNameMap;
        static {
                Map<String, String> map = new HashMap<>();
                map.put("portOfLoading", "Port Of Loading");
                map.put("portOfDischarge", "Port Of Discharge");
                map.put("eta", "Eta");
                map.put("etd", "Etd");
                map.put("vessel", "Vessel");
                map.put("voyage", VOYAGE_VAL);
                map.put("carriageType", "Carriage Type");
                map.put("carriageMode", "Carriage Mode");
                map.put(SHIPMENT_ID, SHIPMENT_ID_VALUE);

                BookingCarriageFieldNameToDisplayNameMap = Collections.unmodifiableMap(map);
        }

        public static final Map<String, String> EventsFieldNameToDisplayNameMap;
        static {
                Map<String, String> map = new HashMap<>();
                map.put(ENTITY_ID, ENTITY_ID_VAL);
                map.put(ENTITY_TYPE, ENTITY_TYPE_VAL);
                map.put("eventCode", "Event Code");
                map.put("description", "Description");
                map.put("estimated", "Estimated");
                map.put("actual", "Actual");
                map.put("isPublicTrackingEvent", "Is Public Tracking Event");
                map.put("placeName", "Place Name");
                map.put("placeDescription", "Place Description");
                map.put("latitude", "Latitude");
                map.put("longitude", "Longitude");
                map.put("source", "Source");
                map.put("event_estimate_update_reasons", "Event Estimate Update Reasons");

                EventsFieldNameToDisplayNameMap = Collections.unmodifiableMap(map);
        }

        public static final Map<String, String> ReferenceNumbersFieldNameToDisplayNameMap;
        static {
                Map<String, String> map = new HashMap<>();
                map.put(CONSOLIDATION_ID, CONSOLIDATION_ID_VAL);
                map.put("countryOfIssue", "Country Of Issue");
                map.put("type", "Type");
                map.put("referenceNumber", REFERENCE_NUMBER_VAL);
                map.put(SHIPMENT_ID, SHIPMENT_ID_VALUE);
                map.put("isPortalEnable", "Is Portal Enable");

                ReferenceNumbersFieldNameToDisplayNameMap = Collections.unmodifiableMap(map);
        }

        public static final Map<String, String> PartiesFieldNameToDisplayNameMap;
        static {
                Map<String, String> map = new HashMap<>();
                map.put(ENTITY_ID, ENTITY_ID_VAL);
                map.put(ENTITY_TYPE, ENTITY_TYPE_VAL);
                map.put("type", "Type");
                map.put("orgCode", ORG_CODE_VAL);
                map.put("addressCode", ADDRESS_CODE_VAL);
                map.put("orgData", ORG_DATA_VAL);
                map.put("addressData", ADDRESS_DATA_VAL);
                map.put("isAddressFreeText", IS_ADDRESS_FREE_TEXT_VAL);

                PartiesFieldNameToDisplayNameMap = Collections.unmodifiableMap(map);
        }

        public static final Map<String, String> ServiceDetailsFieldNameToDisplayNameMap;
        static {
                Map<String, String> map = new HashMap<>();
                map.put(SHIPMENT_ID, SHIPMENT_ID_VALUE);
                map.put(CONSOLIDATION_ID, CONSOLIDATION_ID_VAL);
                map.put("serviceType", "Service Type");
                map.put("contractor", "Contractor");
                map.put("contractor.entityId", "Contractor: Entity Id");
                map.put("contractor.entityType", "Contractor: Entity Type");
                map.put("contractor.type", "Contractor: Type");
                map.put("contractor.orgCode", "Contractor: Org Code");
                map.put("contractor.addressCode", "Contractor: Address Code");
                map.put("contractor.orgData", "Contractor: Org Data");
                map.put("contractor.addressData", "Contractor: Address Data");
                map.put("contractor.isAddressFreeText", "Contractor: Is Address Free Text");
                map.put("srvLocation", "Service Location");
                map.put("bookingDate", "Booking Date");
                map.put("serviceCount", "Service Count");
                map.put("serviceDuration", "Service Duration");
                map.put("completionDate", "Completion Date");
                map.put("refNumber", REFERENCE_NUMBER_VAL);
                map.put("serviceNotes", "Service Notes");

                ServiceDetailsFieldNameToDisplayNameMap = Collections.unmodifiableMap(map);
        }

        public static final Map<String, String> TruckDriverDetailsFieldNameToDisplayName;
        static {
                Map<String, String> map = new HashMap<>();
                map.put(SHIPMENT_ID, SHIPMENT_ID_VALUE);
                map.put("transporterType", "Transporter Type");
                map.put("transporterName", "Transporter Name");
                map.put("driverName", "Driver Name");
                map.put("driverMobileNumber", "Driver Mobile Number");
                map.put("truckNumberPlate", "Truck Number Plate");
                map.put("trailerNumberPlate", "Trailer Number Plate");
                map.put("truckOrTrailerType", "Truck or Trailer Type");
                map.put("containerTypeCode", "Container Type Code");
                map.put("containerId", "Container Id");
                map.put(CONSOLIDATION_ID, CONSOLIDATION_ID_VAL);
                map.put("selfTransporterName", "Self Transporter Name");
                map.put("remarks", "Remarks");
                map.put("truckStatus", "Truck Status");

                TruckDriverDetailsFieldNameToDisplayName = Collections.unmodifiableMap(map);
        }
}
