package com.dpw.runner.shipment.services.commons.constants;

import java.util.HashMap;
import java.util.Map;

public class AuditLogConstants {

        private AuditLogConstants(){}
    public static final String AUDIT_LOG_API_HANDLE = "/api/v2/audit-log";

    public static final String AUDIT_LOG_LIST_SUCCESSFUL = "Successful Audit Log Data List Retrieval";

    public static final String AUDIT_LOG_DOWNLOAD_SUCCESSFUL = "Successful Audit Log Data Download";

        public static final String TRANSPORT_MODE = "transportMode";
        public static final String TRANSPORT_MODE_VALUE = "Transport Mode";
        public static final String SHIPMENT_ID_VALUE = "Shipment Id";
        public static final String SHIPMENT_ID = "shipmentId";
        public static final String IS_DOMESTIC = "isDomestic";
        public static final String IS_DOMESTIC_VALUE = "Is Domestic";
        public static final String CHARGEABLE_UNIT = "chargeableUnit";
        public static final String CHARGEABLE_UNIT_VAL = "Chargeable Unit";
        public static final String NET_WEIGHT_VAL = "Net Weight";
        public static final String NET_WEIGHT = "netWeight";
        public static final String NET_WEIGHT_UNIT_VAL = "Net Weight Unit";
        public static final String NET_WEIGHT_UNIT = "netWeightUnit";
        public static final String VOYAGE_VAL = "Voyage";
        public static final String OLD_VALUE = "oldValue";
        public static final String NEW_VALUE = "newValue";
        public static final Map<String, String> ShipmentsFieldNameToDisplayNameMap = new HashMap<String, String>() {{
                put("houseBill", "House Bill");
                put(TRANSPORT_MODE, TRANSPORT_MODE_VALUE);
                put("direction", "Direction");
                put("shipmentType", "Shipment Type");
                put("containersList", "Containers List");
                put("status", "Status");
                put("source", "Source");
                put("jobType", "Job Type");
                put("serviceType", "Service Type");
                put("masterBill", "Master Bill");
                put("bookingReference", "Booking Reference");
                put("consolRef", "Consol Ref");
                put("salesAgent", "Sales Agent");
                put("paymentTerms", "Payment Terms");
                put("incoterms", "Incoterms");
                put(SHIPMENT_ID, SHIPMENT_ID_VALUE);
                put(IS_DOMESTIC, IS_DOMESTIC_VALUE);
                put("assignedTo", "Assigned To");
                put("additionalTerms", "Additional Terms");
                put("goodsDescription", "Goods Description");
                put("bookingCarriagesList", "Booking Carriages List");
                put("elDetailsList", "El Details List");
                put("eventsList", "Events List");
                put("fileRepoList", "File Repo List");
                put("packingList", "Packing List");
                put("referenceNumbersList", "Reference Numbers List");
                put("routingsList", "Routings List");
                put("servicesList", "Services List");
                put("truckDriverDetails", "Truck Driver Details");
                put("weight", "Weight");
                put("weightUnit", "Weight Unit");
                put("volume", "Volume");
                put("volumeUnit", "Volume Unit");
                put("volumetricWeight", "Volumetric Weight");
                put("volumetricWeightUnit", "Volumetric Weight Unit");
                put("chargable", "Chargable");
                put(CHARGEABLE_UNIT, CHARGEABLE_UNIT_VAL);
                put(NET_WEIGHT, NET_WEIGHT_VAL);
                put(NET_WEIGHT_UNIT, NET_WEIGHT_UNIT_VAL);
                put("noOfPacks", "No Of Packs");
                put("packsUnit", "Packs Unit");
                put("innerPacks", "Inner Packs");
                put("innerPackUnit", "Inner Pack Unit");
                put("freightLocal", "Freight Local");
                put("freightLocalCurrency", "Freight Local Currency");
                put("freightOverseas", "Freight Overseas");
                put("freightOverseasCurrency", "Freight Overseas Currency");
                put("autoUpdateWtVol", "Auto Update Wt Vol");
                put("containerAutoWeightVolumeUpdate", "Container Auto Weight Volume Update");
                put("marksNum", "Marks Num");
                put("entryDetail", "Entry Detail");
                put("isLocked", "Is Locked");
                put("lockedBy", "Locked By");
                put("isNotifyConsigneeEqual", "Is Notify Consignee Equal");
                put("bookingType", "Booking Type");
                put("cargoFinanceBooking", "Cargo Finance Booking");
                put("bookingNumber", "Booking Number");
                put("route", "Route");
                put("sourceTenantId", "Source Tenant Id");
                put("documentationPartner", "Documentation Partner");
                put("triangulationPartnerList", "Triangulation Partner List");
            put("triangulationPartner", "Triangulation Partner");
                put("receivingBranch", "Receiving Branch");
                put("intraBranch", "Intra Branch");
                put("prevShipmentStatus", "Prev Shipment Status");
                put("isShipmentReadOnly", "Is Shipment Read Only");
                put("shipmentCreatedOn", "Shipment Created On");
                put("shipmentCompletedBy", "Shipment Completed By");
                put("shipmentCompletedOn", "Shipment Completed On");
                put("financeClosedBy", "Finance Closed By");
                put("financeClosedOn", "Finance Closed On");
                put("goodsValue", "Goods Value");
                put("goodsValueCurrency", "Goods Value Currency");
                put("insuranceValue", "Insurance Value");
                put("InsuranceValueCurrency", "Insurance Value Currency");
                put("jobsList", "Jobs List");
                put("consolidationList", "Consolidation List");
                put("shipmentAddresses", "Shipment Addresses");
                put("jobStatus", "JobStatus");
                put("entryRefNo", "Entry Ref No");
                put("flightStatus", "Flight Status");
                put("containsHazardous", "Contains Hazardous");
                put("fmcTlcId", "Fmc Tlc Id");
                put("commodity", "Commodity");
                put("orderNumber", "Order Number");
                put("orderManagementId", "Order Management Id");
                put("orderManagementNumber", "Order Management Number");
                put("customerCategory", "Customer Category");
                put("contractId", "Contract Id");
                put("contractType", "Contract Type");
                put("clientCountry", "Client Country");
                put("consignorCountry", "Consignor Country");
                put("consigneeCountry", "Consignee Country");
                put("notifyPartyCountry", "Notify Party Country");
                put("salesAgentEmail", "Sales Agent Email");
                put("salesBranch", "Sales Branch");
                put("sourceGuid", "Source Guid");
                put("consigneeDpsAddressId", "Consignee Dps Address Id");
                put("clientDpsAddressId", "Client Dps Address Id");
                put("consignorDpsAddressId", "Consignor Dps Address Id");
                put("notifyPartyDpsAddressId", "Notify Party Dps Address Id");

                put("additionalDetails", "Additional Details");
                put("additionalDetails.expiryDate", "Expiry Date");
                put("additionalDetails.inspection", "Inspection");
                put("additionalDetails.airwayBillDims", "Airway Bill Dims");
                put("additionalDetails.shipperCOD", "Shipper COD");
                put("additionalDetails.shipperCODPM", "Shipper CODPM");
                put("additionalDetails.phase", "Phase");
                put("additionalDetails.spotRate", "Spot Rate");
                put("additionalDetails.spotRateType", "Spot Rate Type");
                put("additionalDetails.efreightStatus", "Efreight Status");
                put("additionalDetails.importExportShipmentLock", "Import Export Shipment Lock");
                put("additionalDetails.CHAJobNumber", "CHA Job Number");
                put("additionalDetails.ADCode", "AD Code");
                put("additionalDetails.BEType", "BE Type");
                put("additionalDetails.customLocation", "Custom Location");
                put("additionalDetails.customCity", "Custom City");
                put("additionalDetails.isImportClearance", "Is Import Clearance");
                put("additionalDetails.isExportClearance", "Is Export Clearance");
                put("additionalDetails.IGMFileNo", "IGM File No");
                put("additionalDetails.IECode", "IE Code");
                put("additionalDetails.branchSINumber", "Branch SI Number");
                put("additionalDetails.andesStatus", "Andes Status");
                put("additionalDetails.andesResponseDate", "Andes Response Date");
                put("additionalDetails.andesStatusResponseText", "Andes Status Response Text");
                put("additionalDetails.tipoDocumentNotifyParty", "Tipo Document Notify Party");
                put("additionalDetails.tipoDocumentConsignee", "Tipo Document Consignee");
                put("additionalDetails.tipoDocumentConsignor", "Tipo Document Consignor");
                put("additionalDetails.andesTicket", "Andes Ticket");
                put("additionalDetails.warehouseId", "Warehouse Id");
                put("additionalDetails.activityType", "Activity Type");
                put("additionalDetails.hsnNumber", "Hsn Number");
                put("additionalDetails.IGMFileDate", "IGM File Date");
                put("additionalDetails.IGMInwardDate", "IGM Inward Date");
                put("additionalDetails.inwardDateAndTime", "Inward Date And Time");
                put("additionalDetails.lineNumber", "Line Number");
                put("additionalDetails.subLineNumber", "SubLine Number");
                put("additionalDetails.localLineNumber", "Local Line Number");
                put("additionalDetails.SMTPIGMNumber", "SMTPIGM Number");
                put("additionalDetails.SMTPIGMDate", "SMTPIGM Date");
                put("additionalDetails.isInland", "Is Inland");
                put("additionalDetails.ownership", "Ownership");
                put("additionalDetails.ownershipName", "Ownership Name");
                put("additionalDetails.passedBy", "Passed By");
                put("additionalDetails.passedByPerson", "Passed By Person");
                put("additionalDetails.lgdStatus", "Lgd Status");
                put("additionalDetails.isCmsHBLSent", "Is Cms HBL Sent");
                put("additionalDetails.isCreditOverrideApproved", "Is Credit Override Approved");
                put("additionalDetails.freeDays", "Free Days");
                put("additionalDetails.supplierInvoiceNumber", "Supplier Invoice Number");
                put("additionalDetails.supplierInvoiceDate", "Supplier Invoice Date");
                put("additionalDetails.invoiceValue", "Invoice Value");
                put("additionalDetails.assessValue", "Assess Value");
                put("additionalDetails.CIFValue", "CIF Value");
                put("additionalDetails.totalDuty", "Total Duty");
                put("additionalDetails.externalNotes", "External Notes");
                put("additionalDetails.bondedWarehouseId", "Bonded Warehouse Id");
                put("additionalDetails.releaseType", "Release Type");
                put("additionalDetails.houseBillType", "House Bill Type");
                put("additionalDetails.onBoard", "On Board");
                put("additionalDetails.onBoardDate", "On Board Date");
                put("additionalDetails.deliveryMode", "DeliveryMode");
                put("additionalDetails.original", "Original");
                put("additionalDetails.copy", "Copy");
                put("additionalDetails.BLChargesDisplay", "BL Charges Display");
                put("additionalDetails.BLExporterShipment", "BL Exporter Shipment");
                put("additionalDetails.screeningStatus", "Screening Status");
                put("additionalDetails.paidPlace", "Paid Place");
                put("additionalDetails.placeOfIssue", "Place Of Issue");
                put("additionalDetails.placeOfSupply", "Place Of Supply");
                put("additionalDetails.dateOfIssue", "Date Of Issue");
                put("additionalDetails.dateOfReceipt", "Date Of Receipt");
                put("additionalDetails.goodsCO", "Goods CO");
                put("additionalDetails.BOENumber", "BOE Number");
                put("additionalDetails.BOEDate", "BOE Date");
                put("additionalDetails.WBLPrinted", "WBL Printed");
                put("additionalDetails.draftPrinted", "Draft Printed");
                put("additionalDetails.shipmentId", SHIPMENT_ID_VALUE);
                put("additionalDetails.customDeclType", "Custom Decl Type");
                put("additionalDetails.agentReference", "Agent Reference");
                put("additionalDetails.bLTermsandConditionsId", "BL Terms And Conditions Id");
                put("additionalDetails.blComments", "Bl Comments");
                put("additionalDetails.cargoTerms", "Cargo Terms");
                put("additionalDetails.cargoTermsDescription", "Cargo Terms Description");
                put("additionalDetails.bLRemarks", "BL Remarks");
                put("additionalDetails.bLRemarksDescription", "BL Remarks Description");
                put("additionalDetails.summary", "Summary");
                put("additionalDetails.isSummaryUpdated", "Is Summary Updated");

                put("additionalDetails.ownershipOrg", "Ownership Org");
                put("additionalDetails.ownershipOrg.entityId", "Ownership Org: Entity Id");
                put("additionalDetails.ownershipOrg.entityType", "Ownership Org: Entity Type");
                put("additionalDetails.ownershipOrg.type", "Ownership Org: Type");
                put("additionalDetails.ownershipOrg.orgCode", "Ownership Org: Org Code");
                put("additionalDetails.ownershipOrg.addressCode", "Ownership Org: Address Code");
                put("additionalDetails.ownershipOrg.orgData", "Ownership Org: Org Data");
                put("additionalDetails.ownershipOrg.addressData", "Ownership Org: Address Data");
                put("additionalDetails.ownershipOrg.isAddressFreeText", "Ownership Org: Is Address Free Text");

                put("additionalDetails.notifyParty", "Notify Party");
                put("additionalDetails.notifyParty.entityId", "Notify Party: Entity Id");
                put("additionalDetails.notifyParty.entityType", "Notify Party: Entity Type");
                put("additionalDetails.notifyParty.type", "Notify Party: Type");
                put("additionalDetails.notifyParty.orgCode", "Notify Party: Org Code");
                put("additionalDetails.notifyParty.addressCode", "Notify Party: Address Code");
                put("additionalDetails.notifyParty.orgData", "Notify Party: Org Data");
                put("additionalDetails.notifyParty.addressData", "Notify Party: Address Data");
                put("additionalDetails.notifyParty.isAddressFreeText", "Notify Party: Is Address Free Text");

                put("additionalDetails.importBroker", "Import Broker");
                put("additionalDetails.importBroker.entityId", "Import Broker: Entity Id");
                put("additionalDetails.importBroker.entityType", "Import Broker: Entity Type");
                put("additionalDetails.importBroker.type", "Import Broker: Type");
                put("additionalDetails.importBroker.orgCode", "Import Broker: Org Code");
                put("additionalDetails.importBroker.addressCode", "Import Broker: Address Code");
                put("additionalDetails.importBroker.orgData", "Import Broker: Org Data");
                put("additionalDetails.importBroker.addressData", "Import Broker: Address Data");
                put("additionalDetails.importBroker.isAddressFreeText", "Import Broker: Is Address Free Text");

                put("additionalDetails.exportBroker", "Export Broker");
                put("additionalDetails.exportBroker.entityId", "Export Broker: Entity Id");
                put("additionalDetails.exportBroker.entityType", "Export Broker: Entity Type");
                put("additionalDetails.exportBroker.type", "Export Broker: Type");
                put("additionalDetails.exportBroker.orgCode", "Export Broker: Org Code");
                put("additionalDetails.exportBroker.addressCode", "Export Broker: Address Code");
                put("additionalDetails.exportBroker.orgData", "Export Broker: Org Data");
                put("additionalDetails.exportBroker.addressData", "Export Broker: Address Data");
                put("additionalDetails.exportBroker.isAddressFreeText", "Export Broker: Is Address Free Text");

                put("additionalDetails.sendingForwarder", "Sending Forwarder");
                put("additionalDetails.sendingForwarder.entityId", "Sending Forwarder: Entity Id");
                put("additionalDetails.sendingForwarder.entityType", "Sending Forwarder: Entity Type");
                put("additionalDetails.sendingForwarder.type", "Sending Forwarder: Type");
                put("additionalDetails.sendingForwarder.orgCode", "Sending Forwarder: Org Code");
                put("additionalDetails.sendingForwarder.addressCode", "Sending Forwarder: Address Code");
                put("additionalDetails.sendingForwarder.orgData", "Sending Forwarder: Org Data");
                put("additionalDetails.sendingForwarder.addressData", "Sending Forwarder: Address Data");
                put("additionalDetails.sendingForwarder.isAddressFreeText", "Sending Forwarder: Is Address Free Text");

                put("additionalDetails.receivingForwarder", "Receiving Forwarder");
                put("additionalDetails.receivingForwarder.entityId", "Receiving Forwarder: Entity Id");
                put("additionalDetails.receivingForwarder.entityType", "Receiving Forwarder: Entity Type");
                put("additionalDetails.receivingForwarder.type", "Receiving Forwarder: Type");
                put("additionalDetails.receivingForwarder.orgCode", "Receiving Forwarder: Org Code");
                put("additionalDetails.receivingForwarder.addressCode", "Receiving Forwarder: Address Code");
                put("additionalDetails.receivingForwarder.orgData", "Receiving Forwarder: Org Data");
                put("additionalDetails.receivingForwarder.addressData", "Receiving Forwarder: Address Data");
                put("additionalDetails.receivingForwarder.isAddressFreeText", "Receiving Forwarder: Is Address Free Text");

                put("additionalDetails.traderOrSupplier", "Trader Or Supplier");
                put("additionalDetails.traderOrSupplier.entityId", "Trader Or Supplier: Entity Id");
                put("additionalDetails.traderOrSupplier.entityType", "Trader Or Supplier: Entity Type");
                put("additionalDetails.traderOrSupplier.type", "Trader Or Supplier: Type");
                put("additionalDetails.traderOrSupplier.orgCode", "Trader Or Supplier: Org Code");
                put("additionalDetails.traderOrSupplier.addressCode", "Trader Or Supplier: Address Code");
                put("additionalDetails.traderOrSupplier.orgData", "Trader Or Supplier: Org Data");
                put("additionalDetails.traderOrSupplier.addressData", "Trader Or Supplier: Address Data");
                put("additionalDetails.traderOrSupplier.isAddressFreeText", "Trader Or Supplier: Is Address Free Text");

                put("additionalDetails.eTailor", "eTailor");
                put("additionalDetails.eTailor.entityId", "eTailor: Entity Id");
                put("additionalDetails.eTailor.entityType", "eTailor: Entity Type");
                put("additionalDetails.eTailor.type", "eTailor: Type");
                put("additionalDetails.eTailor.orgCode", "eTailor: Org Code");
                put("additionalDetails.eTailor.addressCode", "eTailor: Address Code");
                put("additionalDetails.eTailor.orgData", "eTailor: Org Data");
                put("additionalDetails.eTailor.addressData", "eTailor: Address Data");
                put("additionalDetails.eTailor.isAddressFreeText", "eTailor: Is Address Free Text");

                put("additionalDetails.borrowedFrom", "Borrowed From");
                put("additionalDetails.borrowedFrom.entityId", "Borrowed From: Entity Id");
                put("additionalDetails.borrowedFrom.entityType", "Borrowed From: Entity Type");
                put("additionalDetails.borrowedFrom.type", "Borrowed From: Type");
                put("additionalDetails.borrowedFrom.orgCode", "Borrowed From: Org Code");
                put("additionalDetails.borrowedFrom.addressCode", "Borrowed From: Address Code");
                put("additionalDetails.borrowedFrom.orgData", "Borrowed From: Org Data");
                put("additionalDetails.borrowedFrom.addressData", "Borrowed From: Address Data");
                put("additionalDetails.borrowedFrom.isAddressFreeText", "Borrowed From: Is Address Free Text");

                put("additionalDetails.sendingAgent", "Sending Agent");
                put("additionalDetails.sendingAgent.entityId", "Sending Agent: Entity Id");
                put("additionalDetails.sendingAgent.entityType", "Sending Agent: Entity Type");
                put("additionalDetails.sendingAgent.type", "Sending Agent: Type");
                put("additionalDetails.sendingAgent.orgCode", "Sending Agent: Org Code");
                put("additionalDetails.sendingAgent.addressCode", "Sending Agent: Address Code");
                put("additionalDetails.sendingAgent.orgData", "Sending Agent: Org Data");
                put("additionalDetails.sendingAgent.addressData", "Sending Agent: Address Data");
                put("additionalDetails.sendingAgent.isAddressFreeText", "Sending Agent: Is Address Free Text");

                put("additionalDetails.receivingAgent", "Receiving Agent");
                put("additionalDetails.receivingAgent.entityId", "Receiving Agent: Entity Id");
                put("additionalDetails.receivingAgent.entityType", "Receiving Agent: Entity Type");
                put("additionalDetails.receivingAgent.type", "Receiving Agent: Type");
                put("additionalDetails.receivingAgent.orgCode", "Receiving Agent: Org Code");
                put("additionalDetails.receivingAgent.addressCode", "Receiving Agent: Address Code");
                put("additionalDetails.receivingAgent.orgData", "Receiving Agent: Org Data");
                put("additionalDetails.receivingAgent.addressData", "Receiving Agent: Address Data");
                put("additionalDetails.receivingAgent.isAddressFreeText", "Receiving Agent: Is Address Free Text");

                put("carrierDetails", "Carrier Details");
                put("carrierDetails.shippingLine", "Shipping Line");
                put("carrierDetails.vessel", "Vessel");
                put("carrierDetails.voyage", VOYAGE_VAL);
                put("carrierDetails.flightNumber", "Flight Number");
                put("carrierDetails.aircraftType", "Aircraft Type");
                put("carrierDetails.aircraftRegistration", "Aircraft Registration");
                put("carrierDetails.truckRefNumber", "Truck Ref Number");
                put("carrierDetails.journeyNumber", "Journey Number");
                put("carrierDetails.journeyRefNumber", "Journey Ref Number");
                put("carrierDetails.origin", "Origin");
                put("carrierDetails.destination", "Destination");
                put("carrierDetails.originPort", "Origin Port");
                put("carrierDetails.destinationPort", "Destination Port");
                put("carrierDetails.eta", "Eta");
                put("carrierDetails.etd", "Etd");
                put("carrierDetails.ata", "Ata");
                put("carrierDetails.atd", "Atd");
                put("carrierDetails.vesselBerthingDate", "Vessel Berthing Date");
                put("carrierDetails.voyageOrFlightNumber", "Voyage Or Flight Number");

                put("deliveryDetails", "Delivery Details");
                put("deliveryDetails.estimatedPickupOrDelivery", "Delivery Details: Estimated Pickup Or Delivery");
                put("deliveryDetails.estimatedPickup", "Delivery Details: Estimated Pickup");
                put("deliveryDetails.estimatedDelivery", "Delivery Details: Estimated Delivery");
                put("deliveryDetails.requiredBy", "Delivery Details: Required By");
                put("deliveryDetails.portTransportAdvised", "Delivery Details: Port Transport Advised");
                put("deliveryDetails.actualPickupOrDelivery", "Delivery Details: Actual Pickup Or Delivery");
                put("deliveryDetails.actualPickup", "Delivery Details: Actual Pickup ");
                put("deliveryDetails.actualDelivery", "Delivery Details: Actual Delivery ");
                put("deliveryDetails.pickupOrDelivery", "Delivery Details: Pickup Or Delivery");
                put("deliveryDetails.type", "Delivery Details: Type");
                put("deliveryDetails.shipmentId", "Delivery Details: Shipment Id");
                put("deliveryDetails.dropMode", "Delivery Details: Drop Mode");
                put("deliveryDetails.labourCharge", "Delivery Details: Labour Charge");
                put("deliveryDetails.labourChargeUnit", "Delivery Details: Labour Charge Unit");
                put("deliveryDetails.labourDuration", "Delivery Details: Labour Duration");
                put("deliveryDetails.shipperRef", "Delivery Details: Shipper Ref");
                put("deliveryDetails.interimReceipt", "Delivery Details: Interim Receipt");
                put("deliveryDetails.fclAvailableDate", "Delivery Details: Fcl Available Date");
                put("deliveryDetails.truckWaitTimeCharge", "Delivery Details: Truck Wait Time Charge");
                put("deliveryDetails.truckWaitTimeChargeUnit", "Delivery Details: Truck Wait Time Charge Unit");
                put("deliveryDetails.truckWaitDuration", "Delivery Details: Truck Wait Duration");
                put("deliveryDetails.storageChargeUnit", "Delivery Details: Storage Charge Unit");
                put("deliveryDetails.storageChargeDuration", "Delivery Details: Storage Charge Duration");
                put("deliveryDetails.ucrReference", "Delivery Details: Ucr Reference");
                put("deliveryDetails.emptyTruckInDate", "Delivery Details: Empty Truck In Date");
                put("deliveryDetails.loadedTruckGateOutDate", "Delivery Details: Loaded Truck Gate Out Date");
                put("deliveryDetails.pickupDeliveryInstruction", "Delivery Details: Pickup Delivery Instruction");
                put("deliveryDetails.pickupGateIn", "Delivery Details : Pickup Gate In");
                put("deliveryDetails.deliveryGateIn", "Delivery Details : Delivery Gate In");
                put("deliveryDetails.pickupGateOut", "Delivery Details : Pickup Gate Out");
                put("deliveryDetails.deliveryGateOut", "Delivery Details : Delivery Gate Out");

                put("deliveryDetails.transporterDetail", "Delivery Details: Transporter Detail");
                put("deliveryDetails.transporterDetail.entityId", "Delivery Details: Transporter Detail: Entity Id");
                put("deliveryDetails.transporterDetail.entityType", "Delivery Details: Transporter Detail: Entity Type");
                put("deliveryDetails.transporterDetail.type", "Delivery Details: Transporter Detail: Type");
                put("deliveryDetails.transporterDetail.orgCode", "Delivery Details: Transporter Detail: Org Code");
                put("deliveryDetails.transporterDetail.addressCode", "Delivery Details: Transporter Detail: Address Code");
                put("deliveryDetails.transporterDetail.orgData", "Delivery Details: Transporter Detail: Org Data");
                put("deliveryDetails.transporterDetail.addressData", "Delivery Details: Transporter Detail: Address Data");
                put("deliveryDetails.transporterDetail.isAddressFreeText", "Delivery Details: Transporter Detail: Is Address Free Text");

                put("deliveryDetails.brokerDetail", "Delivery Details: Broker Detail");
                put("deliveryDetails.brokerDetail.entityId", "Delivery Details: Broker Detail: Entity Id");
                put("deliveryDetails.brokerDetail.entityType", "Delivery Details: Broker Detail: Entity Type");
                put("deliveryDetails.brokerDetail.type", "Delivery Details: Broker Detail: Type");
                put("deliveryDetails.brokerDetail.orgCode", "Delivery Details: Broker Detail: Org Code");
                put("deliveryDetails.brokerDetail.addressCode", "Delivery Details: Broker Detail: Address Code");
                put("deliveryDetails.brokerDetail.orgData", "Delivery Details: Broker Detail: Org Data");
                put("deliveryDetails.brokerDetail.addressData", "Delivery Details: Broker Detail: Address Data");
                put("deliveryDetails.brokerDetail.isAddressFreeText", "Delivery Details: Broker Detail: Is Address Free Text");

                put("deliveryDetails.destinationDetail", "Delivery Details: Destination Detail");
                put("deliveryDetails.destinationDetail.entityId", "Delivery Details: Destination Detail: Entity Id");
                put("deliveryDetails.destinationDetail.entityType", "Delivery Details: Destination Detail: Entity Type");
                put("deliveryDetails.destinationDetail.type", "Delivery Details: Destination Detail: Type");
                put("deliveryDetails.destinationDetail.orgCode", "Delivery Details: Destination Detail: Org Code");
                put("deliveryDetails.destinationDetail.addressCode", "Delivery Details: Destination Detail: Address Code");
                put("deliveryDetails.destinationDetail.orgData", "Delivery Details: Destination Detail: Org Data");
                put("deliveryDetails.destinationDetail.addressData", "Delivery Details: Destination Detail: Address Data");
                put("deliveryDetails.destinationDetail.isAddressFreeText", "Delivery Details: Destination Detail: Is Address Free Text");

                put("deliveryDetails.sourceDetail", "Delivery Details: Source Detail");
                put("deliveryDetails.sourceDetail.entityId", "Delivery Details: Source Detail: Entity Id");
                put("deliveryDetails.sourceDetail.entityType", "Delivery Details: Source Detail: Entity Type");
                put("deliveryDetails.sourceDetail.type", "Delivery Details: Source Detail: Type");
                put("deliveryDetails.sourceDetail.orgCode", "Delivery Details: Source Detail: Org Code");
                put("deliveryDetails.sourceDetail.addressCode", "Delivery Details: Source Detail: Address Code");
                put("deliveryDetails.sourceDetail.orgData", "Delivery Details: Source Detail: Org Data");
                put("deliveryDetails.sourceDetail.addressData", "Delivery Details: Source Detail: Address Data");
                put("deliveryDetails.sourceDetail.isAddressFreeText", "Delivery Details: Source Detail: Is Address Free Text");

                put("deliveryDetails.agentDetail", "Delivery Details: Agent Detail");
                put("deliveryDetails.agentDetail.entityId", "Delivery Details: Agent Detail: Entity Id");
                put("deliveryDetails.agentDetail.entityType", "Delivery Details: Agent Detail: Entity Type");
                put("deliveryDetails.agentDetail.type", "Delivery Details: Agent Detail: Type");
                put("deliveryDetails.agentDetail.orgCode", "Delivery Details: Agent Detail: Org Code");
                put("deliveryDetails.agentDetail.addressCode", "Delivery Details: Agent Detail: Address Code");
                put("deliveryDetails.agentDetail.orgData", "Delivery Details: Agent Detail: Org Data");
                put("deliveryDetails.agentDetail.addressData", "Delivery Details: Agent Detail: Address Data");
                put("deliveryDetails.agentDetail.isAddressFreeText", "Delivery Details: Agent Detail: Is Address Free Text");


                put("pickupDetails", "Pickup Details");
                put("pickupDetails.estimatedPickupOrDelivery", "Pickup Details: Estimated Pickup Or Delivery");
                put("pickupDetails.requiredBy", "Pickup Details: Required By");
                put("pickupDetails.portTransportAdvised", "Pickup Details: Port Transport Advised");
                put("pickupDetails.actualPickupOrDelivery", "Pickup Details: Actual Pickup Or Delivery");
                put("pickupDetails.pickupOrDelivery", "Pickup Details: Pickup Or Delivery");
                put("pickupDetails.type", "Pickup Details: Type");
                put("pickupDetails.shipmentId", "Pickup Details: Shipment Id");
                put("pickupDetails.dropMode", "Pickup Details: Drop Mode");
                put("pickupDetails.labourCharge", "Pickup Details: Labour Charge");
                put("pickupDetails.labourChargeUnit", "Pickup Details: Labour Charge Unit");
                put("pickupDetails.labourDuration", "Pickup Details: Labour Duration");
                put("pickupDetails.shipperRef", "Pickup Details: Shipper Ref");
                put("pickupDetails.interimReceipt", "Pickup Details: Interim Receipt");
                put("pickupDetails.fclAvailableDate", "Pickup Details: Fcl Available Date");
                put("pickupDetails.truckWaitTimeCharge", "Pickup Details: Truck Wait Time Charge");
                put("pickupDetails.truckWaitTimeChargeUnit", "Pickup Details: Truck Wait Time Charge Unit");
                put("pickupDetails.truckWaitDuration", "Pickup Details: Truck Wait Duration");
                put("pickupDetails.storageChargeUnit", "Pickup Details: Storage Charge Unit");
                put("pickupDetails.storageChargeDuration", "Pickup Details: Storage Charge Duration");
                put("pickupDetails.ucrReference", "Pickup Details: Ucr Reference");
                put("pickupDetails.emptyTruckInDate", "Pickup Details: Empty Truck In Date");
                put("pickupDetails.loadedTruckGateOutDate", "Pickup Details: Loaded Truck Gate Out Date");
                put("pickupDetails.pickupDeliveryInstruction", "Pickup Details: Pickup Delivery Instruction");

                put("pickupDetails.pickupGateIn", "Pickup Details : Pickup Gate In");
                put("pickupDetails.deliveryGateIn", "Pickup Details : Delivery Gate In");
                put("pickupDetails.pickupGateOut", "Pickup Details : Pickup Gate Out");
                put("pickupDetails.deliveryGateOut", "Pickup Details : Delivery Gate Out");
                put("pickupDetails.estimatedPickup", "Pickup Details: Estimated Pickup");
                put("pickupDetails.estimatedDelivery", "Pickup Details: Estimated Delivery");
                put("pickupDetails.actualPickup", "Pickup Details: Actual Pickup ");
                put("pickupDetails.actualDelivery", "Pickup Details: Actual Delivery ");

                put("pickupDetails.transporterDetail", "Pickup Details: Transporter Detail");
                put("pickupDetails.transporterDetail.entityId", "Pickup Details: Transporter Detail: Entity Id");
                put("pickupDetails.transporterDetail.entityType", "Pickup Details: Transporter Detail: Entity Type");
                put("pickupDetails.transporterDetail.type", "Pickup Details: Transporter Detail: Type");
                put("pickupDetails.transporterDetail.orgCode", "Pickup Details: Transporter Detail: Org Code");
                put("pickupDetails.transporterDetail.addressCode", "Pickup Details: Transporter Detail: Address Code");
                put("pickupDetails.transporterDetail.orgData", "Pickup Details: Transporter Detail: Org Data");
                put("pickupDetails.transporterDetail.addressData", "Pickup Details: Transporter Detail: Address Data");
                put("pickupDetails.transporterDetail.isAddressFreeText", "Pickup Details: Transporter Detail: Is Address Free Text");

                put("pickupDetails.brokerDetail", "Pickup Details: Broker Detail");
                put("pickupDetails.brokerDetail.entityId", "Pickup Details: Broker Detail: Entity Id");
                put("pickupDetails.brokerDetail.entityType", "Pickup Details: Broker Detail: Entity Type");
                put("pickupDetails.brokerDetail.type", "Pickup Details: Broker Detail: Type");
                put("pickupDetails.brokerDetail.orgCode", "Pickup Details: Broker Detail: Org Code");
                put("pickupDetails.brokerDetail.addressCode", "Pickup Details: Broker Detail: Address Code");
                put("pickupDetails.brokerDetail.orgData", "Pickup Details: Broker Detail: Org Data");
                put("pickupDetails.brokerDetail.addressData", "Pickup Details: Broker Detail: Address Data");
                put("pickupDetails.brokerDetail.isAddressFreeText", "Pickup Details: Broker Detail: Is Address Free Text");

                put("pickupDetails.destinationDetail", "Pickup Details: Destination Detail");
                put("pickupDetails.destinationDetail.entityId", "Pickup Details: Destination Detail: Entity Id");
                put("pickupDetails.destinationDetail.entityType", "Pickup Details: Destination Detail: Entity Type");
                put("pickupDetails.destinationDetail.type", "Pickup Details: Destination Detail: Type");
                put("pickupDetails.destinationDetail.orgCode", "Pickup Details: Destination Detail: Org Code");
                put("pickupDetails.destinationDetail.addressCode", "Pickup Details: Destination Detail: Address Code");
                put("pickupDetails.destinationDetail.orgData", "Pickup Details: Destination Detail: Org Data");
                put("pickupDetails.destinationDetail.addressData", "Pickup Details: Destination Detail: Address Data");
                put("pickupDetails.destinationDetail.isAddressFreeText", "Pickup Details: Destination Detail: Is Address Free Text");

                put("pickupDetails.sourceDetail", "Pickup Details: Source Detail");
                put("pickupDetails.sourceDetail.entityId", "Pickup Details: Source Detail: Entity Id");
                put("pickupDetails.sourceDetail.entityType", "Pickup Details: Source Detail: Entity Type");
                put("pickupDetails.sourceDetail.type", "Pickup Details: Source Detail: Type");
                put("pickupDetails.sourceDetail.orgCode", "Pickup Details: Source Detail: Org Code");
                put("pickupDetails.sourceDetail.addressCode", "Pickup Details: Source Detail: Address Code");
                put("pickupDetails.sourceDetail.orgData", "Pickup Details: Source Detail: Org Data");
                put("pickupDetails.sourceDetail.addressData", "Pickup Details: Source Detail: Address Data");
                put("pickupDetails.sourceDetail.isAddressFreeText", "Pickup Details: Source Detail: Is Address Free Text");

                put("pickupDetails.agentDetail", "Pickup Details: Agent Detail");
                put("pickupDetails.agentDetail.entityId", "Pickup Details: Agent Detail: Entity Id");
                put("pickupDetails.agentDetail.entityType", "Pickup Details: Agent Detail: Entity Type");
                put("pickupDetails.agentDetail.type", "Pickup Details: Agent Detail: Type");
                put("pickupDetails.agentDetail.orgCode", "Pickup Details: Agent Detail: Org Code");
                put("pickupDetails.agentDetail.addressCode", "Pickup Details: Agent Detail: Address Code");
                put("pickupDetails.agentDetail.orgData", "Pickup Details: Agent Detail: Org Data");
                put("pickupDetails.agentDetail.addressData", "Pickup Details: Agent Detail: Address Data");
                put("pickupDetails.agentDetail.isAddressFreeText", "Pickup Details: Agent Detail: Is Address Free Text");


                put("client", "Client");
                put("client.entityId", "Client: Entity Id");
                put("client.entityType", "Client: Entity Type");
                put("client.type", "Client: Type");
                put("client.orgCode", "Client: Org Code");
                put("client.addressCode", "Client: Address Code");
                put("client.orgData", "Client: Org Data");
                put("client.addressData", "Client: Address Data");
                put("client.isAddressFreeText", "Client: Is Address Free Text");

                put("consigner", "Consigner");
                put("consigner.entityId", "Consigner: Entity Id");
                put("consigner.entityType", "Consigner: Entity Type");
                put("consigner.type", "Consigner: Type");
                put("consigner.orgCode", "Consigner: Org Code");
                put("consigner.addressCode", "Consigner: Address Code");
                put("consigner.orgData", "Consigner: Org Data");
                put("consigner.addressData", "Consigner: Address Data");
                put("consigner.isAddressFreeText", "Consigner: Is Address Free Text");

                put("consignee", "Consignee");
                put("consignee.entityId", "Consignee: Entity Id");
                put("consignee.entityType", "Consignee: Entity Type");
                put("consignee.type", "Consignee: Type");
                put("consignee.orgCode", "Consignee: Org Code");
                put("consignee.addressCode", "Consignee: Address Code");
                put("consignee.orgData", "Consignee: Org Data");
                put("consignee.addressData", "Consignee: Address Data");
                put("consignee.isAddressFreeText", "Consignee: Is Address Free Text");

        }};

        public static final String CONSOLIDATION_ID = "consolidationId";
        public static final String CONSOLIDATION_ID_VAL = "Consolidation Id";
        public static final String BOOKING_ID_VAL = "Booking Id";
        public static final String BOOKING_ID = "bookingId";
        public static final String ENTITY_ID_VAL = "Entity Id";
        public static final String ENTITY_TYPE_VAL = "Entity Type";
        public static final String ORG_CODE_VAL = "Org Code";
        public static final String ADDRESS_CODE_VAL = "Address Code";
        public static final String ORG_DATA_VAL = "Org Data";
        public static final String ADDRESS_DATA_VAL = "Address Data";
        public static final String IS_ADDRESS_FREE_TEXT_VAL = "Is Address Free Text";
        public static final String CONTAINER_CODE = "containerCode";
        public static final Map<String, String> ContainerFieldNameToDisplayNameMap = new HashMap<String, String>() {{
                put(CONSOLIDATION_ID, CONSOLIDATION_ID_VAL);
                put(BOOKING_ID, BOOKING_ID_VAL);
                put("loggingId", "Logging Id");
                put(CONTAINER_CODE, "Container Code");
                put("sealNumber", "Seal Number");
                put("descriptionOfGoods", "Description Of Goods");
                put(NET_WEIGHT, NET_WEIGHT_VAL);
                put(NET_WEIGHT_UNIT, NET_WEIGHT_UNIT_VAL);
                put("grossWeight", "Gross Weight");
                put("grossWeightUnit", "Gross Weight Unit");
                put("measurement", "Measurement");
                put("measurementUnit", "Measurement Unit");
                put("commodityCode", "Commodity Code");
                put("hsCode", "Hs Code");
                put("isShipperOwned", "Is Shipper Owned");
                put("isEmpty", "Is Empty");
                put("containerCount", "Container Count");
                put("carrierSealNumber", "Carrier Seal Number");
                put("shipperSealNumber", "Shipper Seal Number");
                put("terminalOperatorSealNumber", "Terminal Operator Seal Number");
                put("veterinarySealNumber", "Veterinary Seal Number");
                put("customsSealNumber", "Customs Seal Number");
                put("customsReleaseCode", "Customs Release Code");
                put("containerStuffingLocation", "Container Stuffing Location");
                put("containerComments", "Container Comments");
                put("grossVolume", "Gross Volume");
                put("grossVolumeUnit", "Gross Volume Unit");
                put("isReefer", "Is Reefer");
                put("minTemp", "Min Temp");
                put("minTempUnit", "Min Temp Unit");
                put("maxTemp", "Max Temp");
                put("maxTempUnit", "Max Temp Unit");
                put("hblDeliveryMode", "Hbl Delivery Mode");
                put("allocationDate", "Allocation Date");
                put("dgClass", "Dg Class");
                put("hazardous", "Hazardous");
                put("hazardousUn", "Hazardous Un");
                put("tareWeight", "Tare Weight");
                put("tareWeightUnit", "Tare Weight Unit");
                put("serialNumber", "Serial Number");
                put("innerPackageNumber", "Inner Package Number");
                put("innerPackageType", "Inner Package Type");
                put("packageLength", "Package Length");
                put("packageBreadth", "Package Breadth");
                put("packageHeight", "Package Height");
                put("isTemperatureMaintained", "Is Temperature Maintained");
                put("packs", "Packs");
                put("packsType", "Packs Type");
                put("marksNums", "MarksNums");
                put("innerPackageMeasurementUnit", "Inner Package Measurement Unit");
                put("pacrNumber", "Pacr Number");
                put("chargeable", "Chargeable");
                put(CHARGEABLE_UNIT, CHARGEABLE_UNIT_VAL);
                put("isOwnContainer", "Is Own Container");
                put(TRANSPORT_MODE, TRANSPORT_MODE_VALUE);
                put("status", "Status");
                put("extraParams", "Extra Params");
                put("remarks", "Remarks");
                put("allocatedWeight", "Allocated Weight");
                put("allocatedWeightUnit", "Allocated Weight Unit");
                put("allocatedVolume", "Allocated Volume");
                put("allocatedVolumeUnit", "Allocated Volume Unit");
                put("achievedWeight", "Achieved Weight");
                put("achievedWeightUnit", "Achieved Weight Unit");
                put("achievedVolume", "Achieved Volume");
                put("achievedVolumeUnit", "Achieved Volume Unit");
                put("weightUtilization", "Weight Utilization");
                put("volumeUtilization", "Volume Utilization");

                put("commodityGroup", "Commodity Group");
                put("isContractEnforced", "Is Contract Enforced");
                put("contractEnforcedQuantityLimit", "Contract Enforced Quantity Limit");
                put("ownType", "Own Type");
                put("handlingInfo", "Handling Info");
                put("isPart", "Is Part");
                put("isAttached", "Is Attached");

                put("pickupAddress", "Pickup Address");
                put("pickupAddress.entityId", ENTITY_ID_VAL);
                put("pickupAddress.entityType", ENTITY_TYPE_VAL);
                put("pickupAddress.type", "Type");
                put("pickupAddress.orgCode", ORG_CODE_VAL);
                put("pickupAddress.addressCode", ADDRESS_CODE_VAL);
                put("pickupAddress.orgData", ORG_DATA_VAL);
                put("pickupAddress.addressData", ADDRESS_DATA_VAL);
                put("pickupAddress.isAddressFreeText", IS_ADDRESS_FREE_TEXT_VAL);

                put("deliveryAddress", "Delivery Address");
                put("deliveryAddress.entityId", ENTITY_ID_VAL);
                put("deliveryAddress.entityType", ENTITY_TYPE_VAL);
                put("deliveryAddress.type", "Type");
                put("deliveryAddress.orgCode", ORG_CODE_VAL);
                put("deliveryAddress.addressCode", ADDRESS_CODE_VAL);
                put("deliveryAddress.orgData", ORG_DATA_VAL);
                put("deliveryAddress.addressData", ADDRESS_DATA_VAL);
                put("deliveryAddress.isAddressFreeText", IS_ADDRESS_FREE_TEXT_VAL);
        }};

        public static final String REFERENCE_NUMBER_VAL = "Reference Number";
        public static final Map<String, String> PackingFieldNameToDisplayNameMap = new HashMap<String, String>() {{
                put(CONSOLIDATION_ID, CONSOLIDATION_ID_VAL);
                put(SHIPMENT_ID, SHIPMENT_ID_VALUE);
                put(BOOKING_ID, BOOKING_ID_VAL);
                put("DGGoodsId", "DG Goods Id");
                put("DGSubstanceId", "DG Substance Id");
                put("packs", "Packs");
                put("packsType", "Packs Type");
                put("weight", "Weight");
                put("weightUnit", "Weight Unit");
                put("volume", "Volume");
                put("volumeUnit", "Volume Unit");
                put("inspections", "Inspections");
                put("origin", "Origin");
                put("commodity", "Commodity");
                put("packingOrder", "Packing Order");
                put("length", "Length");
                put("lengthUnit", "Length Unit");
                put("width", "Width");
                put("widthUnit", "Width Unit");
                put("height", "Height");
                put("heightUnit", "Height Unit");
                put("marksnNums", "MarksnNums");
                put("flashPoint", "Flash Point");
                put("UNDGContact", "UNDG Contact");
                put("isTemperatureControlled", "Is Temperature Controlled");
                put("minTemp", "Min Temp");
                put("minTempUnit", "Min Temp Unit");
                put("maxTemp", "Max Temp");
                put("maxTempUnit", "Max Temp Unit");
                put("HSCode", "HS Code");
                put("countryCode", "Country Code");
                put("goodsDescription", "Goods Description");
                put("referenceNumber", REFERENCE_NUMBER_VAL);
                put("DGClass", "DG Class");
                put("hazardous", "Hazardous");
                put("commodityId", "Commodity Id");
                put(NET_WEIGHT, NET_WEIGHT_VAL);
                put(NET_WEIGHT_UNIT, NET_WEIGHT_UNIT_VAL);
                put("volumeWeight", "Volume Weight");
                put("volumeWeightUnit", "Volume Weight Unit");
                put("vinNumber", "Vin Number");
                put("containerId", "Container Id");
                put(TRANSPORT_MODE, TRANSPORT_MODE_VALUE);
                put("innerPackageNumber", "Inner Package Number");
                put("innerPackageType", "Inner Package Type");
                put(CHARGEABLE_UNIT, CHARGEABLE_UNIT_VAL);
                put("customsReleaseCode", "Customs Release Code");
                put("shipmentNumber", "Shipment Number");
                put("innerPacksId", "Inner Packs Id");
                put("innerPacksCount", "Inner Packs Count");
                put("commodityGroup", "Commodity Group");
                put("isDimension", "Is Dimension");
                put("isContractEnforced", "Is Contract Enforced");
                put("handlingInfo", "Handling Info");
                put("contractEnforcedQuantityLimit", "Contract Enforced Quantity Limit");
        }};

        public static final Map<String, String> RoutingsFieldNameToDisplayNameMap = new HashMap<String, String>() {{
                put(BOOKING_ID, BOOKING_ID_VAL);
                put(SHIPMENT_ID, SHIPMENT_ID_VALUE);
                put("leg", "Leg");
                put("mode", "Mode");
                put("routingStatus", "Routing Status");
                put("vesselName", "Vessel Name");
                put("pol", "Pol");
                put("pod", "Pod");
                put(IS_DOMESTIC, IS_DOMESTIC_VALUE);
                put("eta", "Eta");
                put("etd", "Etd");
                put("ata", "Ata");
                put("atd", "Atd");
                put(CONSOLIDATION_ID, CONSOLIDATION_ID_VAL);
                put("isLinked", "Is Linked");
                put("voyage", VOYAGE_VAL);
                put("aircraftRegistration", "Aircraft Registration");
                put("flightNumber", "Flight Number");
                put("aircraftType", "Aircraft Type");
                put("routeLegId", "Route Leg Id");
                put("vesselId", "Vessel Id");
                put("transitDays", "Transit Days");
                put("carrier", "Carrier");
                put("truckReferenceNumber", "Truck Reference Number");

        }};
        public static final String ENTITY_ID = "entityId";
        public static final String ENTITY_TYPE = "entityType";
        public static final Map<String, String> NotesFieldNameToDisplayNameMap = new HashMap<String, String>() {{
                put("text", "Text");
                put("label", "Label");
                put("assignedTo", "Asigned To");
                put(ENTITY_ID, ENTITY_ID_VAL);
                put(ENTITY_TYPE, ENTITY_TYPE_VAL);
                put("insertUserId", "Insert User Id");
                put("insertDate", "Insert Date");
                put("insertUserDisplayName", "Insert User Display Name");
                put(IS_DOMESTIC, IS_DOMESTIC_VALUE);
                put("isPublic", "Is Public");
                put("isActive", "Is Active");
        }};
        public static final Map<String, String> BookingCarriageFieldNameToDisplayNameMap = new HashMap<String, String>() {{
                put("portOfLoading", "Port Of Loading");
                put("portOfDischarge", "Port Of Discharge");
                put("eta", "Eta");
                put("etd", "Etd");
                put("vessel", "Vessel");
                put("voyage", VOYAGE_VAL);
                put("carriageType", "Carriage Type");
                put("carriageMode", "Carriage Mode");
                put(SHIPMENT_ID, SHIPMENT_ID_VALUE);
        }};
        public static final Map<String, String> EventsFieldNameToDisplayNameMap = new HashMap<String, String>() {{
                put(ENTITY_ID, ENTITY_ID_VAL);
                put(ENTITY_TYPE, ENTITY_TYPE_VAL);
                put("eventCode", "Event Code");
                put("description", "Description");
                put("estimated", "Estimated");
                put("actual", "Actual");
                put("isPublicTrackingEvent", "Is Public Tracking Event");
                put("placeName", "Place Name");
                put("placeDescription", "Place Description");
                put("latitude", "Latitude");
                put("longitude", "Longitude");
                put("source", "Source");
                put("event_estimate_update_reasons", "Event Estimate Update Reasons");
        }};
        public static final Map<String, String> ReferenceNumbersFieldNameToDisplayNameMap = new HashMap<String, String>() {{
                put(CONSOLIDATION_ID, CONSOLIDATION_ID_VAL);
                put("countryOfIssue", "Country Of Issue");
                put("type", "Type");
                put("referenceNumber", REFERENCE_NUMBER_VAL);
                put(SHIPMENT_ID, SHIPMENT_ID_VALUE);
                put("isPortalEnable", "Is Portal Enable");
        }};
        public static final Map<String, String> PartiesFieldNameToDisplayNameMap = new HashMap<String, String>() {{
                put(ENTITY_ID, ENTITY_ID_VAL);
                put(ENTITY_TYPE, ENTITY_TYPE_VAL);
                put("type", "Type");
                put("orgCode", ORG_CODE_VAL);
                put("addressCode", ADDRESS_CODE_VAL);
                put("orgData", ORG_DATA_VAL);
                put("addressData", ADDRESS_DATA_VAL);
                put("isAddressFreeText", IS_ADDRESS_FREE_TEXT_VAL);
        }};
        public static final Map<String, String> ServiceDetailsFieldNameToDisplayNameMap = new HashMap<>() {{
                put(SHIPMENT_ID, SHIPMENT_ID_VALUE);
                put(CONSOLIDATION_ID, CONSOLIDATION_ID_VAL);
                put("serviceType", "Service Type");
                put("contractor", "Contractor");
                put("contractor.entityId", "Contractor: Entity Id");
                put("contractor.entityType", "Contractor: Entity Type");
                put("contractor.type", "Contractor: Type");
                put("contractor.orgCode", "Contractor: Org Code");
                put("contractor.addressCode", "Contractor: Address Code");
                put("contractor.orgData", "Contractor: Org Data");
                put("contractor.addressData", "Contractor: Address Data");
                put("contractor.isAddressFreeText", "Contractor: Is Address Free Text");
                put("srvLocation", "Service Location");
                put("bookingDate", "Booking Date");
                put("serviceCount", "Service Count");
                put("serviceDuration", "Service Duration");
                put("completionDate", "Completion Date");
                put("refNumber", REFERENCE_NUMBER_VAL);
                put("serviceNotes", "Service Notes");
        }};
        public static final Map<String, String> TruckDriverDetailsFieldNameToDisplayName = new HashMap<>() {{
                put(SHIPMENT_ID, SHIPMENT_ID_VALUE);
                put("transporterType", "Transporter Type");
                put("transporterName", "Transporter Name");
                put("driverName", "Driver Name");
                put("driverMobileNumber", "Driver Mobile Number");
                put("truckNumberPlate", "Truck Number Plate");
                put("trailerNumberPlate", "Trailer Number Plate");
                put("truckOrTrailerType", "Truck or Trailer Type");
                put("containerTypeCode", "Container Type Code");
                put("containerId", "Container Id");
                put(CONSOLIDATION_ID, CONSOLIDATION_ID_VAL);
                put("selfTransporterName", "Self Transporter Name");
                put("remarks", "Remarks");
                put("truckStatus", "Truck Status");
        }};
}
