CREATE TABLE IF NOT EXISTS quote_contracts (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    contract_id varchar(255),
    container_types jsonb,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by varchar(64),
    updated_by varchar(64),
    is_deleted BOOLEAN DEFAULT FALSE
);