CREATE TABLE IF NOT EXISTS integration_responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guid uuid,
  entity_id bigint NOT NULL,
  entity_type varchar(32) NOT NULL,
  integration_type varchar(64) NOT NULL,
  status varchar(64) NOT NULL,
  response_message jsonb NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  created_by VARCHAR,
  updated_by VARCHAR,
  tenant_id integer,
  is_deleted BOOLEAN DEFAULT FALSE
);