package com.dpw.runner.shipment.services.syncing.Entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

public class ContainerRequestV2 {

    public UUID Guid;
    public BigDecimal AchievedVolume;
    public String AchievedVolumeUnit;
    public BigDecimal AchievedWeight;
    public String AchievedWeightUnit;
    public BigDecimal AllocatedVolume;
    public String AllocatedVolumeUnit;
    public BigDecimal AllocatedWeight;
    public String AllocatedWeightUnit;
    public LocalDateTime AllocationDate;
    public String CarrierSealNumber;
    public BigDecimal Chargeable;
    public String ChargeableUnit;
    public String CommodityCode;
    public Long ConsolidationId;
    public String ContainerCode;
    public String ContainerComments;
    public String ContainerCount;
    public String ContainerNumber;
    public String ContainerStuffingLocationName;
    public String CustomsReleaseCode;
    public String CustomsSealNumber;
    public PartyRequestV2 DeliveryAddressJson;
    public String DescriptionOfGoods;
    public String DgClassString;
    public List<EventsRequestV2> EventsList;
    public String ExtraParams;
    public BigDecimal GrossVolume;
    public String GrossVolumeUnit;
    public BigDecimal GrossWeight;
    public String GrossWeightUnit;
    public Boolean IsHazardous;
    public String HazardousUn;
    public String HblDeliveryMode;
    public String HsCode;
    public String InnerPackageMeasurementUnit;
    public String InnerPackageNumber;
    public String InnerPackageType;
    public Boolean IsEmpty;
    public Boolean IsOwnContainer;
    public Boolean IsReefer;
    public Boolean IsShipperOwned;
    public Boolean IsTemperatureMaintained;
    public String MarksnNums;
    public BigDecimal MaxTemp;
    public String MaxTempUnit;
    public BigDecimal MinTemp;
    public String MinTempUnit;
    public BigDecimal Measurement;
    public String MeasurementUnit;
    public BigDecimal NetWeight;
    public String NetWeightUnit;
    public Long NoOfPackages;
    public String PackageBreadth;
    public String PackageHeight;
    public String PackageLength;
    public String Packs;
//    public List<PackRequestV2> PacksList;
    public String PacksType;
    public String PacrNumber;
    public PartyRequestV2 PickupAddressJson;
    public String Remarks;
    public String SealNumber;
    public String SerialNumber;
    public List<Long> ShipmentsList;
    public String ShipperSealNumber;
    public String StatusString;
    public BigDecimal TareWeight;
    public String TareWeightUnit;
    public String TerminalOperatorSealNumber;
    public String TransportMode;
    public String VeterinarySealNumber;
    public String VolumeUtilization;
    public String WeightUtilization;
}
