update parties
set
    org_code = 'FRC00026122',
	address_code = 'FRO00026964',
	org_id = '159417',
	address_id = '268744',
	updated_at = NOW(),
	org_data = '{
                    "Id": 159417,
                    "City": "HALLSTADT",
                    "Guid": "3e40f5df-005a-4bc8-9585-9df91b329335",
                    "Email": "d.kudlyk@optimum-maschinen.de",
                    "IsGSA": false,
                    "Phone": "951996555805",
                    "label": "OPTIMUM MASCHINEN GERMANY GMBH",
                    "value": "FRC00026122",
                    "Broker": false,
                    "Source": "CRP",
                    "Carrier": false,
                    "Country": "DEU",
                    "Address1": "DR.-ROBERT-PFLEGER-STR.26",
                    "FullName": "OPTIMUM MASCHINEN GERMANY GMBH",
                    "IsActive": 1,
                    "Payables": false,
                    "Services": false,
                    "TenantId": 442,
                    "CompanyId": 372,
                    "Consignee": true,
                    "Consigner": true,
                    "IsParnter": false,
                    "PANNumber": "FRC00026122",
                    "TaxVendor": false,
                    "WareHouse": false,
                    "AirCarrier": false,
                    "ExtraParam": "",
                    "InsertDate": "2025-07-28T12:52:42.000",
                    "SeaCarrier": false,
                    "UpdateDate": "2025-07-28T12:52:42.000",
                    "IsSuspended": false,
                    "RailCarrier": false,
                    "Receivables": false,
                    "RoadCarrier": false,
                    "ZipPostCode": "96103",
                    "ActiveClient": true,
                    "CurrencyCode": "EUR",
                    "EmailInvoice": false,
                    "InsertUserId": 1712,
                    "UpdateUserId": 1712,
                    "ForworderAgent": false,
                    "IsCreditEnabled": false,
                    "IsV2PaymentTerm": false,
                    "TransportClient": false,
                    "IsWalkInCustomer": false,
                    "OrganizationCode": "FRC00026122",
                    "EnableBulkInvoice": false,
                    "InsertUserIdUsername": "p100serviceaccountegypt@dpworld.com",
                    "UpdateUserIdUsername": "p100serviceaccountegypt@dpworld.com",
                    "IsClientEInvoiceEnabled": false,
                    "ImportExportClearanceLock": false,
                    "FusionCreditlimitOverrideApproved": false
                }',
                address_data = '{
                                    "Id": 268744,
                                    "City": "HALLSTADT",
                                    "Email": "d.kudlyk@optimum-maschinen.de",
                                    "label": "FRO00026964",
                                    "value": "FRO00026964",
                                    "Country": "DEU",
                                    "OrgGuid": "3e40f5df-005a-4bc8-9585-9df91b329335",
                                    "Address1": "DR.-ROBERT-PFLEGER-STR.26",
                                    "OrgSource": "CRP",
                                    "AddressType": 2,
                                    "CompanyName": "OPTIMUM MASCHINEN GERMANY GMBH",
                                    "OrgFullName": "OPTIMUM MASCHINEN GERMANY GMBH",
                                    "OrgPayables": false,
                                    "ZipPostCode": "96103",
                                    "OrgReceivables": false,
                                    "OrgActiveClient": true,
                                    "AddressShortCode": "FRO00026964",
                                    "OrgOrganizationCode": "FRC00026122"
                                }'
                                where id in (select client_id from shipment_details where id in (82863));