package com.dpw.runner.shipment.services.dto.v3.request;

import com.dpw.runner.shipment.services.commons.requests.CommonRequest;
import com.dpw.runner.shipment.services.commons.requests.IRunnerRequest;
import com.dpw.runner.shipment.services.dto.request.*;
import com.dpw.runner.shipment.services.utils.ExcludeTimeZone;
import com.dpw.runner.shipment.services.utils.TrimStringDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ConsolidationDetailsV3Request extends CommonRequest implements IRunnerRequest {
    private Long id;
    private String consolidationNumber;
    private String consolidationType;
    private String transportMode;
    private String containerCategory;
    private Boolean isDomestic;
    @JsonDeserialize(using = TrimStringDeserializer.class)
    private String mawb;
    private String serviceLevel;
    private String payment;
    private String declarationType;
    private String deliveryMode;
    private Boolean isLinked;
    private Boolean isCharter;
    private String referenceNumber;
    private String packageType;
    private String agentReference;
    private String coLoadMBL;
    private String coLoadBookingReference;
    private String manifestPrint;
    private String printOtherDocs;
    private String awbDims;
    private String releaseType;
    private LocalDateTime masterBillIssueDate;
    private String dgClass;
    private String dgSubstance;
    private Boolean override;
    private LocalDateTime estimatedTerminalCutoff;
    private LocalDateTime terminalCutoff;
    private LocalDateTime verifiedGrossMassCutoff;
    private LocalDateTime reeferCutoff;
    private LocalDateTime bookingCutoff;
    private LocalDateTime shipInstructionCutoff;
    private LocalDateTime hazardousBookingCutoff;
    private LocalDateTime latestFullEquDeliveredToCarrier;
    private LocalDateTime earliestDropOffFullEquToCarrier;
    private LocalDateTime earliestEmptyEquPickUp;
    private String volumeUtilization;
    private String weightUtilization;
    private String shipmentType;
    @JsonDeserialize(using = TrimStringDeserializer.class)
    private String bol;
    private Boolean isCargoOnly;
    private Boolean isLocked;
    private String lockedBy;
    private String specialInstructions;
    private String description;
    private String marksnNums;
    private String additionalTerms;
    private LocalDateTime docsClosingTime;
    private LocalDateTime cargoClosingTime;
    private String mrnNumber;
    private String msnNumber;
    private LocalDateTime igmFileDate;
    private LocalDateTime igmInwardDate;
    private LocalDateTime inwardDateAndTime;
    private String igmFileNo;
    private String smtpigmNumber;
    private LocalDateTime smtpigmDate;
    private Boolean isInland;
    private Integer original;
    private Integer copy;
    private String doPlaceOfIssue;
    private LocalDateTime doIssueDate;
    private Long bondedWarehouseId;
    private Long warehouseId;
    private Long sourceTenantId;
    private String ediTransactionId;
    private List<TriangulationPartnerRequest> triangulationPartnerList;
    private Long triangulationPartner;
    private Long receivingBranch;
    private boolean intraBranch;
    private Long documentationPartner;
    private Boolean isReceivingAgentFreeTextAddress;
    private String receivingAgentFreeTextAddress;
    private Boolean isSendingAgentFreeTextAddress;
    private String sendingAgentFreeTextAddress;
    private String placeOfIssue;
    private CarrierDetailRequest carrierDetails;
    private AchievedQuantitiesRequest achievedQuantities;
    private AllocationsRequest allocations;
    private ArrivalDepartureDetailsRequest arrivalDetails;
    private ArrivalDepartureDetailsRequest departureDetails;
    private String sendingAgentCountry;
    private String receivingAgentCountry;
    private PartiesRequest sendingAgent;
    private PartiesRequest receivingAgent;
    private PartiesRequest borrowedFrom;
    private PartiesRequest creditor;
    private PartiesRequest coLoadWith;
    private Long bookingAgent;
    private String coLoadCarrierName;
    private List<ReferenceNumbersRequest> referenceNumbersList;
    private List<PartiesRequest> consolidationAddresses;
    private String carrierBookingRef;
    private String modeOfBooking;
    private Boolean autoUpdateGoodsDesc;
    private UUID sourceGuid;
    private String efreightStatus;
    private Boolean hazardous;
    private String emergencyContactNumber;
    private String emergencyContactNumberCode;
    private Boolean creatingFromDgShipment;
    private String securityStatus;
    private List<String> screeningStatus;
    private String exemptionCodes;
    private String aomFreeText;
    private String sci;
    private String additionalSecurityInformation;
    private LocalDateTime cfsCutOffDate;
    private Boolean openForAttachment;
    private Boolean interBranchConsole;
    @ExcludeTimeZone
    private LocalDateTime latDate;
    private String department;
    private Boolean isNetworkFile;
    private Boolean isReceivingBranchManually;
    private Boolean isTransferredToReceivingBranch;
    private String partner;
    private Boolean borrowed;
    private Long originBranch;
}
