package com.dpw.runner.shipment.services.dto.request;

import com.dpw.runner.shipment.services.commons.requests.CommonRequest;
import com.dpw.runner.shipment.services.commons.requests.IRunnerRequest;
import com.dpw.runner.shipment.services.entity.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.Where;

import javax.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ConsolidationDetailsRequest extends CommonRequest implements IRunnerRequest {
    private Long id;
    private String consolidationNumber;
    private String consolidationType;
    private String transportMode;
    private String containerCategory;
    private Boolean isDomestic;
    private String MAWB;
    private String serviceLevel;
    private String payment;
    private String firstLoad;
    private String lastDischarge;
    private String bookingType;
    private String declarationType;
    private String deliveryMode;
    private Boolean isLinked;
    private Boolean isCharter;
    private String referenceNumber;
    private String packageType;
    private String agentReference;
    private String coLoadMBL;
    private String coLoadBookingReference;
    private String manifestPrint;
    private String printOtherDocs;
    private String awbDims;
    private String releaseType;
    private LocalDateTime masterBillIssueDate;
    private String dgClass;
    private String dgSubstance;
    private Boolean override;
    private LocalDateTime EstimatedTerminalCutoff;
    private LocalDateTime TerminalCutoff;
    private LocalDateTime VerifiedGrossMassCutoff;
    private LocalDateTime ReeferCutoff;
    private LocalDateTime BookingCutoff;
    private LocalDateTime ShipInstructionCutoff;
    private LocalDateTime HazardousBookingCutoff;
    private String volumeUtilization;
    private String weightUtilization;
    private String shipmentType;
    private String bol;
    private Boolean isCargoOnly;
    private Boolean isLocked;
    private String lockedBy;
    private String specialInstructions;
    private String description;
    private String MarksnNums;
    private String AdditionalTerms;
    private LocalDateTime docsClosingTime;
    private LocalDateTime cargoClosingTime;
    private String mrnNumber;
    private String msnNumber;
    private LocalDateTime IGMFileDate;
    private LocalDateTime IGMInwardDate;
    private LocalDateTime inwardDateAndTime;
    private String igmFileNo;
    private String SMTPIGMNumber;
    private LocalDateTime SMTPIGMDate;
    private Boolean isInland;
    private Integer original;
    private Integer copy;
    private Long DOPlaceOfIssueId;
    private LocalDateTime DOIssueDate;
    private Long bondedWarehouseId;
    private Long warehouseId;
    private long SourceTenantId;
    private String ediTransactionId;
    private long triangulationPartner;
    private long receivingBranch;
    private boolean intraBranch;
    private long documentationPartner;
    private Boolean isReceivingAgentFreeTextAddress;
    private String receivingAgentFreeTextAddress;
    private Boolean IsSendingAgentFreeTextAddress;
    private String sendingAgentFreeTextAddress;
    private CarrierDetailRequest carrierDetails;
    private AchievedQuantitiesRequest achievedQuantities;
    private AllocationsRequest allocations;
    private ArrivalDepartureDetailsRequest arrivalDepartureDetails;
    private List<PackingRequest> packingList;
    private List<ReferenceNumbersRequest> referenceNumbersList;
    private List<RoutingsRequest> routingsList;
    private List<ContainerRequest> containersList;
    private List<TruckDriverDetailsRequest> truckDriverDetails;
    private List<JobRequest> jobsList;
    private List<EventsRequest> eventsList;
    private List<FileRepoRequest> fileRepoList;
    private List<NotesRequest> notesList;
}
