package com.dpw.runner.shipment.services.dto.request;

import com.dpw.runner.shipment.services.commons.requests.CommonRequest;
import com.dpw.runner.shipment.services.commons.requests.IRunnerRequest;
import io.swagger.annotations.ApiModel;
import lombok.*;

@Getter
@Setter
@ApiModel("Hawb Lock Settings Request Model")
@ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class HawbLockSettingsRequest extends CommonRequest implements IRunnerRequest {

    private Long id;
    private Boolean shipperNameLock;
    private Boolean shipperAddressLock;
    private Boolean consigneeNameLock;
    private Boolean consigneeAddressLock;
    private Boolean issuingAgentNameLock;
    private Boolean issuingAgentAddressLock;
    private Boolean iataCodeLock;
    private Boolean awbNumberLock;
    private Boolean notifyPartyLock;
    private Boolean routingDetailsLock;
    private Boolean accountingInfoLock;
    private Boolean handlingInfoLock;
    private Boolean otherInfoLock;
    private Boolean ntrQtyGoodsLock;
    private Boolean specialHandlingCodesLock;
    private Boolean referenceNumberLock;
    private Boolean shippingInformationLock;
    private Boolean sciLock;
    private Boolean currencyLock;
    private Boolean chargeCodeLock;
    private Boolean carriageValueLock;
    private Boolean customsValueLock;
    private Boolean insuranceAmountLock;
    private Boolean customOriginCodeLock;
    private Boolean goodsDescriptionLock;
    private Boolean packingLock;
    private Boolean prepaidDueAgentChargesLock;
    private Boolean prepaidDueCarrierChargesLock;
    private Boolean totalPrepaidLock;
    private Boolean collectWeightChargesLock;
    private Boolean collectValuationChargeLock;
    private Boolean collectTaxLock;
    private Boolean totalCollectLock;
    private Boolean otherChargesLock;
    private Boolean shipperLock;
    private Boolean carrierLock;
    private Boolean executedAtLock;
    private Boolean executedOnLock;
    private Boolean otherCustomsLock;
    private Boolean notifyOrganizationLock;
    private Boolean notifyOrganizationAddressLock;
    private Boolean airportOfDepartureLock;
    private Boolean airportOfDestinationLock;
    private Boolean firstCarrierLock;
    private Boolean originPortLock;
    private Boolean destinationPortLock;
    private Boolean byCarrierLock;
    private Boolean flightNumberLock;
    private Boolean flightDateLock;
    private Boolean informationIdentifierLock;
    private Boolean tradeIdentificationCodeLock;
    private Boolean tradeIdentificationCommentLock;
    private Boolean chargeDescriptionLock;
    private Boolean rateLock;
    private Boolean chargeBasisLock;
    private Boolean chargesDueLock;
    private Boolean piecesNoLock;
    private Boolean grossWtLock;
    private Boolean grossWtUnitLock;
    private Boolean rateClassLock;
    private Boolean commodityItemNoLock;
    private Boolean chargeableWtLock;
    private Boolean rateChargeLock;
    private Boolean totalAmountLock;
    private Boolean slacCodeLock;
    private Boolean hsCodeLock;
    private Boolean packingAwbGoodsDescIdLock;
    private Boolean packingPacksLock;
    private Boolean packingPacksTypeLock;
    private Boolean packingOriginLock;
    private Boolean packingOrderLock;
    private Boolean packingLengthLock;
    private Boolean packingLengthUnitLock;
    private Boolean packingWidthLock;
    private Boolean packingWidthUnitLock;
    private Boolean packingHeightLock;
    private Boolean packingHeightUnitLock;
    private Boolean packingWeightLock;
    private Boolean packingWeightUnitLock;
    private Boolean packingVolumeLock;
    private Boolean packingVolumeUnitLock;
    private Boolean packingNetWeightLock;
    private Boolean packingNetWeightUnitLock;
    private Boolean packingVolumeWeightLock;
    private Boolean packingVolumeWeightUnitLock;
    private Boolean packingMarksnNumsLock;
    private Boolean packingCountryCodeLock;
    private Boolean packingGoodsDescLock;
    private Boolean packingReferenceNumberLock;
    private Boolean packingInspectionsLock;
    private Boolean packingDgClassLock;
    private Boolean packingDgSubstanceIdLock;
    private Boolean packingMinTempLock;
    private Boolean packingMinTempUnitLock;
    private Boolean packingMaxTempLock;
    private Boolean packingMaxTempUnitLock;
    private Boolean packingCommodityLock;
    private Boolean packingHsCodeLock;
    private Boolean shipperAddressLine2Lock;
    private Boolean shipperCityLock;
    private Boolean shipperStateCode;
    private Boolean shipperZipCode;
    private Boolean shipperCountyCodeLock;
    private Boolean shipperCountryNameLock;
    private Boolean shipperPhoneNumberLock;
    private Boolean shipperTAXNumberLock;
    private Boolean shipperAccountNumber;
    private Boolean consigneeAddressLine2Lock;
    private Boolean consigneeCityLock;
    private Boolean consigneeStateCode;
    private Boolean consigneeZipCode;
    private Boolean consigneeCountyCodeLock;
    private Boolean consigneeCountryNameLock;
    private Boolean consigneeContactNameLock;
    private Boolean consigneePhoneNumberLock;
    private Boolean consigneeTAXNumberLock;
    private Boolean consigneeAccountNumber;
    private Boolean notifyAddressLine2Lock;
    private Boolean notifyCityLock;
    private Boolean notifyStateCode;
    private Boolean notifyZipCode;
    private Boolean notifyCountyCodeLock;
    private Boolean notifyCountryNameLock;
    private Boolean notifyContactNameLock;
    private Boolean notifyPhoneNumberLock;
    private Boolean notifyTAXNumberLock;
    private Boolean issuingAgentAddressLine2Lock;
    private Boolean issuingAgentCityLock;
    private Boolean issuingAgentStateCode;
    private Boolean issuingAgentZipCode;
    private Boolean issuingAgentCountyCodeLock;
    private Boolean issuingAgentCountryNameLock;
    private Boolean issuingAgentContactNameLock;
    private Boolean issuingAgentPhoneNumberLock;
    private Boolean issuingAgentTAXNumberLock;
    private Boolean specifiedAddressLocation;
    private Boolean cassCode;
    private Boolean accountNumber;
    private Boolean otherInformationCodeLock;
    private Boolean overrideAutoUpdateLock;
    private Boolean countryCodeLock;
    private Boolean raNumberLock;
    private Boolean raExpiryDateLock;
    private Boolean screeningStatusLock;
    private Boolean screeningTimeLock;
    private Boolean screenerNameLock;
    private Boolean grossVolumeLock;
    private Boolean grossVolumeUnitLock;
    private Boolean dimensionsLock;
    private Boolean versionLock;
}
