package com.dpw.runner.shipment.services.dto.request;

import com.dpw.runner.shipment.services.commons.requests.CommonRequest;
import com.dpw.runner.shipment.services.commons.requests.IRunnerRequest;
import com.dpw.runner.shipment.services.entity.enums.GenerationType;
import io.swagger.annotations.ApiModel;
import java.time.LocalDateTime;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ApiModel("Shipment Settings Request Model")
@ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ShipmentSettingRequest extends CommonRequest implements IRunnerRequest {
    private Long id;
    private Long tenantId;
    private Boolean autoUpdateShipmentAWB;
    private Boolean autoUpdateShipmentBL;
    private Boolean houseBillNumberLock;
    private Boolean restrictHblGen;
    private Boolean printPhoneNumber;
    private String housebillPrefix;
    private String housebillNumberGeneration;
    private Integer footerColumns;
    private Boolean isAutoPopulateShipType;
    private Boolean partialCloningEnabled;
    private Boolean shipConsolidationContainerEnabled;
    private Boolean autoAttachConsolidation;
    private Boolean multipleShipmentEnabled;
    private Boolean enableRouteMaster;
    private Boolean arApFlag;
    private Boolean shipmentTiCargesLinkage;
    private Integer cooldownTime;
    private Integer advancePeriod;
    private Boolean autoEventCreate;
    private Boolean shipmentLite;
    private Boolean billingLite;
    private Boolean restrictedLocationsEnabled;
    private Boolean isAtdAtaAutoPopulateEnabled;
    private List<String> restrictedLocations;
    private String shipmentConsoleImportApproverRole;
    private GenerationType shipmentIdGenerationType;
    private String shipmentIdGenerationPrefix;
    private Integer shipmentIdGenerationCounter;
    private Boolean lowMarginApproval;
    private List<HblTermsConditionTemplateRequest> hblTermsConditionTemplate;
    private List<HblTermsConditionTemplateRequest> hblHawbBackPrintTemplate;
    private Boolean inlineEnabled;
    private Boolean carrierMandatory;
    private Integer weightVolumeDecimalPlace;
    private String dpwDateFormat;
    private String weightChargeableUnit;
    private String volumeChargeableUnit;
    private String measurementChargeableUnit;
    private String temperatureUnit;
    private String defaultTransportMode;
    private String defaultContainerType;
    private String defaultShipmentType;
    private String emailHost;
    private Long emailPort;
    private Boolean emailUseSsl;
    private String emailFrom;
    private String emailUserName;
    private String emailPassword;
    private Boolean emailIsfAsmResponse;
    private String defaultFailureEmailIds;
    private Boolean shipmentLock;
    private String orgPrefix;
    private Boolean orgCodeLock;
    private Boolean countryPrefix;
    private GenerationType orgNumberGeneration;
    private Boolean unLocoCodeEnabled;
    private Boolean enableOrgAddressUpdate;
    private Boolean allowFreeTextAddress;
    private Boolean isConsolidator;
    private Boolean mergeContainers;
    private Boolean bolNumberLock;
    private Boolean isShowMBL;
    private Boolean consolidationLite;
    private Boolean containerEventBulkUpload;
    private String bolNumberPrefix;
    private GenerationType bolNumberGeneration;
    private Boolean isMandateDocType;
    private String houseMainPage;
    private String hblFooter;
    private Boolean printAfterEachPage;
    private String seawayMainPage;
    private String shipTruckWayBillMainPage;
    private String consTruckWayBillMainPage;
    private String shipTruckDriverProof;
    private String consTruckDriverProof;
    private String commercialInvMainPage;
    private String packingListMainPage;
    private String customsInsMainPage;
    private String airwayMainPage;
    private String canMainPage;
    private String canBackPrint;
    private String arrivalNotice;
    private String freightCertification;
    private String preAlertDoc;
    private String manifestPrint;
    private String containerManifestPrint;
    private String seaImportShipmentManifest;
    private String seaExportShipmentManifest;
    private String seaImportConsoleManifest;
    private String seaExportConsoleManifest;
    private String airImportShipmentManifest;
    private String airExportShipmentManifest;
    private String airImportConsoleManifest;
    private String airExportConsoleManifest;
    private String proofOfDelivery;
    private String pickupOrder;
    private String deliveryOrder;
    private String bookingConfirmation;
    private String costalDocument;
    private String shippingInstruction;
    private String consolidatedPackingList;
    private String awbLable;
    private String cargoManifest;
    private String packingListMainPageAir;
    private String freightCertificationAir;
    private String preAlertAir;
    private String bookingConfirmationAir;
    private String pickupOrderAir;
    private String deliveryOrderAir;
    private String canMainPageAir;
    private String canBackPrintAir;
    private String customsInsMainPageAir;
    private String commercialInvMainPageAir;
    private String arrivalNoticeAir;
    private String hawb;
    private String mawb;
    private String awbNeutral;
    private String csr;
    private String shippingRequestMainPage;
    private String shippingRequestAir;
    private String seaShippingInstructionMainPage;
    private String defaultEmailTemplate;
    private Integer decimalPlaces;
    private Integer hblApprovalRole;
    private Boolean cargoFinanceBooking;
    private Boolean unicoBlObject;
    private HblLockSettingsRequest hblLockSettings;
    private Boolean customisedSequence;
    private List<TenantProductsRequest> tenantProducts;
    private List<ProductSequenceConfigRequest> productSequenceConfig;
    private HawbLockSettingsRequest hawbLockSettings;
    private MawbLockSettingsRequest mawbLockSettings;
    private Integer hblMultipleOriginalApproval;
    private Boolean hblApprovalFlow;
    private Boolean isShipmentLevelContainer;
    private Boolean restrictBlRelease;
    private Integer restrictBlApprovalRole;
    private Boolean eManifest;
    private String isfFileMainPage;
    private String cancelledBLSuffix;
    private Integer volumeDecimalPlace;
    private Integer weightDecimalPlace;
    private Boolean restrictBLEdit;
    private Boolean restrictAWBEdit;
    private Boolean regulatedAgent;
    private String raNumber;
    private LocalDateTime raExpiry;
    private String transportOrderRoad;
    private Boolean disableBlPartiesName;
    private Boolean airDGFlag;
    private Boolean iataTactFlag;
    private Boolean enableLclConsolidation;
    private String bookingOrder;
    private String bookingOrderForMbl;
    private String bookingOrderAir;
    private String bookingOrderAirForMawb;
    private String transportInstructionPickupOrder;
    private String transportInstructionDeliveryOrder;
    private Boolean enablePartyCheckForConsolidation;
    private String csd;
    private Boolean hideManifest;
    private LocalDateTime isEntityTransferPrerequisiteEnabledDate;
    private Boolean isEntityTransferPrerequisiteEnabled;
    private Boolean isNetworkTransferEntityEnabled;
    private Boolean isAutomaticTransferEnabled;
    private Boolean eventsRevampEnabled;
    private Boolean isAlwaysUtilization;
    private Boolean isUtilizationForContainerQuoted;
    private Boolean hasNoUtilization;
    private Boolean isAwbRevampEnabled;
    private String fcrDocument;
    private Boolean isRunnerV3Enabled;

    private Boolean isRAEnabled;
    private Boolean isKCEnabled;
}
