package com.dpw.runner.shipment.services.utils;

import java.util.Map;

public class V1PermissionMapUtil {

    private static final Map<String, String> v1PermissionMapping = Map.ofEntries(
            // SHIPMENT LIST PERMISSION MAPPINGS
            Map.entry("Shipments:List:Air Shipment:ImportAirShipmentList","air-imp-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:ExportAirShipmentList","air-exp-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:ReshipmentAirShipmentList","air-res-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:TranshipmentAirShipmentList","air-tra-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:EmptyContainerAirShipmentList","air-cts-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:DomesticAirShipmentList","air-dom-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:CrossTradeAirShipmentList","air-cts-all-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:AllAirShipmentList","air-shipmentList"),
            Map.entry("Shipments:List:All Shipment:ImportAllShipmentList","all-imp-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:ExportAllShipmentList","all-exp-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:ReshipmentAllShipmentList","all-res-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:TranshipmentAllShipmentList","all-tra-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:EmptyContainerAllShipmentList","all-emt-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:DomesticAllShipmentList","all-dom-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:CrossTradeAllShipmentList","all-cts-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:AllShipmentList","all-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:ImportRailShipmentList","rail-imp-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:ExportRailShipmentList","rail-exp-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:ReshipmentRailShipmentList","rail-res-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:TranshipmentRailShipmentList","rail-tra-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:EmptyContainerRailShipmentList","rail-emt-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:DomesticRailShipmentList","rail-dom-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:CrossTradeRailShipmentList","rail-cts-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:AllRailShipmentList","rail-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:ImportRoadShipmentList","road-imp-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:ExportRoadShipmentList","road-exp-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:ReshipmentRoadShipmentList","road-res-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:TranshipmentRoadShipmentList","road-tra-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:EmptyContainerRoadShipmentList","road-emt-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:DomesticRoadShipmentList","road-dom-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:CrossTradeRoadShipmentList","road-cts-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:AllRoadShipmentList","road-shipmentList"),
            // IsDomestic flag
            Map.entry("Shipments:List:Sea International Shipment:ImportSeaShipmentList","sea-imp-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:ExportSeaShipmentList","sea-exp-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:ReshipmentSeaShipmentList","sea-res-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:TranshipmentSeaShipmentList","sea-tra-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:EmptyContainerSeaShipmentList","sea-emt-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:DomesticSeaShipmentList","sea-dom-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:CrossTradeSeaShipmentList","sea-cts-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:AllSeaShipmentList","sea-all-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:ImportDomesticSeaShipmentList","sea-imp-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:ExportDomesticSeaShipmentList","sea-exp-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:ReshipmentDomesticSeaShipmentList","sea-res-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:TranshipmentDomesticSeaShipmentList","sea-tra-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:EmptyContainerDomesticSeaShipmentList","sea-emt-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:DomesticDomesticSeaShipmentList","sea-dom-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:CrossTradeDomesticSeaShipmentList","sea-cts-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:AllDomesticSeaShipmentList","sea-all-all-domestic-shipmentList"),

            // SHIPMENT RETRIEVE PERMISSIONS MAPPING
            Map.entry("Shipments:Retrive:Air Shipment:ImportAirShipmentRetrive","air-imp-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:ExportAirShipmentRetrive","air-exp-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:ReshipmentAirShipmentRetrive","air-res-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:TranshipmentAirShipmentRetrive","air-tra-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:EmptyContainerAirShipmentRetrive","air-cts-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:DomesticAirShipmentRetrive","air-dom-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:CrossTradeAirShipmentRetrive","air-cts-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:AllAirShipmentRetrive","air-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:ImportAllShipmentRetrive","all-imp-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:ExportAllShipmentRetrive","all-exp-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:ReshipmentAllShipmentRetrive","all-res-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:TranshipmentAllShipmentRetrive","all-tra-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:EmptyContainerAllShipmentRetrive","all-emt-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:DomesticAllShipmentRetrive","all-dom-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:CrossTradeAllShipmentRetrive","all-cts-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:AllShipmentRetrive","all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:ImportRailShipmentRetrive","rail-imp-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:ExportRailShipmentRetrive","rail-exp-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:ReshipmentRailShipmentRetrive","rail-res-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:TranshipmentRailShipmentRetrive","rail-tra-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:EmptyContainerRailShipmentRetrive","rail-emt-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:DomesticRailShipmentRetrive","rail-dom-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:CrossTradeRailShipmentRetrive","rail-cts-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:AllRailShipmentRetrive","rail-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:ImportRoadShipmentRetrive","road-imp-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:ExportRoadShipmentRetrive","road-exp-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:ReshipmentRoadShipmentRetrive","road-res-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:TranshipmentRoadShipmentRetrive","road-tra-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:EmptyContainerRoadShipmentRetrive","road-emt-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:DomesticRoadShipmentRetrive","road-dom-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:CrossTradeRoadShipmentRetrive","road-cts-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:AllRoadShipmentRetrive","road-shipmentRetrieve"),
            // IsDomestic flag
            Map.entry("Shipments:Retrive:Sea International Shipment:ImportSeaShipmentRetrive","sea-imp-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:ExportSeaShipmentRetrive","sea-exp-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:ReshipmentSeaShipmentRetrive","sea-res-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:TranshipmentSeaShipmentRetrive","sea-tra-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:EmptyContainerSeaShipmentRetrive","sea-emt-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:DomesticSeaShipmentRetrive","sea-dom-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:CrossTradeSeaShipmentRetrive","sea-cts-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:AllSeaShipmentRetrive","sea-all-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:ImportDomesticSeaShipmentRetrive","sea-imp-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:ExportDomesticSeaShipmentRetrive","sea-exp-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:ReshipmentDomesticSeaShipmentRetrive","sea-res-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:TranshipmentDomesticSeaShipmentRetrive","sea-tra-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:EmptyContainerDomesticSeaShipmentRetrive","sea-emt-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:DomesticDomesticSeaShipmentRetrive","sea-dom-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:CrossTradeDomesticSeaShipmentRetrive","sea-cts-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:AllDomesticSeaShipmentRetrive","sea-all-all-domestic-shipmentRetrieve"),

            // SHIPMENT CREATE PERMISSION MAPPINGS
            Map.entry("Shipments:Creation:Air Shipment:ImportAirShipmentCreate","air-imp-shipmentCreate"),
            Map.entry("Shipments:Creation:Air Shipment:ExportAirShipmentCreate","air-exp-shipmentCreate"),
            Map.entry("Shipments:Creation:Air Shipment:ReshipmentAirShipmentCreate","air-res-shipmentCreate"),
            Map.entry("Shipments:Creation:Air Shipment:TranshipmentAirShipmentCreate","air-tra-shipmentCreate"),
            Map.entry("Shipments:Creation:Air Shipment:EmptyContainerAirShipmentCreate","air-cts-shipmentCreate"),
            Map.entry("Shipments:Creation:Air Shipment:DomesticAirShipmentCreate","air-dom-shipmentCreate"),
            Map.entry("Shipments:Creation:Air Shipment:CrossTradeAirShipmentCreate","air-cts-all-shipmentCreate"),
            Map.entry("Shipments:Creation:Air Shipment:AllAirShipmentCreate","air-shipmentCreate"),
            Map.entry("Shipments:Creation:All Shipment:ImportAllShipmentCreate","all-imp-all-shipmentCreate"),
            Map.entry("Shipments:Creation:All Shipment:ExportAllShipmentCreate","all-exp-all-shipmentCreate"),
            Map.entry("Shipments:Creation:All Shipment:ReshipmentAllShipmentCreate","all-res-all-shipmentCreate"),
            Map.entry("Shipments:Creation:All Shipment:TranshipmentAllShipmentCreate","all-tra-all-shipmentCreate"),
            Map.entry("Shipments:Creation:All Shipment:EmptyContainerAllShipmentCreate","all-emt-all-shipmentCreate"),
            Map.entry("Shipments:Creation:All Shipment:DomesticAllShipmentCreate","all-dom-all-shipmentCreate"),
            Map.entry("Shipments:Creation:All Shipment:CrossTradeAllShipmentCreate","all-cts-all-shipmentCreate"),
            Map.entry("Shipments:Creation:All Shipment:AllShipmentCreate","all-shipmentCreate"),
            Map.entry("Shipments:Creation:Rail Shipment:ImportRailShipmentCreate","rail-imp-shipmentCreate"),
            Map.entry("Shipments:Creation:Rail Shipment:ExportRailShipmentCreate","rail-exp-shipmentCreate"),
            Map.entry("Shipments:Creation:Rail Shipment:ReshipmentRailShipmentCreate","rail-res-shipmentCreate"),
            Map.entry("Shipments:Creation:Rail Shipment:TranshipmentRailShipmentCreate","rail-tra-shipmentCreate"),
            Map.entry("Shipments:Creation:Rail Shipment:EmptyContainerRailShipmentCreate","rail-emt-shipmentCreate"),
            Map.entry("Shipments:Creation:Rail Shipment:DomesticRailShipmentCreate","rail-dom-shipmentCreate"),
            Map.entry("Shipments:Creation:Rail Shipment:CrossTradeRailShipmentCreate","rail-cts-shipmentCreate"),
            Map.entry("Shipments:Creation:Rail Shipment:AllRailShipmentCreate","rail-shipmentCreate"),
            Map.entry("Shipments:Creation:Road Shipment:ImportRoadShipmentCreate","road-imp-shipmentCreate"),
            Map.entry("Shipments:Creation:Road Shipment:ExportRoadShipmentCreate","road-exp-shipmentCreate"),
            Map.entry("Shipments:Creation:Road Shipment:ReshipmentRoadShipmentCreate","road-res-shipmentCreate"),
            Map.entry("Shipments:Creation:Road Shipment:TranshipmentRoadShipmentCreate","road-tra-shipmentCreate"),
            Map.entry("Shipments:Creation:Road Shipment:EmptyContainerRoadShipmentCreate","road-emt-shipmentCreate"),
            Map.entry("Shipments:Creation:Road Shipment:DomesticRoadShipmentCreate","road-dom-shipmentCreate"),
            Map.entry("Shipments:Creation:Road Shipment:CrossTradeRoadShipmentCreate","road-cts-shipmentCreate"),
            Map.entry("Shipments:Creation:Road Shipment:AllRoadShipmentCreate","road-shipmentCreate"),
            // IsDomestic flag
            Map.entry("Shipments:Creation:Sea International Shipment:ImportSeaShipmentCreate","sea-imp-all-international-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea International Shipment:ExportSeaShipmentCreate","sea-exp-all-international-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea International Shipment:ReshipmentSeaShipmentCreate","sea-res-all-international-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea International Shipment:TranshipmentSeaShipmentCreate","sea-tra-all-international-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea International Shipment:EmptyContainerSeaShipmentCreate","sea-emt-all-international-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea International Shipment:DomesticSeaShipmentCreate","sea-dom-all-international-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea International Shipment:CrossTradeSeaShipmentCreate","sea-cts-all-international-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea International Shipment:AllSeaShipmentCreate","sea-all-all-international-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea Domestic Shipment:ImportDomesticSeaShipmentCreate","sea-imp-all-domestic-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea Domestic Shipment:ExportDomesticSeaShipmentCreate","sea-exp-all-domestic-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea Domestic Shipment:ReshipmentDomesticSeaShipmentCreate","sea-res-all-domestic-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea Domestic Shipment:TranshipmentDomesticSeaShipmentCreate","sea-tra-all-domestic-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea Domestic Shipment:EmptyContainerDomesticSeaShipmentCreate","sea-emt-all-domestic-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea Domestic Shipment:DomesticDomesticSeaShipmentCreate","sea-dom-all-domestic-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea Domestic Shipment:CrossTradeDomesticSeaShipmentCreate","sea-cts-all-domestic-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea Domestic Shipment:AllDomesticSeaShipmentCreate","sea-all-all-domestic-shipmentCreate"),

            // SHIPMENT UPDATE PERMISSIONS MAPPING
            Map.entry("Shipments:Update:Air Shipment:ImportAirShipmentUpdate","air-imp-shipmentUpdate"),
            Map.entry("Shipments:Update:Air Shipment:ExportAirShipmentUpdate","air-exp-shipmentUpdate"),
            Map.entry("Shipments:Update:Air Shipment:ReshipmentAirShipmentUpdate","air-res-shipmentUpdate"),
            Map.entry("Shipments:Update:Air Shipment:TranshipmentAirShipmentUpdate","air-tra-shipmentUpdate"),
            Map.entry("Shipments:Update:Air Shipment:EmptyContainerAirShipmentUpdate","air-cts-shipmentUpdate"),
            Map.entry("Shipments:Update:Air Shipment:DomesticAirShipmentUpdate","air-dom-shipmentUpdate"),
            Map.entry("Shipments:Update:Air Shipment:CrossTradeAirShipmentUpdate","air-cts-all-shipmentUpdate"),
            Map.entry("Shipments:Update:Air Shipment:AllAirShipmentUpdate","air-shipmentUpdate"),
            Map.entry("Shipments:Update:All Shipment:ImportAllShipmentUpdate","all-imp-all-shipmentUpdate"),
            Map.entry("Shipments:Update:All Shipment:ExportAllShipmentUpdate","all-exp-all-shipmentUpdate"),
            Map.entry("Shipments:Update:All Shipment:ReshipmentAllShipmentUpdate","all-res-all-shipmentUpdate"),
            Map.entry("Shipments:Update:All Shipment:TranshipmentAllShipmentUpdate","all-tra-all-shipmentUpdate"),
            Map.entry("Shipments:Update:All Shipment:EmptyContainerAllShipmentUpdate","all-emt-all-shipmentUpdate"),
            Map.entry("Shipments:Update:All Shipment:DomesticAllShipmentUpdate","all-dom-all-shipmentUpdate"),
            Map.entry("Shipments:Update:All Shipment:CrossTradeAllShipmentUpdate","all-cts-all-shipmentUpdate"),
            Map.entry("Shipments:Update:All Shipment:AllShipmentUpdate","all-shipmentUpdate"),
            Map.entry("Shipments:Update:Rail Shipment:ImportRailShipmentUpdate","rail-imp-shipmentUpdate"),
            Map.entry("Shipments:Update:Rail Shipment:ExportRailShipmentUpdate","rail-exp-shipmentUpdate"),
            Map.entry("Shipments:Update:Rail Shipment:ReshipmentRailShipmentUpdate","rail-res-shipmentUpdate"),
            Map.entry("Shipments:Update:Rail Shipment:TranshipmentRailShipmentUpdate","rail-tra-shipmentUpdate"),
            Map.entry("Shipments:Update:Rail Shipment:EmptyContainerRailShipmentUpdate","rail-emt-shipmentUpdate"),
            Map.entry("Shipments:Update:Rail Shipment:DomesticRailShipmentUpdate","rail-dom-shipmentUpdate"),
            Map.entry("Shipments:Update:Rail Shipment:CrossTradeRailShipmentUpdate","rail-cts-shipmentUpdate"),
            Map.entry("Shipments:Update:Rail Shipment:AllRailShipmentUpdate","rail-shipmentUpdate"),
            Map.entry("Shipments:Update:Road Shipment:ImportRoadShipmentUpdate","road-imp-shipmentUpdate"),
            Map.entry("Shipments:Update:Road Shipment:ExportRoadShipmentUpdate","road-exp-shipmentUpdate"),
            Map.entry("Shipments:Update:Road Shipment:ReshipmentRoadShipmentUpdate","road-res-shipmentUpdate"),
            Map.entry("Shipments:Update:Road Shipment:TranshipmentRoadShipmentUpdate","road-tra-shipmentUpdate"),
            Map.entry("Shipments:Update:Road Shipment:EmptyContainerRoadShipmentUpdate","road-emt-shipmentUpdate"),
            Map.entry("Shipments:Update:Road Shipment:DomesticRoadShipmentUpdate","road-dom-shipmentUpdate"),
            Map.entry("Shipments:Update:Road Shipment:CrossTradeRoadShipmentUpdate","road-cts-shipmentUpdate"),
            Map.entry("Shipments:Update:Road Shipment:AllRoadShipmentUpdate","road-shipmentUpdate"),
            // IsDomestic flag
            Map.entry("Shipments:Update:Sea International Shipment:ImportSeaShipmentUpdate","sea-imp-all-international-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea International Shipment:ExportSeaShipmentUpdate","sea-exp-all-international-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea International Shipment:ReshipmentSeaShipmentUpdate","sea-res-all-international-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea International Shipment:TranshipmentSeaShipmentUpdate","sea-tra-all-international-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea International Shipment:EmptyContainerSeaShipmentUpdate","sea-emt-all-international-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea International Shipment:DomesticSeaShipmentUpdate","sea-dom-all-international-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea International Shipment:CrossTradeSeaShipmentUpdate","sea-cts-all-international-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea International Shipment:AllSeaShipmentUpdate","sea-all-all-international-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea Domestic Shipment:ImportDomesticSeaShipmentUpdate","sea-imp-all-domestic-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea Domestic Shipment:ExportDomesticSeaShipmentUpdate","sea-exp-all-domestic-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea Domestic Shipment:ReshipmentDomesticSeaShipmentUpdate","sea-res-all-domestic-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea Domestic Shipment:TranshipmentDomesticSeaShipmentUpdate","sea-tra-all-domestic-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea Domestic Shipment:EmptyContainerDomesticSeaShipmentUpdate","sea-emt-all-domestic-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea Domestic Shipment:DomesticDomesticSeaShipmentUpdate","sea-dom-all-domestic-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea Domestic Shipment:CrossTradeDomesticSeaShipmentUpdate","sea-cts-all-domestic-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea Domestic Shipment:AllDomesticSeaShipmentUpdate","sea-all-all-domestic-shipmentUpdate"),

            // CONSOLIDATION LIST PERMISSION MAPPINGS
            Map.entry("Consolidations:List:Air Consolidation:ImportAirConsolidationList","air-imp-consolidationList"),
            Map.entry("Consolidations:List:Air Consolidation:ExportAirConsolidationList","air-exp-consolidationList"),
            Map.entry("Consolidations:List:Air Consolidation:ReshipmentAirConsolidationList","air-res-consolidationList"),
            Map.entry("Consolidations:List:Air Consolidation:TranshipmentAirConsolidationList","air-tra-consolidationList"),
            Map.entry("Consolidations:List:Air Consolidation:EmptyContainerAirConsolidationList","air-cts-consolidationList"),
            Map.entry("Consolidations:List:Air Consolidation:DomesticAirConsolidationList","air-dom-consolidationList"),
            Map.entry("Consolidations:List:Air Consolidation:CrossTradeAirConsolidationList","air-cts-all-consolidationList"),
            Map.entry("Consolidations:List:Air Consolidation:AllAirConsolidationList","air-consolidationList"),
            Map.entry("Consolidations:List:All Consolidation:ImportAllConsolidationList","all-imp-all-consolidationList"),
            Map.entry("Consolidations:List:All Consolidation:ExportAllConsolidationList","all-exp-all-consolidationList"),
            Map.entry("Consolidations:List:All Consolidation:ReshipmentAllConsolidationList","all-res-all-consolidationList"),
            Map.entry("Consolidations:List:All Consolidation:TranshipmentAllConsolidationList","all-tra-all-consolidationList"),
            Map.entry("Consolidations:List:All Consolidation:EmptyContainerAllConsolidationList","all-emt-all-consolidationList"),
            Map.entry("Consolidations:List:All Consolidation:DomesticAllConsolidationList","all-dom-all-consolidationList"),
            Map.entry("Consolidations:List:All Consolidation:CrossTradeAllConsolidationList","all-cts-all-consolidationList"),
            Map.entry("Consolidations:List:All Consolidation:AllConsolidationList","all-consolidationList"),
            Map.entry("Consolidations:List:Rail Consolidation:ImportRailConsolidationList","rail-imp-consolidationList"),
            Map.entry("Consolidations:List:Rail Consolidation:ExportRailConsolidationList","rail-exp-consolidationList"),
            Map.entry("Consolidations:List:Rail Consolidation:ReshipmentRailConsolidationList","rail-res-consolidationList"),
            Map.entry("Consolidations:List:Rail Consolidation:TranshipmentRailConsolidationList","rail-tra-consolidationList"),
            Map.entry("Consolidations:List:Rail Consolidation:EmptyContainerRailConsolidationList","rail-emt-consolidationList"),
            Map.entry("Consolidations:List:Rail Consolidation:DomesticRailConsolidationList","rail-dom-consolidationList"),
            Map.entry("Consolidations:List:Rail Consolidation:CrossTradeRailConsolidationList","rail-cts-consolidationList"),
            Map.entry("Consolidations:List:Rail Consolidation:AllRailConsolidationList","rail-consolidationList"),
            Map.entry("Consolidations:List:Road Consolidation:ImportRoadConsolidationList","road-imp-consolidationList"),
            Map.entry("Consolidations:List:Road Consolidation:ExportRoadConsolidationList","road-exp-consolidationList"),
            Map.entry("Consolidations:List:Road Consolidation:ReshipmentRoadConsolidationList","road-res-consolidationList"),
            Map.entry("Consolidations:List:Road Consolidation:TranshipmentRoadConsolidationList","road-tra-consolidationList"),
            Map.entry("Consolidations:List:Road Consolidation:EmptyContainerRoadConsolidationList","road-emt-consolidationList"),
            Map.entry("Consolidations:List:Road Consolidation:DomesticRoadConsolidationList","road-dom-consolidationList"),
            Map.entry("Consolidations:List:Road Consolidation:CrossTradeRoadConsolidationList","road-cts-consolidationList"),
            Map.entry("Consolidations:List:Road Consolidation:AllRoadConsolidationList","road-consolidationList"),
            Map.entry("Consolidations:List:Sea Consolidation:ImportSeaConsolidationList","sea-imp-consolidationList"),
            Map.entry("Consolidations:List:Sea Consolidation:ExportSeaConsolidationList","sea-exp-consolidationList"),
            Map.entry("Consolidations:List:Sea Consolidation:ReshipmentSeaConsolidationList","sea-res-consolidationList"),
            Map.entry("Consolidations:List:Sea Consolidation:TranshipmentSeaConsolidationList","sea-tra-consolidationList"),
            Map.entry("Consolidations:List:Sea Consolidation:EmptyContainerSeaConsolidationList","sea-emt-consolidationList"),
            Map.entry("Consolidations:List:Sea Consolidation:DomesticSeaConsolidationList","sea-dom-consolidationList"),
            Map.entry("Consolidations:List:Sea Consolidation:CrossTradeSeaConsolidationList","sea-cts-consolidationList"),
            Map.entry("Consolidations:List:Sea Consolidation:AllSeaConsolidationList","sea-consolidationList"),

            // CONSOLIDATION RETRIEVE PERMISSIONS MAPPING
            Map.entry("Consolidations:Retrive:Air Consolidation:ImportAirConsolidationRetrive","air-imp-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Air Consolidation:ExportAirConsolidationRetrive","air-exp-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Air Consolidation:ReshipmentAirConsolidationRetrive","air-res-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Air Consolidation:TranshipmentAirConsolidationRetrive","air-tra-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Air Consolidation:EmptyContainerAirConsolidationRetrive","air-cts-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Air Consolidation:DomesticAirConsolidationRetrive","air-dom-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Air Consolidation:CrossTradeAirConsolidationRetrive","air-cts-all-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Air Consolidation:AllAirConsolidationRetrive","air-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:All Consolidation:ImportAllConsolidationRetrive","all-imp-all-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:All Consolidation:ExportAllConsolidationRetrive","all-exp-all-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:All Consolidation:ReshipmentAllConsolidationRetrive","all-res-all-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:All Consolidation:TranshipmentAllConsolidationRetrive","all-tra-all-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:All Consolidation:EmptyContainerAllConsolidationRetrive","all-emt-all-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:All Consolidation:DomesticAllConsolidationRetrive","all-dom-all-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:All Consolidation:CrossTradeAllConsolidationRetrive","all-cts-all-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:All Consolidation:AllConsolidationRetrive","all-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Rail Consolidation:ImportRailConsolidationRetrive","rail-imp-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Rail Consolidation:ExportRailConsolidationRetrive","rail-exp-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Rail Consolidation:ReshipmentRailConsolidationRetrive","rail-res-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Rail Consolidation:TranshipmentRailConsolidationRetrive","rail-tra-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Rail Consolidation:EmptyContainerRailConsolidationRetrive","rail-emt-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Rail Consolidation:DomesticRailConsolidationRetrive","rail-dom-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Rail Consolidation:CrossTradeRailConsolidationRetrive","rail-cts-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Rail Consolidation:AllRailConsolidationRetrive","rail-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Road Consolidation:ImportRoadConsolidationRetrive","road-imp-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Road Consolidation:ExportRoadConsolidationRetrive","road-exp-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Road Consolidation:ReshipmentRoadConsolidationRetrive","road-res-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Road Consolidation:TranshipmentRoadConsolidationRetrive","road-tra-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Road Consolidation:EmptyContainerRoadConsolidationRetrive","road-emt-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Road Consolidation:DomesticRoadConsolidationRetrive","road-dom-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Road Consolidation:CrossTradeRoadConsolidationRetrive","road-cts-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Road Consolidation:AllRoadConsolidationRetrive","road-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Sea Consolidation:ImportSeaConsolidationRetrive","sea-imp-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Sea Consolidation:ExportSeaConsolidationRetrive","sea-exp-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Sea Consolidation:ReshipmentSeaConsolidationRetrive","sea-res-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Sea Consolidation:TranshipmentSeaConsolidationRetrive","sea-tra-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Sea Consolidation:EmptyContainerSeaConsolidationRetrive","sea-emt-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Sea Consolidation:DomesticSeaConsolidationRetrive","sea-dom-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Sea Consolidation:CrossTradeSeaConsolidationRetrive","sea-cts-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Sea Consolidation:AllSeaConsolidationRetrive","sea-consolidationRetrieve"),

            // CONSOLIDATION CREATE PERMISSION MAPPINGS
            Map.entry("Consolidations:Creation:Air Consolidation:ImportAirConsolidationCreate","air-imp-consolidationCreate"),
            Map.entry("Consolidations:Creation:Air Consolidation:ExportAirConsolidationCreate","air-exp-consolidationCreate"),
            Map.entry("Consolidations:Creation:Air Consolidation:ReshipmentAirConsolidationCreate","air-res-consolidationCreate"),
            Map.entry("Consolidations:Creation:Air Consolidation:TranshipmentAirConsolidationCreate","air-tra-consolidationCreate"),
            Map.entry("Consolidations:Creation:Air Consolidation:EmptyContainerAirConsolidationCreate","air-cts-consolidationCreate"),
            Map.entry("Consolidations:Creation:Air Consolidation:DomesticAirConsolidationCreate","air-dom-consolidationCreate"),
            Map.entry("Consolidations:Creation:Air Consolidation:CrossTradeAirConsolidationCreate","air-cts-all-consolidationCreate"),
            Map.entry("Consolidations:Creation:Air Consolidation:AllAirConsolidationCreate","air-consolidationCreate"),
            Map.entry("Consolidations:Creation:All Consolidation:ImportAllConsolidationCreate","all-imp-all-consolidationCreate"),
            Map.entry("Consolidations:Creation:All Consolidation:ExportAllConsolidationCreate","all-exp-all-consolidationCreate"),
            Map.entry("Consolidations:Creation:All Consolidation:ReshipmentAllConsolidationCreate","all-res-all-consolidationCreate"),
            Map.entry("Consolidations:Creation:All Consolidation:TranshipmentAllConsolidationCreate","all-tra-all-consolidationCreate"),
            Map.entry("Consolidations:Creation:All Consolidation:EmptyContainerAllConsolidationCreate","all-emt-all-consolidationCreate"),
            Map.entry("Consolidations:Creation:All Consolidation:DomesticAllConsolidationCreate","all-dom-all-consolidationCreate"),
            Map.entry("Consolidations:Creation:All Consolidation:CrossTradeAllConsolidationCreate","all-cts-all-consolidationCreate"),
            Map.entry("Consolidations:Creation:All Consolidation:AllConsolidationCreate","all-consolidationCreate"),
            Map.entry("Consolidations:Creation:Rail Consolidation:ImportRailConsolidationCreate","rail-imp-consolidationCreate"),
            Map.entry("Consolidations:Creation:Rail Consolidation:ExportRailConsolidationCreate","rail-exp-consolidationCreate"),
            Map.entry("Consolidations:Creation:Rail Consolidation:ReshipmentRailConsolidationCreate","rail-res-consolidationCreate"),
            Map.entry("Consolidations:Creation:Rail Consolidation:TranshipmentRailConsolidationCreate","rail-tra-consolidationCreate"),
            Map.entry("Consolidations:Creation:Rail Consolidation:EmptyContainerRailConsolidationCreate","rail-emt-consolidationCreate"),
            Map.entry("Consolidations:Creation:Rail Consolidation:DomesticRailConsolidationCreate","rail-dom-consolidationCreate"),
            Map.entry("Consolidations:Creation:Rail Consolidation:CrossTradeRailConsolidationCreate","rail-cts-consolidationCreate"),
            Map.entry("Consolidations:Creation:Rail Consolidation:AllRailConsolidationCreate","rail-consolidationCreate"),
            Map.entry("Consolidations:Creation:Road Consolidation:ImportRoadConsolidationCreate","road-imp-consolidationCreate"),
            Map.entry("Consolidations:Creation:Road Consolidation:ExportRoadConsolidationCreate","road-exp-consolidationCreate"),
            Map.entry("Consolidations:Creation:Road Consolidation:ReshipmentRoadConsolidationCreate","road-res-consolidationCreate"),
            Map.entry("Consolidations:Creation:Road Consolidation:TranshipmentRoadConsolidationCreate","road-tra-consolidationCreate"),
            Map.entry("Consolidations:Creation:Road Consolidation:EmptyContainerRoadConsolidationCreate","road-emt-consolidationCreate"),
            Map.entry("Consolidations:Creation:Road Consolidation:DomesticRoadConsolidationCreate","road-dom-consolidationCreate"),
            Map.entry("Consolidations:Creation:Road Consolidation:CrossTradeRoadConsolidationCreate","road-cts-consolidationCreate"),
            Map.entry("Consolidations:Creation:Road Consolidation:AllRoadConsolidationCreate","road-consolidationCreate"),
            Map.entry("Consolidations:Creation:Sea Consolidation:ImportSeaConsolidationCreate","sea-imp-consolidationCreate"),
            Map.entry("Consolidations:Creation:Sea Consolidation:ExportSeaConsolidationCreate","sea-exp-consolidationCreate"),
            Map.entry("Consolidations:Creation:Sea Consolidation:ReshipmentSeaConsolidationCreate","sea-res-consolidationCreate"),
            Map.entry("Consolidations:Creation:Sea Consolidation:TranshipmentSeaConsolidationCreate","sea-tra-consolidationCreate"),
            Map.entry("Consolidations:Creation:Sea Consolidation:EmptyContainerSeaConsolidationCreate","sea-emt-consolidationCreate"),
            Map.entry("Consolidations:Creation:Sea Consolidation:DomesticSeaConsolidationCreate","sea-dom-consolidationCreate"),
            Map.entry("Consolidations:Creation:Sea Consolidation:CrossTradeSeaConsolidationCreate","sea-cts-consolidationCreate"),
            Map.entry("Consolidations:Creation:Sea Consolidation:AllSeaConsolidationCreate","sea-consolidationCreate"),

            // CONSOLIDATION UPDATE PERMISSIONS MAPPING
            Map.entry("Consolidations:Update:Air Consolidation:ImportAirConsolidationUpdate","air-imp-consolidationUpdate"),
            Map.entry("Consolidations:Update:Air Consolidation:ExportAirConsolidationUpdate","air-exp-consolidationUpdate"),
            Map.entry("Consolidations:Update:Air Consolidation:ReshipmentAirConsolidationUpdate","air-res-consolidationUpdate"),
            Map.entry("Consolidations:Update:Air Consolidation:TranshipmentAirConsolidationUpdate","air-tra-consolidationUpdate"),
            Map.entry("Consolidations:Update:Air Consolidation:EmptyContainerAirConsolidationUpdate","air-cts-consolidationUpdate"),
            Map.entry("Consolidations:Update:Air Consolidation:DomesticAirConsolidationUpdate","air-dom-consolidationUpdate"),
            Map.entry("Consolidations:Update:Air Consolidation:CrossTradeAirConsolidationUpdate","air-cts-all-consolidationUpdate"),
            Map.entry("Consolidations:Update:Air Consolidation:AllAirConsolidationUpdate","air-consolidationUpdate"),
            Map.entry("Consolidations:Update:All Consolidation:ImportAllConsolidationUpdate","all-imp-all-consolidationUpdate"),
            Map.entry("Consolidations:Update:All Consolidation:ExportAllConsolidationUpdate","all-exp-all-consolidationUpdate"),
            Map.entry("Consolidations:Update:All Consolidation:ReshipmentAllConsolidationUpdate","all-res-all-consolidationUpdate"),
            Map.entry("Consolidations:Update:All Consolidation:TranshipmentAllConsolidationUpdate","all-tra-all-consolidationUpdate"),
            Map.entry("Consolidations:Update:All Consolidation:EmptyContainerAllConsolidationUpdate","all-emt-all-consolidationUpdate"),
            Map.entry("Consolidations:Update:All Consolidation:DomesticAllConsolidationUpdate","all-dom-all-consolidationUpdate"),
            Map.entry("Consolidations:Update:All Consolidation:CrossTradeAllConsolidationUpdate","all-cts-all-consolidationUpdate"),
            Map.entry("Consolidations:Update:All Consolidation:AllConsolidationUpdate","all-consolidationUpdate"),
            Map.entry("Consolidations:Update:Rail Consolidation:ImportRailConsolidationUpdate","rail-imp-consolidationUpdate"),
            Map.entry("Consolidations:Update:Rail Consolidation:ExportRailConsolidationUpdate","rail-exp-consolidationUpdate"),
            Map.entry("Consolidations:Update:Rail Consolidation:ReshipmentRailConsolidationUpdate","rail-res-consolidationUpdate"),
            Map.entry("Consolidations:Update:Rail Consolidation:TranshipmentRailConsolidationUpdate","rail-tra-consolidationUpdate"),
            Map.entry("Consolidations:Update:Rail Consolidation:EmptyContainerRailConsolidationUpdate","rail-emt-consolidationUpdate"),
            Map.entry("Consolidations:Update:Rail Consolidation:DomesticRailConsolidationUpdate","rail-dom-consolidationUpdate"),
            Map.entry("Consolidations:Update:Rail Consolidation:CrossTradeRailConsolidationUpdate","rail-cts-consolidationUpdate"),
            Map.entry("Consolidations:Update:Rail Consolidation:AllRailConsolidationUpdate","rail-consolidationUpdate"),
            Map.entry("Consolidations:Update:Road Consolidation:ImportRoadConsolidationUpdate","road-imp-consolidationUpdate"),
            Map.entry("Consolidations:Update:Road Consolidation:ExportRoadConsolidationUpdate","road-exp-consolidationUpdate"),
            Map.entry("Consolidations:Update:Road Consolidation:ReshipmentRoadConsolidationUpdate","road-res-consolidationUpdate"),
            Map.entry("Consolidations:Update:Road Consolidation:TranshipmentRoadConsolidationUpdate","road-tra-consolidationUpdate"),
            Map.entry("Consolidations:Update:Road Consolidation:EmptyContainerRoadConsolidationUpdate","road-emt-consolidationUpdate"),
            Map.entry("Consolidations:Update:Road Consolidation:DomesticRoadConsolidationUpdate","road-dom-consolidationUpdate"),
            Map.entry("Consolidations:Update:Road Consolidation:CrossTradeRoadConsolidationUpdate","road-cts-consolidationUpdate"),
            Map.entry("Consolidations:Update:Road Consolidation:AllRoadConsolidationUpdate","road-consolidationUpdate"),
            Map.entry("Consolidations:Update:Sea Consolidation:ImportSeaConsolidationUpdate","sea-imp-consolidationUpdate"),
            Map.entry("Consolidations:Update:Sea Consolidation:ExportSeaConsolidationUpdate","sea-exp-consolidationUpdate"),
            Map.entry("Consolidations:Update:Sea Consolidation:ReshipmentSeaConsolidationUpdate","sea-res-consolidationUpdate"),
            Map.entry("Consolidations:Update:Sea Consolidation:TranshipmentSeaConsolidationUpdate","sea-tra-consolidationUpdate"),
            Map.entry("Consolidations:Update:Sea Consolidation:EmptyContainerSeaConsolidationUpdate","sea-emt-consolidationUpdate"),
            Map.entry("Consolidations:Update:Sea Consolidation:DomesticSeaConsolidationUpdate","sea-dom-consolidationUpdate"),
            Map.entry("Consolidations:Update:Sea Consolidation:CrossTradeSeaConsolidationUpdate","sea-cts-consolidationUpdate"),
            Map.entry("Consolidations:Update:Sea Consolidation:AllSeaConsolidationUpdate","sea-consolidationUpdate")
    );

    public static String getPermissionName(String v1Permission){
        return v1PermissionMapping.get(v1Permission);
    }
}
