package com.dpw.runner.shipment.services.utils;

import java.util.*;

public class V1PermissionMapUtil {
    private static final Map<String, String> v1PermissionMapping = Map.ofEntries(
            // SHIPMENT LIST PERMISSION MAPPINGS
            Map.entry("Shipments:List:Air Shipment:ImportAirShipmentList", "air-imp-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:ExportAirShipmentList", "air-exp-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:ReshipmentAirShipmentList", "air-res-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:TranshipmentAirShipmentList", "air-tra-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:EmptyContainerAirShipmentList", "air-cts-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:DomesticAirShipmentList", "air-dom-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:CrossTradeAirShipmentList", "air-cts-all-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:AllAirShipmentList", "air-shipmentList"),
            Map.entry("Shipments:List:All Shipment:ImportAllShipmentList", "all-imp-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:ExportAllShipmentList", "all-exp-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:ReshipmentAllShipmentList", "all-res-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:TranshipmentAllShipmentList", "all-tra-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:EmptyContainerAllShipmentList", "all-emt-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:DomesticAllShipmentList", "all-dom-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:CrossTradeAllShipmentList", "all-cts-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:AllShipmentList", "all-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:ImportRailShipmentList", "rai-imp-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:ExportRailShipmentList", "rai-exp-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:ReshipmentRailShipmentList", "rai-res-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:TranshipmentRailShipmentList", "rai-tra-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:EmptyContainerRailShipmentList", "rai-emt-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:DomesticRailShipmentList", "rai-dom-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:CrossTradeRailShipmentList", "rai-cts-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:AllRailShipmentList", "rai-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:ImportRoadShipmentList", "roa-imp-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:ExportRoadShipmentList", "roa-exp-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:ReshipmentRoadShipmentList", "roa-res-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:TranshipmentRoadShipmentList", "roa-tra-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:EmptyContainerRoadShipmentList", "roa-emt-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:DomesticRoadShipmentList", "roa-dom-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:CrossTradeRoadShipmentList", "roa-cts-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:AllRoadShipmentList", "roa-shipmentList"),
            // IsDomestic flag
            Map.entry("Shipments:List:Sea International Shipment:ImportSeaShipmentList", "sea-imp-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:ExportSeaShipmentList", "sea-exp-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:ReshipmentSeaShipmentList", "sea-res-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:TranshipmentSeaShipmentList", "sea-tra-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:EmptyContainerSeaShipmentList", "sea-emt-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:DomesticSeaShipmentList", "sea-dom-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:CrossTradeSeaShipmentList", "sea-cts-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:AllSeaShipmentList", "sea-all-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:ImportDomesticSeaShipmentList", "sea-imp-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:ExportDomesticSeaShipmentList", "sea-exp-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:ReshipmentDomesticSeaShipmentList", "sea-res-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:TranshipmentDomesticSeaShipmentList", "sea-tra-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:EmptyContainerDomesticSeaShipmentList", "sea-emt-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:DomesticDomesticSeaShipmentList", "sea-dom-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:CrossTradeDomesticSeaShipmentList", "sea-cts-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:AllDomesticSeaShipmentList", "sea-all-all-domestic-shipmentList"),

            // SHIPMENT RETRIEVE PERMISSIONS MAPPING
            Map.entry("Shipments:Retrive:Air Shipment:ImportAirShipmentRetrive", "air-imp-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:ExportAirShipmentRetrive", "air-exp-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:ReshipmentAirShipmentRetrive", "air-res-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:TranshipmentAirShipmentRetrive", "air-tra-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:EmptyContainerAirShipmentRetrive", "air-cts-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:DomesticAirShipmentRetrive", "air-dom-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:CrossTradeAirShipmentRetrive", "air-cts-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:AllAirShipmentRetrive", "air-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:ImportAllShipmentRetrive", "all-imp-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:ExportAllShipmentRetrive", "all-exp-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:ReshipmentAllShipmentRetrive", "all-res-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:TranshipmentAllShipmentRetrive", "all-tra-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:EmptyContainerAllShipmentRetrive", "all-emt-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:DomesticAllShipmentRetrive", "all-dom-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:CrossTradeAllShipmentRetrive", "all-cts-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:AllShipmentRetrive", "all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:ImportRailShipmentRetrive", "rai-imp-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:ExportRailShipmentRetrive", "rai-exp-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:ReshipmentRailShipmentRetrive", "rai-res-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:TranshipmentRailShipmentRetrive", "rai-tra-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:EmptyContainerRailShipmentRetrive", "rai-emt-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:DomesticRailShipmentRetrive", "rai-dom-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:CrossTradeRailShipmentRetrive", "rai-cts-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:AllRailShipmentRetrive", "rai-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:ImportRoadShipmentRetrive", "roa-imp-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:ExportRoadShipmentRetrive", "roa-exp-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:ReshipmentRoadShipmentRetrive", "roa-res-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:TranshipmentRoadShipmentRetrive", "roa-tra-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:EmptyContainerRoadShipmentRetrive", "roa-emt-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:DomesticRoadShipmentRetrive", "roa-dom-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:CrossTradeRoadShipmentRetrive", "roa-cts-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:AllRoadShipmentRetrive", "roa-shipmentRetrieve"),
            // IsDomestic flag
            Map.entry("Shipments:Retrive:Sea International Shipment:ImportSeaShipmentRetrive", "sea-imp-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:ExportSeaShipmentRetrive", "sea-exp-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:ReshipmentSeaShipmentRetrive", "sea-res-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:TranshipmentSeaShipmentRetrive", "sea-tra-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:EmptyContainerSeaShipmentRetrive", "sea-emt-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:DomesticSeaShipmentRetrive", "sea-dom-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:CrossTradeSeaShipmentRetrive", "sea-cts-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:AllSeaShipmentRetrive", "sea-all-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:ImportDomesticSeaShipmentRetrive", "sea-imp-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:ExportDomesticSeaShipmentRetrive", "sea-exp-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:ReshipmentDomesticSeaShipmentRetrive", "sea-res-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:TranshipmentDomesticSeaShipmentRetrive", "sea-tra-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:EmptyContainerDomesticSeaShipmentRetrive", "sea-emt-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:DomesticDomesticSeaShipmentRetrive", "sea-dom-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:CrossTradeDomesticSeaShipmentRetrive", "sea-cts-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:AllDomesticSeaShipmentRetrive", "sea-all-all-domestic-shipmentRetrieve"),

            // SHIPMENT CREATE PERMISSION MAPPINGS
            Map.entry("Shipments:Creation:Air Shipment:ImportAirShipmentCreate", "air-imp-shipmentCreate"),
            Map.entry("Shipments:Creation:Air Shipment:ExportAirShipmentCreate", "air-exp-shipmentCreate"),
            Map.entry("Shipments:Creation:Air Shipment:ReshipmentAirShipmentCreate", "air-res-shipmentCreate"),
            Map.entry("Shipments:Creation:Air Shipment:TranshipmentAirShipmentCreate", "air-tra-shipmentCreate"),
            Map.entry("Shipments:Creation:Air Shipment:EmptyContainerAirShipmentCreate", "air-cts-shipmentCreate"),
            Map.entry("Shipments:Creation:Air Shipment:DomesticAirShipmentCreate", "air-dom-shipmentCreate"),
            Map.entry("Shipments:Creation:Air Shipment:CrossTradeAirShipmentCreate", "air-cts-all-shipmentCreate"),
            Map.entry("Shipments:Creation:Air Shipment:AllAirShipmentCreate", "air-shipmentCreate"),
            Map.entry("Shipments:Creation:All Shipment:ImportAllShipmentCreate", "all-imp-all-shipmentCreate"),
            Map.entry("Shipments:Creation:All Shipment:ExportAllShipmentCreate", "all-exp-all-shipmentCreate"),
            Map.entry("Shipments:Creation:All Shipment:ReshipmentAllShipmentCreate", "all-res-all-shipmentCreate"),
            Map.entry("Shipments:Creation:All Shipment:TranshipmentAllShipmentCreate", "all-tra-all-shipmentCreate"),
            Map.entry("Shipments:Creation:All Shipment:EmptyContainerAllShipmentCreate", "all-emt-all-shipmentCreate"),
            Map.entry("Shipments:Creation:All Shipment:DomesticAllShipmentCreate", "all-dom-all-shipmentCreate"),
            Map.entry("Shipments:Creation:All Shipment:CrossTradeAllShipmentCreate", "all-cts-all-shipmentCreate"),
            Map.entry("Shipments:Creation:All Shipment:AllShipmentCreate", "all-shipmentCreate"),
            Map.entry("Shipments:Creation:Rail Shipment:ImportRailShipmentCreate", "rai-imp-shipmentCreate"),
            Map.entry("Shipments:Creation:Rail Shipment:ExportRailShipmentCreate", "rai-exp-shipmentCreate"),
            Map.entry("Shipments:Creation:Rail Shipment:ReshipmentRailShipmentCreate", "rai-res-shipmentCreate"),
            Map.entry("Shipments:Creation:Rail Shipment:TranshipmentRailShipmentCreate", "rai-tra-shipmentCreate"),
            Map.entry("Shipments:Creation:Rail Shipment:EmptyContainerRailShipmentCreate", "rai-emt-shipmentCreate"),
            Map.entry("Shipments:Creation:Rail Shipment:DomesticRailShipmentCreate", "rai-dom-shipmentCreate"),
            Map.entry("Shipments:Creation:Rail Shipment:CrossTradeRailShipmentCreate", "rai-cts-shipmentCreate"),
            Map.entry("Shipments:Creation:Rail Shipment:AllRailShipmentCreate", "rai-shipmentCreate"),
            Map.entry("Shipments:Creation:Road Shipment:ImportRoadShipmentCreate", "roa-imp-shipmentCreate"),
            Map.entry("Shipments:Creation:Road Shipment:ExportRoadShipmentCreate", "roa-exp-shipmentCreate"),
            Map.entry("Shipments:Creation:Road Shipment:ReshipmentRoadShipmentCreate", "roa-res-shipmentCreate"),
            Map.entry("Shipments:Creation:Road Shipment:TranshipmentRoadShipmentCreate", "roa-tra-shipmentCreate"),
            Map.entry("Shipments:Creation:Road Shipment:EmptyContainerRoadShipmentCreate", "roa-emt-shipmentCreate"),
            Map.entry("Shipments:Creation:Road Shipment:DomesticRoadShipmentCreate", "roa-dom-shipmentCreate"),
            Map.entry("Shipments:Creation:Road Shipment:CrossTradeRoadShipmentCreate", "roa-cts-shipmentCreate"),
            Map.entry("Shipments:Creation:Road Shipment:AllRoadShipmentCreate", "roa-shipmentCreate"),
            // IsDomestic flag
            Map.entry("Shipments:Creation:Sea International Shipment:ImportSeaShipmentCreate", "sea-imp-all-international-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea International Shipment:ExportSeaShipmentCreate", "sea-exp-all-international-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea International Shipment:ReshipmentSeaShipmentCreate", "sea-res-all-international-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea International Shipment:TranshipmentSeaShipmentCreate", "sea-tra-all-international-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea International Shipment:EmptyContainerSeaShipmentCreate", "sea-emt-all-international-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea International Shipment:DomesticSeaShipmentCreate", "sea-dom-all-international-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea International Shipment:CrossTradeSeaShipmentCreate", "sea-cts-all-international-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea International Shipment:AllSeaShipmentCreate", "sea-all-all-international-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea Domestic Shipment:ImportDomesticSeaShipmentCreate", "sea-imp-all-domestic-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea Domestic Shipment:ExportDomesticSeaShipmentCreate", "sea-exp-all-domestic-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea Domestic Shipment:ReshipmentDomesticSeaShipmentCreate", "sea-res-all-domestic-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea Domestic Shipment:TranshipmentDomesticSeaShipmentCreate", "sea-tra-all-domestic-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea Domestic Shipment:EmptyContainerDomesticSeaShipmentCreate", "sea-emt-all-domestic-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea Domestic Shipment:DomesticDomesticSeaShipmentCreate", "sea-dom-all-domestic-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea Domestic Shipment:CrossTradeDomesticSeaShipmentCreate", "sea-cts-all-domestic-shipmentCreate"),
            Map.entry("Shipments:Creation:Sea Domestic Shipment:AllDomesticSeaShipmentCreate", "sea-all-all-domestic-shipmentCreate"),

            // SHIPMENT UPDATE PERMISSIONS MAPPING
            Map.entry("Shipments:Update:Air Shipment:ImportAirShipmentUpdate", "air-imp-shipmentUpdate"),
            Map.entry("Shipments:Update:Air Shipment:ExportAirShipmentUpdate", "air-exp-shipmentUpdate"),
            Map.entry("Shipments:Update:Air Shipment:ReshipmentAirShipmentUpdate", "air-res-shipmentUpdate"),
            Map.entry("Shipments:Update:Air Shipment:TranshipmentAirShipmentUpdate", "air-tra-shipmentUpdate"),
            Map.entry("Shipments:Update:Air Shipment:EmptyContainerAirShipmentUpdate", "air-cts-shipmentUpdate"),
            Map.entry("Shipments:Update:Air Shipment:DomesticAirShipmentUpdate", "air-dom-shipmentUpdate"),
            Map.entry("Shipments:Update:Air Shipment:CrossTradeAirShipmentUpdate", "air-cts-all-shipmentUpdate"),
            Map.entry("Shipments:Update:Air Shipment:AllAirShipmentUpdate", "air-shipmentUpdate"),
            Map.entry("Shipments:Update:All Shipment:ImportAllShipmentUpdate", "all-imp-all-shipmentUpdate"),
            Map.entry("Shipments:Update:All Shipment:ExportAllShipmentUpdate", "all-exp-all-shipmentUpdate"),
            Map.entry("Shipments:Update:All Shipment:ReshipmentAllShipmentUpdate", "all-res-all-shipmentUpdate"),
            Map.entry("Shipments:Update:All Shipment:TranshipmentAllShipmentUpdate", "all-tra-all-shipmentUpdate"),
            Map.entry("Shipments:Update:All Shipment:EmptyContainerAllShipmentUpdate", "all-emt-all-shipmentUpdate"),
            Map.entry("Shipments:Update:All Shipment:DomesticAllShipmentUpdate", "all-dom-all-shipmentUpdate"),
            Map.entry("Shipments:Update:All Shipment:CrossTradeAllShipmentUpdate", "all-cts-all-shipmentUpdate"),
            Map.entry("Shipments:Update:All Shipment:AllShipmentUpdate", "all-shipmentUpdate"),
            Map.entry("Shipments:Update:Rail Shipment:ImportRailShipmentUpdate", "rai-imp-shipmentUpdate"),
            Map.entry("Shipments:Update:Rail Shipment:ExportRailShipmentUpdate", "rai-exp-shipmentUpdate"),
            Map.entry("Shipments:Update:Rail Shipment:ReshipmentRailShipmentUpdate", "rai-res-shipmentUpdate"),
            Map.entry("Shipments:Update:Rail Shipment:TranshipmentRailShipmentUpdate", "rai-tra-shipmentUpdate"),
            Map.entry("Shipments:Update:Rail Shipment:EmptyContainerRailShipmentUpdate", "rai-emt-shipmentUpdate"),
            Map.entry("Shipments:Update:Rail Shipment:DomesticRailShipmentUpdate", "rai-dom-shipmentUpdate"),
            Map.entry("Shipments:Update:Rail Shipment:CrossTradeRailShipmentUpdate", "rai-cts-shipmentUpdate"),
            Map.entry("Shipments:Update:Rail Shipment:AllRailShipmentUpdate", "rai-shipmentUpdate"),
            Map.entry("Shipments:Update:Road Shipment:ImportRoadShipmentUpdate", "roa-imp-shipmentUpdate"),
            Map.entry("Shipments:Update:Road Shipment:ExportRoadShipmentUpdate", "roa-exp-shipmentUpdate"),
            Map.entry("Shipments:Update:Road Shipment:ReshipmentRoadShipmentUpdate", "roa-res-shipmentUpdate"),
            Map.entry("Shipments:Update:Road Shipment:TranshipmentRoadShipmentUpdate", "roa-tra-shipmentUpdate"),
            Map.entry("Shipments:Update:Road Shipment:EmptyContainerRoadShipmentUpdate", "roa-emt-shipmentUpdate"),
            Map.entry("Shipments:Update:Road Shipment:DomesticRoadShipmentUpdate", "roa-dom-shipmentUpdate"),
            Map.entry("Shipments:Update:Road Shipment:CrossTradeRoadShipmentUpdate", "roa-cts-shipmentUpdate"),
            Map.entry("Shipments:Update:Road Shipment:AllRoadShipmentUpdate", "roa-shipmentUpdate"),
            // IsDomestic flag
            Map.entry("Shipments:Update:Sea International Shipment:ImportSeaShipmentUpdate", "sea-imp-all-international-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea International Shipment:ExportSeaShipmentUpdate", "sea-exp-all-international-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea International Shipment:ReshipmentSeaShipmentUpdate", "sea-res-all-international-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea International Shipment:TranshipmentSeaShipmentUpdate", "sea-tra-all-international-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea International Shipment:EmptyContainerSeaShipmentUpdate", "sea-emt-all-international-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea International Shipment:DomesticSeaShipmentUpdate", "sea-dom-all-international-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea International Shipment:CrossTradeSeaShipmentUpdate", "sea-cts-all-international-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea International Shipment:AllSeaShipmentUpdate", "sea-all-all-international-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea Domestic Shipment:ImportDomesticSeaShipmentUpdate", "sea-imp-all-domestic-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea Domestic Shipment:ExportDomesticSeaShipmentUpdate", "sea-exp-all-domestic-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea Domestic Shipment:ReshipmentDomesticSeaShipmentUpdate", "sea-res-all-domestic-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea Domestic Shipment:TranshipmentDomesticSeaShipmentUpdate", "sea-tra-all-domestic-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea Domestic Shipment:EmptyContainerDomesticSeaShipmentUpdate", "sea-emt-all-domestic-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea Domestic Shipment:DomesticDomesticSeaShipmentUpdate", "sea-dom-all-domestic-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea Domestic Shipment:CrossTradeDomesticSeaShipmentUpdate", "sea-cts-all-domestic-shipmentUpdate"),
            Map.entry("Shipments:Update:Sea Domestic Shipment:AllDomesticSeaShipmentUpdate", "sea-all-all-domestic-shipmentUpdate"),

            // CONSOLIDATION LIST PERMISSION MAPPINGS
            Map.entry("Consolidations:List:Air Consolidation:ImportAirConsolidationList", "air-imp-consolidationList"),
            Map.entry("Consolidations:List:Air Consolidation:ExportAirConsolidationList", "air-exp-consolidationList"),
            Map.entry("Consolidations:List:Air Consolidation:ReshipmentAirConsolidationList", "air-res-consolidationList"),
            Map.entry("Consolidations:List:Air Consolidation:TranshipmentAirConsolidationList", "air-tra-consolidationList"),
            Map.entry("Consolidations:List:Air Consolidation:EmptyContainerAirConsolidationList", "air-cts-consolidationList"),
            Map.entry("Consolidations:List:Air Consolidation:DomesticAirConsolidationList", "air-dom-consolidationList"),
            Map.entry("Consolidations:List:Air Consolidation:CrossTradeAirConsolidationList", "air-cts-all-consolidationList"),
            Map.entry("Consolidations:List:Air Consolidation:AllAirConsolidationList", "air-consolidationList"),
            Map.entry("Consolidations:List:All Consolidation:ImportAllConsolidationList", "all-imp-all-consolidationList"),
            Map.entry("Consolidations:List:All Consolidation:ExportAllConsolidationList", "all-exp-all-consolidationList"),
            Map.entry("Consolidations:List:All Consolidation:ReshipmentAllConsolidationList", "all-res-all-consolidationList"),
            Map.entry("Consolidations:List:All Consolidation:TranshipmentAllConsolidationList", "all-tra-all-consolidationList"),
            Map.entry("Consolidations:List:All Consolidation:EmptyContainerAllConsolidationList", "all-emt-all-consolidationList"),
            Map.entry("Consolidations:List:All Consolidation:DomesticAllConsolidationList", "all-dom-all-consolidationList"),
            Map.entry("Consolidations:List:All Consolidation:CrossTradeAllConsolidationList", "all-cts-all-consolidationList"),
            Map.entry("Consolidations:List:All Consolidation:AllConsolidationList", "all-consolidationList"),
            Map.entry("Consolidations:List:Rail Consolidation:ImportRailConsolidationList", "rai-imp-consolidationList"),
            Map.entry("Consolidations:List:Rail Consolidation:ExportRailConsolidationList", "rai-exp-consolidationList"),
            Map.entry("Consolidations:List:Rail Consolidation:ReshipmentRailConsolidationList", "rai-res-consolidationList"),
            Map.entry("Consolidations:List:Rail Consolidation:TranshipmentRailConsolidationList", "rai-tra-consolidationList"),
            Map.entry("Consolidations:List:Rail Consolidation:EmptyContainerRailConsolidationList", "rai-emt-consolidationList"),
            Map.entry("Consolidations:List:Rail Consolidation:DomesticRailConsolidationList", "rai-dom-consolidationList"),
            Map.entry("Consolidations:List:Rail Consolidation:CrossTradeRailConsolidationList", "rai-cts-consolidationList"),
            Map.entry("Consolidations:List:Rail Consolidation:AllRailConsolidationList", "rai-consolidationList"),
            Map.entry("Consolidations:List:Road Consolidation:ImportRoadConsolidationList", "roa-imp-consolidationList"),
            Map.entry("Consolidations:List:Road Consolidation:ExportRoadConsolidationList", "roa-exp-consolidationList"),
            Map.entry("Consolidations:List:Road Consolidation:ReshipmentRoadConsolidationList", "roa-res-consolidationList"),
            Map.entry("Consolidations:List:Road Consolidation:TranshipmentRoadConsolidationList", "roa-tra-consolidationList"),
            Map.entry("Consolidations:List:Road Consolidation:EmptyContainerRoadConsolidationList", "roa-emt-consolidationList"),
            Map.entry("Consolidations:List:Road Consolidation:DomesticRoadConsolidationList", "roa-dom-consolidationList"),
            Map.entry("Consolidations:List:Road Consolidation:CrossTradeRoadConsolidationList", "roa-cts-consolidationList"),
            Map.entry("Consolidations:List:Road Consolidation:AllRoadConsolidationList", "roa-consolidationList"),
            Map.entry("Consolidations:List:Sea Consolidation:ImportSeaConsolidationList", "sea-imp-consolidationList"),
            Map.entry("Consolidations:List:Sea Consolidation:ExportSeaConsolidationList", "sea-exp-consolidationList"),
            Map.entry("Consolidations:List:Sea Consolidation:ReshipmentSeaConsolidationList", "sea-res-consolidationList"),
            Map.entry("Consolidations:List:Sea Consolidation:TranshipmentSeaConsolidationList", "sea-tra-consolidationList"),
            Map.entry("Consolidations:List:Sea Consolidation:EmptyContainerSeaConsolidationList", "sea-emt-consolidationList"),
            Map.entry("Consolidations:List:Sea Consolidation:DomesticSeaConsolidationList", "sea-dom-consolidationList"),
            Map.entry("Consolidations:List:Sea Consolidation:CrossTradeSeaConsolidationList", "sea-cts-consolidationList"),
            Map.entry("Consolidations:List:Sea Consolidation:AllSeaConsolidationList", "sea-consolidationList"),

            // CONSOLIDATION RETRIEVE PERMISSIONS MAPPING
            Map.entry("Consolidations:Retrive:Air Consolidation:ImportAirConsolidationRetrive", "air-imp-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Air Consolidation:ExportAirConsolidationRetrive", "air-exp-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Air Consolidation:ReshipmentAirConsolidationRetrive", "air-res-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Air Consolidation:TranshipmentAirConsolidationRetrive", "air-tra-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Air Consolidation:EmptyContainerAirConsolidationRetrive", "air-cts-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Air Consolidation:DomesticAirConsolidationRetrive", "air-dom-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Air Consolidation:CrossTradeAirConsolidationRetrive", "air-cts-all-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Air Consolidation:AllAirConsolidationRetrive", "air-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:All Consolidation:ImportAllConsolidationRetrive", "all-imp-all-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:All Consolidation:ExportAllConsolidationRetrive", "all-exp-all-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:All Consolidation:ReshipmentAllConsolidationRetrive", "all-res-all-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:All Consolidation:TranshipmentAllConsolidationRetrive", "all-tra-all-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:All Consolidation:EmptyContainerAllConsolidationRetrive", "all-emt-all-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:All Consolidation:DomesticAllConsolidationRetrive", "all-dom-all-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:All Consolidation:CrossTradeAllConsolidationRetrive", "all-cts-all-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:All Consolidation:AllConsolidationRetrive", "all-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Rail Consolidation:ImportRailConsolidationRetrive", "rai-imp-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Rail Consolidation:ExportRailConsolidationRetrive", "rai-exp-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Rail Consolidation:ReshipmentRailConsolidationRetrive", "rai-res-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Rail Consolidation:TranshipmentRailConsolidationRetrive", "rai-tra-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Rail Consolidation:EmptyContainerRailConsolidationRetrive", "rai-emt-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Rail Consolidation:DomesticRailConsolidationRetrive", "rai-dom-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Rail Consolidation:CrossTradeRailConsolidationRetrive", "rai-cts-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Rail Consolidation:AllRailConsolidationRetrive", "rai-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Road Consolidation:ImportRoadConsolidationRetrive", "roa-imp-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Road Consolidation:ExportRoadConsolidationRetrive", "roa-exp-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Road Consolidation:ReshipmentRoadConsolidationRetrive", "roa-res-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Road Consolidation:TranshipmentRoadConsolidationRetrive", "roa-tra-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Road Consolidation:EmptyContainerRoadConsolidationRetrive", "roa-emt-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Road Consolidation:DomesticRoadConsolidationRetrive", "roa-dom-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Road Consolidation:CrossTradeRoadConsolidationRetrive", "roa-cts-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Road Consolidation:AllRoadConsolidationRetrive", "roa-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Sea Consolidation:ImportSeaConsolidationRetrive", "sea-imp-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Sea Consolidation:ExportSeaConsolidationRetrive", "sea-exp-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Sea Consolidation:ReshipmentSeaConsolidationRetrive", "sea-res-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Sea Consolidation:TranshipmentSeaConsolidationRetrive", "sea-tra-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Sea Consolidation:EmptyContainerSeaConsolidationRetrive", "sea-emt-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Sea Consolidation:DomesticSeaConsolidationRetrive", "sea-dom-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Sea Consolidation:CrossTradeSeaConsolidationRetrive", "sea-cts-consolidationRetrieve"),
            Map.entry("Consolidations:Retrive:Sea Consolidation:AllSeaConsolidationRetrive", "sea-consolidationRetrieve"),

            // CONSOLIDATION CREATE PERMISSION MAPPINGS
            Map.entry("Consolidations:Creation:Air Consolidation:ImportAirConsolidationCreate", "air-imp-consolidationCreate"),
            Map.entry("Consolidations:Creation:Air Consolidation:ExportAirConsolidationCreate", "air-exp-consolidationCreate"),
            Map.entry("Consolidations:Creation:Air Consolidation:ReshipmentAirConsolidationCreate", "air-res-consolidationCreate"),
            Map.entry("Consolidations:Creation:Air Consolidation:TranshipmentAirConsolidationCreate", "air-tra-consolidationCreate"),
            Map.entry("Consolidations:Creation:Air Consolidation:EmptyContainerAirConsolidationCreate", "air-cts-consolidationCreate"),
            Map.entry("Consolidations:Creation:Air Consolidation:DomesticAirConsolidationCreate", "air-dom-consolidationCreate"),
            Map.entry("Consolidations:Creation:Air Consolidation:CrossTradeAirConsolidationCreate", "air-cts-all-consolidationCreate"),
            Map.entry("Consolidations:Creation:Air Consolidation:AllAirConsolidationCreate", "air-consolidationCreate"),
            Map.entry("Consolidations:Creation:All Consolidation:ImportAllConsolidationCreate", "all-imp-all-consolidationCreate"),
            Map.entry("Consolidations:Creation:All Consolidation:ExportAllConsolidationCreate", "all-exp-all-consolidationCreate"),
            Map.entry("Consolidations:Creation:All Consolidation:ReshipmentAllConsolidationCreate", "all-res-all-consolidationCreate"),
            Map.entry("Consolidations:Creation:All Consolidation:TranshipmentAllConsolidationCreate", "all-tra-all-consolidationCreate"),
            Map.entry("Consolidations:Creation:All Consolidation:EmptyContainerAllConsolidationCreate", "all-emt-all-consolidationCreate"),
            Map.entry("Consolidations:Creation:All Consolidation:DomesticAllConsolidationCreate", "all-dom-all-consolidationCreate"),
            Map.entry("Consolidations:Creation:All Consolidation:CrossTradeAllConsolidationCreate", "all-cts-all-consolidationCreate"),
            Map.entry("Consolidations:Creation:All Consolidation:AllConsolidationCreate", "all-consolidationCreate"),
            Map.entry("Consolidations:Creation:Rail Consolidation:ImportRailConsolidationCreate", "rai-imp-consolidationCreate"),
            Map.entry("Consolidations:Creation:Rail Consolidation:ExportRailConsolidationCreate", "rai-exp-consolidationCreate"),
            Map.entry("Consolidations:Creation:Rail Consolidation:ReshipmentRailConsolidationCreate", "rai-res-consolidationCreate"),
            Map.entry("Consolidations:Creation:Rail Consolidation:TranshipmentRailConsolidationCreate", "rai-tra-consolidationCreate"),
            Map.entry("Consolidations:Creation:Rail Consolidation:EmptyContainerRailConsolidationCreate", "rai-emt-consolidationCreate"),
            Map.entry("Consolidations:Creation:Rail Consolidation:DomesticRailConsolidationCreate", "rai-dom-consolidationCreate"),
            Map.entry("Consolidations:Creation:Rail Consolidation:CrossTradeRailConsolidationCreate", "rai-cts-consolidationCreate"),
            Map.entry("Consolidations:Creation:Rail Consolidation:AllRailConsolidationCreate", "rai-consolidationCreate"),
            Map.entry("Consolidations:Creation:Road Consolidation:ImportRoadConsolidationCreate", "roa-imp-consolidationCreate"),
            Map.entry("Consolidations:Creation:Road Consolidation:ExportRoadConsolidationCreate", "roa-exp-consolidationCreate"),
            Map.entry("Consolidations:Creation:Road Consolidation:ReshipmentRoadConsolidationCreate", "roa-res-consolidationCreate"),
            Map.entry("Consolidations:Creation:Road Consolidation:TranshipmentRoadConsolidationCreate", "roa-tra-consolidationCreate"),
            Map.entry("Consolidations:Creation:Road Consolidation:EmptyContainerRoadConsolidationCreate", "roa-emt-consolidationCreate"),
            Map.entry("Consolidations:Creation:Road Consolidation:DomesticRoadConsolidationCreate", "roa-dom-consolidationCreate"),
            Map.entry("Consolidations:Creation:Road Consolidation:CrossTradeRoadConsolidationCreate", "roa-cts-consolidationCreate"),
            Map.entry("Consolidations:Creation:Road Consolidation:AllRoadConsolidationCreate", "roa-consolidationCreate"),
            Map.entry("Consolidations:Creation:Sea Consolidation:ImportSeaConsolidationCreate", "sea-imp-consolidationCreate"),
            Map.entry("Consolidations:Creation:Sea Consolidation:ExportSeaConsolidationCreate", "sea-exp-consolidationCreate"),
            Map.entry("Consolidations:Creation:Sea Consolidation:ReshipmentSeaConsolidationCreate", "sea-res-consolidationCreate"),
            Map.entry("Consolidations:Creation:Sea Consolidation:TranshipmentSeaConsolidationCreate", "sea-tra-consolidationCreate"),
            Map.entry("Consolidations:Creation:Sea Consolidation:EmptyContainerSeaConsolidationCreate", "sea-emt-consolidationCreate"),
            Map.entry("Consolidations:Creation:Sea Consolidation:DomesticSeaConsolidationCreate", "sea-dom-consolidationCreate"),
            Map.entry("Consolidations:Creation:Sea Consolidation:CrossTradeSeaConsolidationCreate", "sea-cts-consolidationCreate"),
            Map.entry("Consolidations:Creation:Sea Consolidation:AllSeaConsolidationCreate", "sea-consolidationCreate"),

            // CONSOLIDATION UPDATE PERMISSIONS MAPPING
            Map.entry("Consolidations:Update:Air Consolidation:ImportAirConsolidationUpdate", "air-imp-consolidationUpdate"),
            Map.entry("Consolidations:Update:Air Consolidation:ExportAirConsolidationUpdate", "air-exp-consolidationUpdate"),
            Map.entry("Consolidations:Update:Air Consolidation:ReshipmentAirConsolidationUpdate", "air-res-consolidationUpdate"),
            Map.entry("Consolidations:Update:Air Consolidation:TranshipmentAirConsolidationUpdate", "air-tra-consolidationUpdate"),
            Map.entry("Consolidations:Update:Air Consolidation:EmptyContainerAirConsolidationUpdate", "air-cts-consolidationUpdate"),
            Map.entry("Consolidations:Update:Air Consolidation:DomesticAirConsolidationUpdate", "air-dom-consolidationUpdate"),
            Map.entry("Consolidations:Update:Air Consolidation:CrossTradeAirConsolidationUpdate", "air-cts-all-consolidationUpdate"),
            Map.entry("Consolidations:Update:Air Consolidation:AllAirConsolidationUpdate", "air-consolidationUpdate"),
            Map.entry("Consolidations:Update:All Consolidation:ImportAllConsolidationUpdate", "all-imp-all-consolidationUpdate"),
            Map.entry("Consolidations:Update:All Consolidation:ExportAllConsolidationUpdate", "all-exp-all-consolidationUpdate"),
            Map.entry("Consolidations:Update:All Consolidation:ReshipmentAllConsolidationUpdate", "all-res-all-consolidationUpdate"),
            Map.entry("Consolidations:Update:All Consolidation:TranshipmentAllConsolidationUpdate", "all-tra-all-consolidationUpdate"),
            Map.entry("Consolidations:Update:All Consolidation:EmptyContainerAllConsolidationUpdate", "all-emt-all-consolidationUpdate"),
            Map.entry("Consolidations:Update:All Consolidation:DomesticAllConsolidationUpdate", "all-dom-all-consolidationUpdate"),
            Map.entry("Consolidations:Update:All Consolidation:CrossTradeAllConsolidationUpdate", "all-cts-all-consolidationUpdate"),
            Map.entry("Consolidations:Update:All Consolidation:AllConsolidationUpdate", "all-consolidationUpdate"),
            Map.entry("Consolidations:Update:Rail Consolidation:ImportRailConsolidationUpdate", "rai-imp-consolidationUpdate"),
            Map.entry("Consolidations:Update:Rail Consolidation:ExportRailConsolidationUpdate", "rai-exp-consolidationUpdate"),
            Map.entry("Consolidations:Update:Rail Consolidation:ReshipmentRailConsolidationUpdate", "rai-res-consolidationUpdate"),
            Map.entry("Consolidations:Update:Rail Consolidation:TranshipmentRailConsolidationUpdate", "rai-tra-consolidationUpdate"),
            Map.entry("Consolidations:Update:Rail Consolidation:EmptyContainerRailConsolidationUpdate", "rai-emt-consolidationUpdate"),
            Map.entry("Consolidations:Update:Rail Consolidation:DomesticRailConsolidationUpdate", "rai-dom-consolidationUpdate"),
            Map.entry("Consolidations:Update:Rail Consolidation:CrossTradeRailConsolidationUpdate", "rai-cts-consolidationUpdate"),
            Map.entry("Consolidations:Update:Rail Consolidation:AllRailConsolidationUpdate", "rai-consolidationUpdate"),
            Map.entry("Consolidations:Update:Road Consolidation:ImportRoadConsolidationUpdate", "roa-imp-consolidationUpdate"),
            Map.entry("Consolidations:Update:Road Consolidation:ExportRoadConsolidationUpdate", "roa-exp-consolidationUpdate"),
            Map.entry("Consolidations:Update:Road Consolidation:ReshipmentRoadConsolidationUpdate", "roa-res-consolidationUpdate"),
            Map.entry("Consolidations:Update:Road Consolidation:TranshipmentRoadConsolidationUpdate", "roa-tra-consolidationUpdate"),
            Map.entry("Consolidations:Update:Road Consolidation:EmptyContainerRoadConsolidationUpdate", "roa-emt-consolidationUpdate"),
            Map.entry("Consolidations:Update:Road Consolidation:DomesticRoadConsolidationUpdate", "roa-dom-consolidationUpdate"),
            Map.entry("Consolidations:Update:Road Consolidation:CrossTradeRoadConsolidationUpdate", "roa-cts-consolidationUpdate"),
            Map.entry("Consolidations:Update:Road Consolidation:AllRoadConsolidationUpdate", "roa-consolidationUpdate"),
            Map.entry("Consolidations:Update:Sea Consolidation:ImportSeaConsolidationUpdate", "sea-imp-consolidationUpdate"),
            Map.entry("Consolidations:Update:Sea Consolidation:ExportSeaConsolidationUpdate", "sea-exp-consolidationUpdate"),
            Map.entry("Consolidations:Update:Sea Consolidation:ReshipmentSeaConsolidationUpdate", "sea-res-consolidationUpdate"),
            Map.entry("Consolidations:Update:Sea Consolidation:TranshipmentSeaConsolidationUpdate", "sea-tra-consolidationUpdate"),
            Map.entry("Consolidations:Update:Sea Consolidation:EmptyContainerSeaConsolidationUpdate", "sea-emt-consolidationUpdate"),
            Map.entry("Consolidations:Update:Sea Consolidation:DomesticSeaConsolidationUpdate", "sea-dom-consolidationUpdate"),
            Map.entry("Consolidations:Update:Sea Consolidation:CrossTradeSeaConsolidationUpdate", "sea-cts-consolidationUpdate"),
            Map.entry("Consolidations:Update:Sea Consolidation:AllSeaConsolidationUpdate", "sea-consolidationUpdate")
    );
    // export
    private static final String AIR_EXPORT = "air-exp";
    private static final String SEA_EXPORT = "sea-exp";
    private static final String RAIL_EXPORT = "rai-exp";
    private static final String ROAD_EXPORT = "roa-exp";
    // import
    private static final String AIR_IMPORT = "air-imp";
    private static final String SEA_IMPORT = "sea-imp";
    private static final String RAIL_IMPORT = "rai-imp";
    private static final String ROAD_IMPORT = "roa-imp";
    // cross trade
    private static final String AIR_CROSS_TRADE = "air-cts";
    private static final String SEA_CROSS_TRADE = "sea-cts";
    private static final String RAIL_CROSS_TRADE = "rai-cts";
    private static final String ROAD_CROSS_TRADE = "roa-cts";
    // transhipment
    private static final String AIR_TRANSHIPMENT = "air-tra";
    private static final String SEA_TRANSHIPMENT = "sea-tra";
    private static final String RAIL_TRANSHIPMENT = "rai-tra";
    private static final String ROAD_TRANSHIPMENT = "roa-tra";
    // reshipment
    private static final String AIR_RESHIPMENT = "air-res";
    private static final String SEA_RESHIPMENT = "sea-res";
    private static final String RAIL_RESHIPMENT = "rai-res";
    private static final String ROAD_RESHIPMENT = "roa-res";
    //domestic
    private static final String AIR_DOMESTIC = "air-dom";
    private static final String SEA_DOMESTIC = "sea-dom";
    private static final String RAIL_DOMESTIC = "rai-dom";
    private static final String ROAD_DOMESTIC = "roa-dom";
    private static final Map<String, List<String>> updatedPermissionMapping = Map.<String, List<String>>ofEntries(
            // SHIPMENT PERMISSION MAPPINGS
            Map.entry("Operations:Shipments:AIR:Export:View", List.of(AIR_EXPORT)),
            Map.entry("Operations:Shipments:AIR:Export:Create", List.of(AIR_EXPORT)),
            Map.entry("Operations:Shipments:AIR:Export:Modify", List.of(AIR_EXPORT)),
            Map.entry("Operations:Shipments:AIR:Export:Cancel", List.of(AIR_EXPORT)),
            Map.entry("Operations:Shipments:AIR:Import:View", List.of(AIR_IMPORT)),
            Map.entry("Operations:Shipments:AIR:Import:Create", List.of(AIR_IMPORT)),
            Map.entry("Operations:Shipments:AIR:Import:Modify", List.of(AIR_IMPORT)),
            Map.entry("Operations:Shipments:AIR:Import:Cancel", List.of(AIR_IMPORT)),
            Map.entry("Operations:Shipments:AIR:CrossTrade:View", List.of(AIR_CROSS_TRADE)),
            Map.entry("Operations:Shipments:AIR:CrossTrade:Create", List.of(AIR_CROSS_TRADE)),
            Map.entry("Operations:Shipments:AIR:CrossTrade:Modify", List.of(AIR_CROSS_TRADE)),
            Map.entry("Operations:Shipments:AIR:CrossTrade:Cancel", List.of(AIR_CROSS_TRADE)),
            Map.entry("Operations:Shipments:AIR:Transhipment:View", List.of(AIR_TRANSHIPMENT)),
            Map.entry("Operations:Shipments:AIR:Transhipment:Create", List.of(AIR_TRANSHIPMENT)),
            Map.entry("Operations:Shipments:AIR:Transhipment:Modify", List.of(AIR_TRANSHIPMENT)),
            Map.entry("Operations:Shipments:AIR:Transhipment:Cancel", List.of(AIR_TRANSHIPMENT)),
            Map.entry("Operations:Shipments:AIR:Reshipment:View", List.of(AIR_RESHIPMENT)),
            Map.entry("Operations:Shipments:AIR:Reshipment:Create", List.of(AIR_RESHIPMENT)),
            Map.entry("Operations:Shipments:AIR:Reshipment:Modify", List.of(AIR_RESHIPMENT)),
            Map.entry("Operations:Shipments:AIR:Reshipment:Cancel", List.of(AIR_RESHIPMENT)),
            Map.entry("Operations:Shipments:AIR:Domestic:View", List.of(AIR_DOMESTIC)),
            Map.entry("Operations:Shipments:AIR:Domestic:Create", List.of(AIR_DOMESTIC)),
            Map.entry("Operations:Shipments:AIR:Domestic:Modify", List.of(AIR_DOMESTIC)),
            Map.entry("Operations:Shipments:AIR:Domestic:Cancel", List.of(AIR_DOMESTIC)),

            Map.entry("Operations:Shipments:ROA:Export:View", List.of(ROAD_EXPORT)),
            Map.entry("Operations:Shipments:ROA:Export:Create", List.of(ROAD_EXPORT)),
            Map.entry("Operations:Shipments:ROA:Export:Modify", List.of(ROAD_EXPORT)),
            Map.entry("Operations:Shipments:ROA:Export:Cancel", List.of(ROAD_EXPORT)),
            Map.entry("Operations:Shipments:ROA:Import:View", List.of(ROAD_IMPORT)),
            Map.entry("Operations:Shipments:ROA:Import:Create", List.of(ROAD_IMPORT)),
            Map.entry("Operations:Shipments:ROA:Import:Modify", List.of(ROAD_IMPORT)),
            Map.entry("Operations:Shipments:ROA:Import:Cancel", List.of(ROAD_IMPORT)),
            Map.entry("Operations:Shipments:ROA:CrossTrade:View", List.of(ROAD_CROSS_TRADE)),
            Map.entry("Operations:Shipments:ROA:CrossTrade:Create", List.of(ROAD_CROSS_TRADE)),
            Map.entry("Operations:Shipments:ROA:CrossTrade:Modify", List.of(ROAD_CROSS_TRADE)),
            Map.entry("Operations:Shipments:ROA:CrossTrade:Cancel", List.of(ROAD_CROSS_TRADE)),
            Map.entry("Operations:Shipments:ROA:Transhipment:View", List.of(ROAD_TRANSHIPMENT)),
            Map.entry("Operations:Shipments:ROA:Transhipment:Create", List.of(ROAD_TRANSHIPMENT)),
            Map.entry("Operations:Shipments:ROA:Transhipment:Modify", List.of(ROAD_TRANSHIPMENT)),
            Map.entry("Operations:Shipments:ROA:Transhipment:Cancel", List.of(ROAD_TRANSHIPMENT)),
            Map.entry("Operations:Shipments:ROA:Reshipment:View", List.of(ROAD_RESHIPMENT)),
            Map.entry("Operations:Shipments:ROA:Reshipment:Create", List.of(ROAD_RESHIPMENT)),
            Map.entry("Operations:Shipments:ROA:Reshipment:Modify", List.of(ROAD_RESHIPMENT)),
            Map.entry("Operations:Shipments:ROA:Reshipment:Cancel", List.of(ROAD_RESHIPMENT)),
            Map.entry("Operations:Shipments:ROA:Domestic:View", List.of(ROAD_DOMESTIC)),
            Map.entry("Operations:Shipments:ROA:Domestic:Create", List.of(ROAD_DOMESTIC)),
            Map.entry("Operations:Shipments:ROA:Domestic:Modify", List.of(ROAD_DOMESTIC)),
            Map.entry("Operations:Shipments:ROA:Domestic:Cancel", List.of(ROAD_DOMESTIC)),

            Map.entry("Operations:Shipments:RAI:Export:View", List.of(RAIL_EXPORT)),
            Map.entry("Operations:Shipments:RAI:Export:Create", List.of(RAIL_EXPORT)),
            Map.entry("Operations:Shipments:RAI:Export:Modify", List.of(RAIL_EXPORT)),
            Map.entry("Operations:Shipments:RAI:Export:Cancel", List.of(RAIL_EXPORT)),
            Map.entry("Operations:Shipments:RAI:Import:View", List.of(RAIL_IMPORT)),
            Map.entry("Operations:Shipments:RAI:Import:Create", List.of(RAIL_IMPORT)),
            Map.entry("Operations:Shipments:RAI:Import:Modify", List.of(RAIL_IMPORT)),
            Map.entry("Operations:Shipments:RAI:Import:Cancel", List.of(RAIL_IMPORT)),
            Map.entry("Operations:Shipments:RAI:CrossTrade:View", List.of(RAIL_CROSS_TRADE)),
            Map.entry("Operations:Shipments:RAI:CrossTrade:Create", List.of(RAIL_CROSS_TRADE)),
            Map.entry("Operations:Shipments:RAI:CrossTrade:Modify", List.of(RAIL_CROSS_TRADE)),
            Map.entry("Operations:Shipments:RAI:CrossTrade:Cancel", List.of(RAIL_CROSS_TRADE)),
            Map.entry("Operations:Shipments:RAI:Transhipment:View", List.of(RAIL_TRANSHIPMENT)),
            Map.entry("Operations:Shipments:RAI:Transhipment:Create", List.of(RAIL_TRANSHIPMENT)),
            Map.entry("Operations:Shipments:RAI:Transhipment:Modify", List.of(RAIL_TRANSHIPMENT)),
            Map.entry("Operations:Shipments:RAI:Transhipment:Cancel", List.of(RAIL_TRANSHIPMENT)),
            Map.entry("Operations:Shipments:RAI:Reshipment:View", List.of(RAIL_RESHIPMENT)),
            Map.entry("Operations:Shipments:RAI:Reshipment:Create", List.of(RAIL_RESHIPMENT)),
            Map.entry("Operations:Shipments:RAI:Reshipment:Modify", List.of(RAIL_RESHIPMENT)),
            Map.entry("Operations:Shipments:RAI:Reshipment:Cancel", List.of(RAIL_RESHIPMENT)),
            Map.entry("Operations:Shipments:RAI:Domestic:View", List.of(RAIL_DOMESTIC)),
            Map.entry("Operations:Shipments:RAI:Domestic:Create", List.of(RAIL_DOMESTIC)),
            Map.entry("Operations:Shipments:RAI:Domestic:Modify", List.of(RAIL_DOMESTIC)),
            Map.entry("Operations:Shipments:RAI:Domestic:Cancel", List.of(RAIL_DOMESTIC)),

            Map.entry("Operations:Shipments:SEA:Export:View", List.of(SEA_EXPORT)),
            Map.entry("Operations:Shipments:SEA:Export:Create", List.of(SEA_EXPORT)),
            Map.entry("Operations:Shipments:SEA:Export:Modify", List.of(SEA_EXPORT)),
            Map.entry("Operations:Shipments:SEA:Export:Cancel", List.of(SEA_EXPORT)),
            Map.entry("Operations:Shipments:SEA:Import:View", List.of(SEA_IMPORT)),
            Map.entry("Operations:Shipments:SEA:Import:Create", List.of(SEA_IMPORT)),
            Map.entry("Operations:Shipments:SEA:Import:Modify", List.of(SEA_IMPORT)),
            Map.entry("Operations:Shipments:SEA:Import:Cancel", List.of(SEA_IMPORT)),
            Map.entry("Operations:Shipments:SEA:CrossTrade:View", List.of(SEA_CROSS_TRADE)),
            Map.entry("Operations:Shipments:SEA:CrossTrade:Create", List.of(SEA_CROSS_TRADE)),
            Map.entry("Operations:Shipments:SEA:CrossTrade:Modify", List.of(SEA_CROSS_TRADE)),
            Map.entry("Operations:Shipments:SEA:CrossTrade:Cancel", List.of(SEA_CROSS_TRADE)),
            Map.entry("Operations:Shipments:SEA:Transhipment:View", List.of(SEA_TRANSHIPMENT)),
            Map.entry("Operations:Shipments:SEA:Transhipment:Create", List.of(SEA_TRANSHIPMENT)),
            Map.entry("Operations:Shipments:SEA:Transhipment:Modify", List.of(SEA_TRANSHIPMENT)),
            Map.entry("Operations:Shipments:SEA:Transhipment:Cancel", List.of(SEA_TRANSHIPMENT)),
            Map.entry("Operations:Shipments:SEA:Reshipment:View", List.of(SEA_RESHIPMENT)),
            Map.entry("Operations:Shipments:SEA:Reshipment:Create", List.of(SEA_RESHIPMENT)),
            Map.entry("Operations:Shipments:SEA:Reshipment:Modify", List.of(SEA_RESHIPMENT)),
            Map.entry("Operations:Shipments:SEA:Reshipment:Cancel", List.of(SEA_RESHIPMENT)),
            Map.entry("Operations:Shipments:SEA:Domestic:View", List.of(SEA_DOMESTIC)),
            Map.entry("Operations:Shipments:SEA:Domestic:Create", List.of(SEA_DOMESTIC)),
            Map.entry("Operations:Shipments:SEA:Domestic:Modify", List.of(SEA_DOMESTIC)),
            Map.entry("Operations:Shipments:SEA:Domestic:Cancel", List.of(SEA_DOMESTIC)),

            // CONSOLIDATION PERMISSION MAPPINGS
            Map.entry("Operations:Consolidations:AIR:Export:View", List.of(AIR_EXPORT)),
            Map.entry("Operations:Consolidations:AIR:Export:Create", List.of(AIR_EXPORT)),
            Map.entry("Operations:Consolidations:AIR:Export:Modify", List.of(AIR_EXPORT)),
            Map.entry("Operations:Consolidations:AIR:Export:Cancel", List.of(AIR_EXPORT)),
            Map.entry("Operations:Consolidations:AIR:Import:View", List.of(AIR_IMPORT)),
            Map.entry("Operations:Consolidations:AIR:Import:Create", List.of(AIR_IMPORT)),
            Map.entry("Operations:Consolidations:AIR:Import:Modify", List.of(AIR_IMPORT)),
            Map.entry("Operations:Consolidations:AIR:Import:Cancel", List.of(AIR_IMPORT)),
            Map.entry("Operations:Consolidations:AIR:CrossTrade:View", List.of(AIR_CROSS_TRADE)),
            Map.entry("Operations:Consolidations:AIR:CrossTrade:Create", List.of(AIR_CROSS_TRADE)),
            Map.entry("Operations:Consolidations:AIR:CrossTrade:Modify", List.of(AIR_CROSS_TRADE)),
            Map.entry("Operations:Consolidations:AIR:CrossTrade:Cancel", List.of(AIR_CROSS_TRADE)),
            Map.entry("Operations:Consolidations:AIR:Transhipment:View", List.of(AIR_TRANSHIPMENT)),
            Map.entry("Operations:Consolidations:AIR:Transhipment:Create", List.of(AIR_TRANSHIPMENT)),
            Map.entry("Operations:Consolidations:AIR:Transhipment:Modify", List.of(AIR_TRANSHIPMENT)),
            Map.entry("Operations:Consolidations:AIR:Transhipment:Cancel", List.of(AIR_TRANSHIPMENT)),
            Map.entry("Operations:Consolidations:AIR:Reshipment:View", List.of(AIR_RESHIPMENT)),
            Map.entry("Operations:Consolidations:AIR:Reshipment:Create", List.of(AIR_RESHIPMENT)),
            Map.entry("Operations:Consolidations:AIR:Reshipment:Modify", List.of(AIR_RESHIPMENT)),
            Map.entry("Operations:Consolidations:AIR:Reshipment:Cancel", List.of(AIR_RESHIPMENT)),
            Map.entry("Operations:Consolidations:AIR:Domestic:View", List.of(AIR_DOMESTIC)),
            Map.entry("Operations:Consolidations:AIR:Domestic:Create", List.of(AIR_DOMESTIC)),
            Map.entry("Operations:Consolidations:AIR:Domestic:Modify", List.of(AIR_DOMESTIC)),
            Map.entry("Operations:Consolidations:AIR:Domestic:Cancel", List.of(AIR_DOMESTIC)),

            Map.entry("Operations:Consolidations:ROA:Export:View", List.of(ROAD_EXPORT)),
            Map.entry("Operations:Consolidations:ROA:Export:Create", List.of(ROAD_EXPORT)),
            Map.entry("Operations:Consolidations:ROA:Export:Modify", List.of(ROAD_EXPORT)),
            Map.entry("Operations:Consolidations:ROA:Export:Cancel", List.of(ROAD_EXPORT)),
            Map.entry("Operations:Consolidations:ROA:Import:View", List.of(ROAD_IMPORT)),
            Map.entry("Operations:Consolidations:ROA:Import:Create", List.of(ROAD_IMPORT)),
            Map.entry("Operations:Consolidations:ROA:Import:Modify", List.of(ROAD_IMPORT)),
            Map.entry("Operations:Consolidations:ROA:Import:Cancel", List.of(ROAD_IMPORT)),
            Map.entry("Operations:Consolidations:ROA:CrossTrade:View", List.of(ROAD_CROSS_TRADE)),
            Map.entry("Operations:Consolidations:ROA:CrossTrade:Create", List.of(ROAD_CROSS_TRADE)),
            Map.entry("Operations:Consolidations:ROA:CrossTrade:Modify", List.of(ROAD_CROSS_TRADE)),
            Map.entry("Operations:Consolidations:ROA:CrossTrade:Cancel", List.of(ROAD_CROSS_TRADE)),
            Map.entry("Operations:Consolidations:ROA:Transhipment:View", List.of(ROAD_TRANSHIPMENT)),
            Map.entry("Operations:Consolidations:ROA:Transhipment:Create", List.of(ROAD_TRANSHIPMENT)),
            Map.entry("Operations:Consolidations:ROA:Transhipment:Modify", List.of(ROAD_TRANSHIPMENT)),
            Map.entry("Operations:Consolidations:ROA:Transhipment:Cancel", List.of(ROAD_TRANSHIPMENT)),
            Map.entry("Operations:Consolidations:ROA:Reshipment:View", List.of(ROAD_RESHIPMENT)),
            Map.entry("Operations:Consolidations:ROA:Reshipment:Create", List.of(ROAD_RESHIPMENT)),
            Map.entry("Operations:Consolidations:ROA:Reshipment:Modify", List.of(ROAD_RESHIPMENT)),
            Map.entry("Operations:Consolidations:ROA:Reshipment:Cancel", List.of(ROAD_RESHIPMENT)),
            Map.entry("Operations:Consolidations:ROA:Domestic:View", List.of(ROAD_DOMESTIC)),
            Map.entry("Operations:Consolidations:ROA:Domestic:Create", List.of(ROAD_DOMESTIC)),
            Map.entry("Operations:Consolidations:ROA:Domestic:Modify", List.of(ROAD_DOMESTIC)),
            Map.entry("Operations:Consolidations:ROA:Domestic:Cancel", List.of(ROAD_DOMESTIC)),

            Map.entry("Operations:Consolidations:RAI:Export:View", List.of(RAIL_EXPORT)),
            Map.entry("Operations:Consolidations:RAI:Export:Create", List.of(RAIL_EXPORT)),
            Map.entry("Operations:Consolidations:RAI:Export:Modify", List.of(RAIL_EXPORT)),
            Map.entry("Operations:Consolidations:RAI:Export:Cancel", List.of(RAIL_EXPORT)),
            Map.entry("Operations:Consolidations:RAI:Import:View", List.of(RAIL_IMPORT)),
            Map.entry("Operations:Consolidations:RAI:Import:Create", List.of(RAIL_IMPORT)),
            Map.entry("Operations:Consolidations:RAI:Import:Modify", List.of(RAIL_IMPORT)),
            Map.entry("Operations:Consolidations:RAI:Import:Cancel", List.of(RAIL_IMPORT)),
            Map.entry("Operations:Consolidations:RAI:CrossTrade:View", List.of(RAIL_CROSS_TRADE)),
            Map.entry("Operations:Consolidations:RAI:CrossTrade:Create", List.of(RAIL_CROSS_TRADE)),
            Map.entry("Operations:Consolidations:RAI:CrossTrade:Modify", List.of(RAIL_CROSS_TRADE)),
            Map.entry("Operations:Consolidations:RAI:CrossTrade:Cancel", List.of(RAIL_CROSS_TRADE)),
            Map.entry("Operations:Consolidations:RAI:Transhipment:View", List.of(RAIL_TRANSHIPMENT)),
            Map.entry("Operations:Consolidations:RAI:Transhipment:Create", List.of(RAIL_TRANSHIPMENT)),
            Map.entry("Operations:Consolidations:RAI:Transhipment:Modify", List.of(RAIL_TRANSHIPMENT)),
            Map.entry("Operations:Consolidations:RAI:Transhipment:Cancel", List.of(RAIL_TRANSHIPMENT)),
            Map.entry("Operations:Consolidations:RAI:Reshipment:View", List.of(RAIL_RESHIPMENT)),
            Map.entry("Operations:Consolidations:RAI:Reshipment:Create", List.of(RAIL_RESHIPMENT)),
            Map.entry("Operations:Consolidations:RAI:Reshipment:Modify", List.of(RAIL_RESHIPMENT)),
            Map.entry("Operations:Consolidations:RAI:Reshipment:Cancel", List.of(RAIL_RESHIPMENT)),
            Map.entry("Operations:Consolidations:RAI:Domestic:View", List.of(RAIL_DOMESTIC)),
            Map.entry("Operations:Consolidations:RAI:Domestic:Create", List.of(RAIL_DOMESTIC)),
            Map.entry("Operations:Consolidations:RAI:Domestic:Modify", List.of(RAIL_DOMESTIC)),
            Map.entry("Operations:Consolidations:RAI:Domestic:Cancel", List.of(RAIL_DOMESTIC)),

            Map.entry("Operations:Consolidations:SEA:Export:View", List.of(SEA_EXPORT)),
            Map.entry("Operations:Consolidations:SEA:Export:Create", List.of(SEA_EXPORT)),
            Map.entry("Operations:Consolidations:SEA:Export:Modify", List.of(SEA_EXPORT)),
            Map.entry("Operations:Consolidations:SEA:Export:Cancel", List.of(SEA_EXPORT)),
            Map.entry("Operations:Consolidations:SEA:Import:View", List.of(SEA_IMPORT)),
            Map.entry("Operations:Consolidations:SEA:Import:Create", List.of(SEA_IMPORT)),
            Map.entry("Operations:Consolidations:SEA:Import:Modify", List.of(SEA_IMPORT)),
            Map.entry("Operations:Consolidations:SEA:Import:Cancel", List.of(SEA_IMPORT)),
            Map.entry("Operations:Consolidations:SEA:CrossTrade:View", List.of(SEA_CROSS_TRADE)),
            Map.entry("Operations:Consolidations:SEA:CrossTrade:Create", List.of(SEA_CROSS_TRADE)),
            Map.entry("Operations:Consolidations:SEA:CrossTrade:Modify", List.of(SEA_CROSS_TRADE)),
            Map.entry("Operations:Consolidations:SEA:CrossTrade:Cancel", List.of(SEA_CROSS_TRADE)),
            Map.entry("Operations:Consolidations:SEA:Transhipment:View", List.of(SEA_TRANSHIPMENT)),
            Map.entry("Operations:Consolidations:SEA:Transhipment:Create", List.of(SEA_TRANSHIPMENT)),
            Map.entry("Operations:Consolidations:SEA:Transhipment:Modify", List.of(SEA_TRANSHIPMENT)),
            Map.entry("Operations:Consolidations:SEA:Transhipment:Cancel", List.of(SEA_TRANSHIPMENT)),
            Map.entry("Operations:Consolidations:SEA:Reshipment:View", List.of(SEA_RESHIPMENT)),
            Map.entry("Operations:Consolidations:SEA:Reshipment:Create", List.of(SEA_RESHIPMENT)),
            Map.entry("Operations:Consolidations:SEA:Reshipment:Modify", List.of(SEA_RESHIPMENT)),
            Map.entry("Operations:Consolidations:SEA:Reshipment:Cancel", List.of(SEA_RESHIPMENT)),
            Map.entry("Operations:Consolidations:SEA:Domestic:View", List.of(SEA_DOMESTIC)),
            Map.entry("Operations:Consolidations:SEA:Domestic:Create", List.of(SEA_DOMESTIC)),
            Map.entry("Operations:Consolidations:SEA:Domestic:Modify", List.of(SEA_DOMESTIC)),
            Map.entry("Operations:Consolidations:SEA:Domestic:Cancel", List.of(SEA_DOMESTIC))
    );

    private V1PermissionMapUtil() {
    }

    public static String getPermissionName(String v1Permission) {
        return v1PermissionMapping.get(v1Permission);
    }

    public static List<String> getPermissionNames(List<String> v1PermisionList) {
        List<String> olderPermission = new ArrayList<>();
        Set<String> res = new HashSet<>();
        for (String permission : v1PermisionList) {
            var v1UpdatedPermission = updatedPermissionMapping.get(permission);
            if (!Objects.isNull(v1UpdatedPermission)) {
                res.addAll(v1UpdatedPermission);
            }

            var v1OldPermission = getPermissionName(permission);
            if (!Objects.isNull(v1OldPermission)) {
                olderPermission.add(v1OldPermission);
            }

        }

        olderPermission.addAll(res.stream().toList());
        return olderPermission;
    }
}
