package com.dpw.runner.shipment.services.utils;

import java.util.Map;

public class V1PermissionMapUtil {

    private static final Map<String, String> v1PermissionMapping = Map.ofEntries(
            // SHIPMENT LIST PERMISSION MAPPINGS
            Map.entry("Shipments:List:Air Shipment:ImportAirShipmentList","air-imp-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:ExportAirShipmentList","air-exp-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:ReshipmentAirShipmentList","air-res-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:TranshipmentAirShipmentList","air-tra-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:EmptyContainerAirShipmentList","air-cts-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:DomesticAirShipmentList","air-dom-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:CrossTradeAirShipmentList","air-cts-all-shipmentList"),
            Map.entry("Shipments:List:Air Shipment:AllAirShipmentList","air-shipmentList"),
            Map.entry("Shipments:List:All Shipment:ImportAllShipmentList","all-imp-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:ExportAllShipmentList","all-exp-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:ReshipmentAllShipmentList","all-res-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:TranshipmentAllShipmentList","all-tra-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:EmptyContainerAllShipmentList","all-emt-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:DomesticAllShipmentList","all-dom-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:CrossTradeAllShipmentList","all-cts-all-shipmentList"),
            Map.entry("Shipments:List:All Shipment:AllShipmentList","all-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:ImportRailShipmentList","rail-imp-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:ExportRailShipmentList","rail-exp-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:ReshipmentRailShipmentList","rail-res-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:TranshipmentRailShipmentList","rail-tra-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:EmptyContainerRailShipmentList","rail-emt-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:DomesticRailShipmentList","rail-dom-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:CrossTradeRailShipmentList","rail-cts-shipmentList"),
            Map.entry("Shipments:List:Rail Shipment:AllRailShipmentList","rail-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:ImportRoadShipmentList","road-imp-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:ExportRoadShipmentList","road-exp-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:ReshipmentRoadShipmentList","road-res-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:TranshipmentRoadShipmentList","road-tra-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:EmptyContainerRoadShipmentList","road-emt-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:DomesticRoadShipmentList","road-dom-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:CrossTradeRoadShipmentList","road-cts-shipmentList"),
            Map.entry("Shipments:List:Road Shipment:AllRoadShipmentList","road-shipmentList"),
            // IsDomestic flag
            Map.entry("Shipments:List:Sea International Shipment:ImportSeaShipmentList","sea-imp-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:ExportSeaShipmentList","sea-exp-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:ReshipmentSeaShipmentList","sea-res-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:TranshipmentSeaShipmentList","sea-tra-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:EmptyContainerSeaShipmentList","sea-emt-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:DomesticSeaShipmentList","sea-dom-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:CrossTradeSeaShipmentList","sea-cts-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea International Shipment:AllSeaShipmentList","sea-all-all-international-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:ImportDomesticSeaShipmentList","sea-imp-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:ExportDomesticSeaShipmentList","sea-exp-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:ReshipmentDomesticSeaShipmentList","sea-res-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:TranshipmentDomesticSeaShipmentList","sea-tra-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:EmptyContainerDomesticSeaShipmentList","sea-emt-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:DomesticDomesticSeaShipmentList","sea-dom-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:CrossTradeDomesticSeaShipmentList","sea-cts-all-domestic-shipmentList"),
            Map.entry("Shipments:List:Sea Domestic Shipment:AllDomesticSeaShipmentList","sea-all-all-domestic-shipmentList"),

            // SHIPMENT RETRIEVE PERMISSIONS MAPPING
            Map.entry("Shipments:Retrive:Air Shipment:ImportAirShipmentRetrive","air-imp-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:ExportAirShipmentRetrive","air-exp-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:ReshipmentAirShipmentRetrive","air-res-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:TranshipmentAirShipmentRetrive","air-tra-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:EmptyContainerAirShipmentRetrive","air-cts-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:DomesticAirShipmentRetrive","air-dom-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:CrossTradeAirShipmentRetrive","air-cts-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Air Shipment:AllAirShipmentRetrive","air-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:ImportAllShipmentRetrive","all-imp-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:ExportAllShipmentRetrive","all-exp-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:ReshipmentAllShipmentRetrive","all-res-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:TranshipmentAllShipmentRetrive","all-tra-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:EmptyContainerAllShipmentRetrive","all-emt-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:DomesticAllShipmentRetrive","all-dom-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:CrossTradeAllShipmentRetrive","all-cts-all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:All Shipment:AllShipmentRetrive","all-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:ImportRailShipmentRetrive","rail-imp-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:ExportRailShipmentRetrive","rail-exp-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:ReshipmentRailShipmentRetrive","rail-res-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:TranshipmentRailShipmentRetrive","rail-tra-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:EmptyContainerRailShipmentRetrive","rail-emt-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:DomesticRailShipmentRetrive","rail-dom-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:CrossTradeRailShipmentRetrive","rail-cts-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Rail Shipment:AllRailShipmentRetrive","rail-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:ImportRoadShipmentRetrive","road-imp-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:ExportRoadShipmentRetrive","road-exp-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:ReshipmentRoadShipmentRetrive","road-res-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:TranshipmentRoadShipmentRetrive","road-tra-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:EmptyContainerRoadShipmentRetrive","road-emt-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:DomesticRoadShipmentRetrive","road-dom-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:CrossTradeRoadShipmentRetrive","road-cts-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Road Shipment:AllRoadShipmentRetrive","road-shipmentRetrieve"),
            // IsDomestic flag
            Map.entry("Shipments:Retrive:Sea International Shipment:ImportSeaShipmentRetrive","sea-imp-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:ExportSeaShipmentRetrive","sea-exp-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:ReshipmentSeaShipmentRetrive","sea-res-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:TranshipmentSeaShipmentRetrive","sea-tra-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:EmptyContainerSeaShipmentRetrive","sea-emt-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:DomesticSeaShipmentRetrive","sea-dom-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:CrossTradeSeaShipmentRetrive","sea-cts-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea International Shipment:AllSeaShipmentRetrive","sea-all-all-international-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:ImportDomesticSeaShipmentRetrive","sea-imp-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:ExportDomesticSeaShipmentRetrive","sea-exp-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:ReshipmentDomesticSeaShipmentRetrive","sea-res-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:TranshipmentDomesticSeaShipmentRetrive","sea-tra-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:EmptyContainerDomesticSeaShipmentRetrive","sea-emt-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:DomesticDomesticSeaShipmentRetrive","sea-dom-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:CrossTradeDomesticSeaShipmentRetrive","sea-cts-all-domestic-shipmentRetrieve"),
            Map.entry("Shipments:Retrive:Sea Domestic Shipment:AllDomesticSeaShipmentRetrive","sea-all-all-domestic-shipmentRetrieve")
    );

    public static String getPermissionName(String v1Permission){
        return v1PermissionMapping.get(v1Permission);
    }
}
