ALTER TABLE events ADD COLUMN IF NOT EXISTS branch_name varchar;

UPDATE events SET branch_name = 'London' WHERE tenant_id = '456';
UPDATE events SET branch_name = 'Walvis Bay' WHERE tenant_id = '458';
UPDATE events SET branch_name = 'Miami' WHERE tenant_id = '459';
UPDATE events SET branch_name = 'Ho Chi Minh City' WHERE tenant_id = '461';
UPDATE events SET branch_name = 'Dubai Mainland' WHERE tenant_id = '464';
UPDATE events SET branch_name = 'Ras Al Khaimah' WHERE tenant_id = '465';
UPDATE events SET branch_name = 'Nairobi' WHERE tenant_id = '467';
UPDATE events SET branch_name = 'Rotterdam' WHERE tenant_id = '468';
UPDATE events SET branch_name = 'Windhoek' WHERE tenant_id = '469';
UPDATE events SET branch_name = 'Houston' WHERE tenant_id = '470';
UPDATE events SET branch_name = 'Jeddah' WHERE tenant_id = '473';
UPDATE events SET branch_name = 'Hamburg' WHERE tenant_id = '474';
UPDATE events SET branch_name = 'Can Tho' WHERE tenant_id = '475';
UPDATE events SET branch_name = 'Hanoi' WHERE tenant_id = '476';
UPDATE events SET branch_name = 'Detroit' WHERE tenant_id = '477';
UPDATE events SET branch_name = 'El Paso' WHERE tenant_id = '479';
UPDATE events SET branch_name = 'Bogota' WHERE tenant_id = '480';
UPDATE events SET branch_name = 'Los Angeles' WHERE tenant_id = '481';
UPDATE events SET branch_name = 'Antwerp' WHERE tenant_id = '482';
UPDATE events SET branch_name = 'Amsterdam' WHERE tenant_id = '484';
UPDATE events SET branch_name = 'Jakarta' WHERE tenant_id = '486';
UPDATE events SET branch_name = 'Constanta' WHERE tenant_id = '490';
UPDATE events SET branch_name = 'Frankfurt' WHERE tenant_id = '491';
UPDATE events SET branch_name = 'Riyadh' WHERE tenant_id = '493';
UPDATE events SET branch_name = 'Dammam' WHERE tenant_id = '495';
UPDATE events SET branch_name = 'Surabaya' WHERE tenant_id = '498';
UPDATE events SET branch_name = 'Kuala Lumpur' WHERE tenant_id = '504';
UPDATE events SET branch_name = 'Abu Dhabi' WHERE tenant_id = '506';
UPDATE events SET branch_name = 'Mombasa' WHERE tenant_id = '507';
UPDATE events SET branch_name = 'Sharjah' WHERE tenant_id = '508';
UPDATE events SET branch_name = 'Beira' WHERE tenant_id = '515';
UPDATE events SET branch_name = 'Haiphong' WHERE tenant_id = '516';
UPDATE events SET branch_name = 'Maputo' WHERE tenant_id = '517';
UPDATE events SET branch_name = 'Semarang' WHERE tenant_id = '518';
UPDATE events SET branch_name = 'Barcelona' WHERE tenant_id = '520';
UPDATE events SET branch_name = 'Penang' WHERE tenant_id = '521';
UPDATE events SET branch_name = 'Santiago' WHERE tenant_id = '523';
UPDATE events SET branch_name = 'Bahrain' WHERE tenant_id = '528';
UPDATE events SET branch_name = 'Muscat' WHERE tenant_id = '530';
UPDATE events SET branch_name = 'HIPL-Mumbai' WHERE tenant_id = '536';
UPDATE events SET branch_name = 'Kuwait' WHERE tenant_id = '538';
UPDATE events SET branch_name = 'Panama City' WHERE tenant_id = '539';
UPDATE events SET branch_name = 'Medan' WHERE tenant_id = '541';
UPDATE events SET branch_name = 'Singapore' WHERE tenant_id = '543';
UPDATE events SET branch_name = 'Guayaquil' WHERE tenant_id = '546';
UPDATE events SET branch_name = 'Linz' WHERE tenant_id = '551';
UPDATE events SET branch_name = 'Johor' WHERE tenant_id = '558';
UPDATE events SET branch_name = 'Sabah' WHERE tenant_id = '559';
UPDATE events SET branch_name = 'Cairo Airport Office' WHERE tenant_id = '571';
UPDATE events SET branch_name = 'Ningbo' WHERE tenant_id = '573';
UPDATE events SET branch_name = 'Beijing' WHERE tenant_id = '574';
UPDATE events SET branch_name = 'Fuzhou' WHERE tenant_id = '575';
UPDATE events SET branch_name = 'Nanjing' WHERE tenant_id = '576';
UPDATE events SET branch_name = 'Xiamen' WHERE tenant_id = '579';
UPDATE events SET branch_name = 'Paris' WHERE tenant_id = '581';
UPDATE events SET branch_name = 'Shanghai' WHERE tenant_id = '582';
UPDATE events SET branch_name = 'Shenzhen' WHERE tenant_id = '583';
UPDATE events SET branch_name = 'Mexico City' WHERE tenant_id = '586';
UPDATE events SET branch_name = 'Sarawak' WHERE tenant_id = '587';
UPDATE events SET branch_name = 'Vancouver' WHERE tenant_id = '590';
UPDATE events SET branch_name = 'Toronto' WHERE tenant_id = '591';
UPDATE events SET branch_name = 'Tianjin' WHERE tenant_id = '601';
UPDATE events SET branch_name = 'Qingdao' WHERE tenant_id = '602';
UPDATE events SET branch_name = 'Lusaka' WHERE tenant_id = '606';
UPDATE events SET branch_name = 'Milan' WHERE tenant_id = '612';
UPDATE events SET branch_name = 'Karachi' WHERE tenant_id = '614';
UPDATE events SET branch_name = 'Phnom Penh' WHERE tenant_id = '625';
UPDATE events SET branch_name = 'Bucharest' WHERE tenant_id = '646';
UPDATE events SET branch_name = 'Santos' WHERE tenant_id = '654';
UPDATE events SET branch_name = 'Bangkok' WHERE tenant_id = '658';
UPDATE events SET branch_name = 'Chengdu' WHERE tenant_id = '659';
UPDATE events SET branch_name = 'Dalian' WHERE tenant_id = '660';
UPDATE events SET branch_name = 'Guangzhou' WHERE tenant_id = '661';
UPDATE events SET branch_name = 'Wuhan' WHERE tenant_id = '662';
UPDATE events SET branch_name = 'London Heathrow' WHERE tenant_id = '663';
UPDATE events SET branch_name = 'Chongqing' WHERE tenant_id = '667';
UPDATE events SET branch_name = 'Gdynia' WHERE tenant_id = '690';
UPDATE events SET branch_name = 'Warsaw' WHERE tenant_id = '692';
UPDATE events SET branch_name = 'Dublin' WHERE tenant_id = '697';
UPDATE events SET branch_name = 'Budapest' WHERE tenant_id = '698';
UPDATE events SET branch_name = 'Prague' WHERE tenant_id = '699';