UPDATE parties
SET
  address_code ='FRO00011572',
  org_id = '126165',
  org_code = 'FRC00011257',
  address_id ='163779',
  org_data ='{
                 "Id": 126165,
                 "City": "Jacksonville",
                 "Guid": "74b88e14-a8df-4ffa-bb27-28a497bbf20a",
                 "Email": "Wlivermore@margocaribe.com",
                 "IsGSA": false,
                 "Phone": "9047427992",
                 "State": "FL",
                 "label": "Margo Outdoor Living",
                 "value": "FRC00011257",
                 "Source": "CRP",
                 "Country": "USA",
                 "Address1": "10501 Cold Storage Rd Building #100",
                 "FullName": "Margo Outdoor Living",
                 "IsActive": 1,
                 "Payables": false,
                 "TenantId": 442,
                 "CompanyId": 372,
                 "Consignee": true,
                 "Consigner": true,
                 "PANNumber": "202239817",
                 "TaxVendor": false,
                 "ExtraParam": "{}",
                 "InsertDate": "2024-07-16T17:30:15.000",
                 "UpdateDate": "2024-10-15T12:10:48.000",
                 "IsSuspended": false,
                 "Receivables": true,
                 "ZipPostCode": "32218",
                 "ActiveClient": true,
                 "CurrencyCode": "USD",
                 "EmailInvoice": false,
                 "InsertUserId": 1712,
                 "UpdateUserId": 1712,
                 "VatRegNumber": "202239817",
                 "ForworderAgent": false,
                 "IsCreditEnabled": false,
                 "IsV2PaymentTerm": false,
                 "OrganizationCode": "FRC00011257",
                 "CustomerIdentifier": "1514944_001",
                 "ReceivableTermsDate": 2,
                 "InsertUserIdUsername": "p100serviceaccountegypt@dpworld.com",
                 "OrgQuoteValidityDays": 0,
                 "UpdateUserIdUsername": "p100serviceaccountegypt@dpworld.com",
                 "CreditLimitOfConfigRow": "",
                 "CreditTermsOfConfigRow": "",
                 "ImportExportClearanceLock": false
             }'::jsonb
WHERE id = '211095';