UPDATE parties
SET
  address_code ='FRO00018232',
  org_id = '134981',
  org_code = 'FRC00017746',
  address_id ='198732',
  org_data ='{
                 "Id": 134981,
                 "City": "Bottrop",
                 "Guid": "cb91a966-1d7f-47b3-8d7c-bc34ca9f4eda",
                 "Email": "daniela.wibbeling@mc-bauchemie.de",
                 "IsGSA": false,
                 "Phone": "2041101605",
                 "State": "North Rhine-Westphalia",
                 "label": "MC - BAUCHEMIE MULLER GMBH AND CO. KG",
                 "value": "FRC00017746",
                 "Source": "CRP",
                 "Country": "DEU",
                 "Address1": "Am Kruppwald 1 - 8",
                 "FullName": "MC - BAUCHEMIE MULLER GMBH AND CO. KG",
                 "IsActive": 1,
                 "Payables": false,
                 "TenantId": 442,
                 "CompanyId": 372,
                 "Consignee": true,
                 "Consigner": true,
                 "PANNumber": "HRB 888",
                 "TaxVendor": false,
                 "ExtraParam": "{}",
                 "InsertDate": "2024-10-30T08:40:20.000",
                 "UpdateDate": "2025-02-05T16:33:01.000",
                 "IsSuspended": false,
                 "Receivables": true,
                 "ZipPostCode": "46238",
                 "ActiveClient": true,
                 "CurrencyCode": "EUR",
                 "EmailInvoice": false,
                 "InsertUserId": 1712,
                 "UpdateUserId": 1712,
                 "VatRegNumber": "DE119880525",
                 "ForworderAgent": false,
                 "IsCreditEnabled": false,
                 "IsV2PaymentTerm": false,
                 "OrganizationCode": "FRC00017746",
                 "EnableBulkInvoice": false,
                 "CustomerIdentifier": "1627477_001",
                 "ReceivableTermsDate": 2,
                 "InsertUserIdUsername": "p100serviceaccountegypt@dpworld.com",
                 "OrgQuoteValidityDays": 0,
                 "UpdateUserIdUsername": "p100serviceaccountegypt@dpworld.com",
                 "CreditLimitOfConfigRow": "",
                 "CreditTermsOfConfigRow": "",
                 "IsClientEInvoiceEnabled": false,
                 "ImportExportClearanceLock": false
             }'::jsonb
WHERE id IN ( '786046','506047','744549','564438','523197','559837','1047773');