update
	parties
set
	org_code = 'FRC00014596',
	address_code = 'FRO00014945',
	org_id = '129783',
	address_id = '185183',
	updated_at = NOW(),
	org_data = '{
    "Id": 129783,
    "City": "s Herrenberg",
    "Guid": "33429977-b896-488b-95fc-f8c91b7735eb",
    "Email": "DSVH.POCInbound@nl.dsv.com",
    "IsGSA": false,
    "Phone": "31314677943",
    "label": "POC Sweden AB",
    "value": "FRC00014596",
    "Broker": false,
    "Source": "CRP",
    "Carrier": false,
    "Country": "NLD",
    "Address1": "c/o DSV Solutions Nederland BV Transportweg 7",
    "FullName": "POC Sweden AB",
    "IsActive": 1,
    "Payables": false,
    "Services": false,
    "TenantId": 442,
    "CompanyId": 372,
    "Consignee": true,
    "Consigner": true,
    "IsParnter": false,
    "PANNumber": "FRC00014596",
    "TaxVendor": false,
    "WareHouse": false,
    "AirCarrier": false,
    "ExtraParam": "",
    "InsertDate": "2024-09-04T12:04:27.000",
    "SeaCarrier": false,
    "UpdateDate": "2025-07-24T19:56:54.000",
    "IsSuspended": false,
    "RailCarrier": false,
    "Receivables": false,
    "RoadCarrier": false,
    "ZipPostCode": "7041 KK",
    "ActiveClient": true,
    "CurrencyCode": "EUR",
    "EmailInvoice": false,
    "InsertUserId": 1712,
    "UpdateUserId": 1712,
    "ForworderAgent": false,
    "IsCreditEnabled": false,
    "IsV2PaymentTerm": false,
    "TransportClient": false,
    "IsWalkInCustomer": false,
    "OrganizationCode": "FRC00014596",
    "EnableBulkInvoice": false,
    "InsertUserIdUsername": "p100serviceaccountegypt@dpworld.com",
    "OrgQuoteValidityDays": 0,
    "UpdateUserIdUsername": "p100serviceaccountegypt@dpworld.com",
    "CreditLimitOfConfigRow": "",
    "CreditTermsOfConfigRow": "",
    "IsClientEInvoiceEnabled": false,
    "ImportExportClearanceLock": false,
    "FusionCreditlimitOverrideApproved": false
}',
	address_data = '{
    "Id": 185183,
    "City": "s Herrenberg",
    "Email": "DSVH.POCInbound@nl.dsv.com",
    "label": "FRO00014945",
    "value": "FRO00014945",
    "Country": "NLD",
    "OrgGuid": "33429977-b896-488b-95fc-f8c91b7735eb",
    "Address1": "c/o DSV Solutions Nederland BV Transportweg 7",
    "OrgSource": "CRP",
    "AddressType": 2,
    "CompanyName": "POC Sweden AB",
    "OrgFullName": "POC Sweden AB",
    "OrgPayables": false,
    "ZipPostCode": "7041 KK",
    "OrgReceivables": false,
    "OrgActiveClient": true,
    "AddressShortCode": "FRO00014945",
    "OrgOrganizationCode": "FRC00014596"
}'
where
	id = 1279060;

update
	shipment_details
set
	client_dps_address_id = 97657,
	updated_at = NOW()
where
	id = 81923;