-- Update for shipment ID 67336
UPDATE parties
SET
    org_code = 'FRC00030636',
    address_code = 'FRO00031643',
    org_id = '147134',
    address_id = '238880',
    updated_at = NOW(),
    org_data = '{
        "Id": 147134,
        "City": "Morges",
        "Guid": "cd42a8f5-cf26-4416-a5e5-a673fa61d991",
        "Email": "invoice@conforama.ch",
        "IsGSA": false,
        "Phone": "215528068",
        "State": "Vaud",
        "label": "CONFORAMA SUISSE  S.A.",
        "value": "FRC00030636",
        "Broker": false,
        "Source": "CRP",
        "Carrier": false,
        "Country": "CHE",
        "Address1": "221-176 Logistics department / Pascal FELIX  Rue de la Gare 32",
        "Address2": "",
        "FullName": "CONFORAMA SUISSE  S.A.",
        "IsActive": 1,
        "Payables": false,
        "Services": false,
        "TenantId": 442,
        "CompanyId": 372,
        "Consignee": true,
        "Consigner": true,
        "IsParnter": false,
        "PANNumber": "CH-550.0.134.020-6",
        "TaxVendor": false,
        "WareHouse": false,
        "AirCarrier": false,
        "ExtraParam": "",
        "InsertDate": "2025-03-28T20:23:32.000",
        "SeaCarrier": false,
        "UpdateDate": "2025-06-27T16:50:49.000",
        "IsSuspended": false,
        "RailCarrier": false,
        "Receivables": true,
        "RoadCarrier": false,
        "ZipPostCode": "CH-1110",
        "ActiveClient": true,
        "CurrencyCode": "CHF",
        "EmailInvoice": false,
        "InsertUserId": 1712,
        "UpdateUserId": 1712,
        "VatRegNumber": "CHE102382115",
        "ForworderAgent": false,
        "IsCreditEnabled": false,
        "IsV2PaymentTerm": false,
        "TransportClient": false,
        "IsWalkInCustomer": false,
        "OrganizationCode": "FRC00030636",
        "EnableBulkInvoice": false,
        "CustomerIdentifier": "1922275_001",
        "InsertUserIdUsername": "p100serviceaccountegypt@dpworld.com",
        "UpdateUserIdUsername": "p100serviceaccountegypt@dpworld.com",
        "IsClientEInvoiceEnabled": false,
        "ImportExportClearanceLock": false,
        "FusionCreditlimitOverrideApproved": false
    }',
    address_data = '{
        "Id": 238880,
        "City": "Morges",
        "Email": "invoice@conforama.ch",
        "State": "Vaud",
        "label": "FRO00031643",
        "value": "FRO00031643",
        "Country": "CHE",
        "OrgGuid": "cd42a8f5-cf26-4416-a5e5-a673fa61d991",
        "Address1": "221-176 Logistics department / Pascal FELIX  Rue de la Gare 32",
        "Address2": "",
        "OrgSource": "CRP",
        "AddressType": 2,
        "CompanyName": "CONFORAMA SUISSE  S.A.",
        "OrgFullName": "CONFORAMA SUISSE  S.A.",
        "OrgPayables": false,
        "ZipPostCode": "CH-1110",
        "TaxRegNumber": "CHE102382115",
        "OrgReceivables": true,
        "OrgActiveClient": true,
        "AddressShortCode": "FRO00031643",
        "OrgOrganizationCode": "FRC00030636"
    }'
WHERE id IN (SELECT client_id FROM shipment_details WHERE id = 67336);


-- Update for shipment ID 64257
UPDATE parties
SET
    org_code = 'FRC00030636',
    address_code = 'FRO00031643',
    org_id = '147134',
    address_id = '238880',
    updated_at = NOW(),
    org_data = '{
        "Id": 147134,
        "City": "Morges",
        "Guid": "cd42a8f5-cf26-4416-a5e5-a673fa61d991",
        "Email": "invoice@conforama.ch",
        "IsGSA": false,
        "Phone": "1199999999",
        "label": "CONFORAMA SUISSE S.A.",
        "value": "FRC00030636",
        "Broker": false,
        "Source": "CRP",
        "Carrier": false,
        "Country": "CHE",
        "Address1": "Attn: 221-176 Logistics department / Pascal FELIX Rue de la Gare 32,",
        "Address2": "",
        "FullName": "CONFORAMA SUISSE S.A.",
        "IsActive": 1,
        "Payables": false,
        "Services": false,
        "TenantId": 442,
        "CompanyId": 372,
        "Consignee": true,
        "Consigner": true,
        "IsParnter": false,
        "PANNumber": "FRC00030636",
        "TaxVendor": false,
        "WareHouse": false,
        "AirCarrier": false,
        "ExtraParam": "",
        "InsertDate": "2025-03-28T20:23:32.000",
        "SeaCarrier": false,
        "UpdateDate": "2025-03-28T20:23:32.000",
        "IsSuspended": false,
        "RailCarrier": false,
        "Receivables": false,
        "RoadCarrier": false,
        "ZipPostCode": "CH-1110",
        "ActiveClient": true,
        "CurrencyCode": "CHF",
        "EmailInvoice": false,
        "InsertUserId": 1712,
        "UpdateUserId": 1712,
        "ForworderAgent": false,
        "IsCreditEnabled": false,
        "IsV2PaymentTerm": false,
        "TransportClient": false,
        "IsWalkInCustomer": false,
        "OrganizationCode": "FRC00030636",
        "EnableBulkInvoice": false,
        "InsertUserIdUsername": "p100serviceaccountegypt@dpworld.com",
        "UpdateUserIdUsername": "p100serviceaccountegypt@dpworld.com",
        "IsClientEInvoiceEnabled": false,
        "ImportExportClearanceLock": false,
        "FusionCreditlimitOverrideApproved": false
    }',
    address_data = '{
        "Id": 238880,
        "City": "Morges",
        "Email": "invoice@conforama.ch",
        "label": "FRO00031643",
        "value": "FRO00031643",
        "Country": "CHE",
        "OrgGuid": "cd42a8f5-cf26-4416-a5e5-a673fa61d991",
        "Address1": "Attn: 221-176 Logistics department / Pascal FELIX Rue de la Gare 32,",
        "Address2": "",
        "OrgSource": "CRP",
        "AddressType": 2,
        "CompanyName": "CONFORAMA SUISSE S.A.",
        "OrgFullName": "CONFORAMA SUISSE S.A.",
        "OrgPayables": false,
        "ZipPostCode": "CH-1110",
        "OrgReceivables": false,
        "OrgActiveClient": true,
        "AddressShortCode": "FRO00031643",
        "OrgOrganizationCode": "FRC00030636"
    }'
WHERE id IN (SELECT client_id FROM shipment_details WHERE id = 64257);


-- Update client_dps_address_id
UPDATE shipment_details
SET
    client_dps_address_id = 84618,
    updated_at = NOW()
WHERE id IN (67336, 64257);
