trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  isMaven: 'True'
  isJava: 'True'
  jdkVersion: '1.17'
  POM_XML_PATH: 'pom.xml'
  MAVEN_OPTIONS: '-Xmx3072m'
  JAR_NAME: 'runner-shipment-services-0.0.1.jar'

steps:
  - script: |
      echo "===================================="
      echo "Backing up config folder"
      echo "===================================="
      mv src/main/resources/config config_backup
      echo "✅ Config folder moved to backup (config_backup)"
      ls -la src/main/resources/
    displayName: 'Backup config folder'
    condition: and(eq(variables['isMaven'], 'True'), eq(variables['isJava'], 'True'))
  
  - task: Maven@3
    inputs:
      mavenPomFile: $(POM_XML_PATH)
      goals: 'clean package'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '$(jdkVersion)'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: true
      mavenOptions: '$(MAVEN_OPTIONS)'
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
    displayName: 'Build JAR with Maven'
    condition: and(eq(variables['isMaven'], 'True'), eq(variables['isJava'], 'True'))

  - script: |
      echo "===================================="
      echo "Restoring config folder"
      echo "===================================="
      if [ -d "config_backup" ]; then
        mv config_backup src/main/resources
        echo "✅ Config folder restored to src/main/resources"
      else
        echo "⚠️ Config backup folder not found"
      fi
    displayName: 'Restore config folder'
    condition: and(eq(variables['isMaven'], 'True'), eq(variables['isJava'], 'True'))

  - script: |
      echo "===================================="
      echo "Checking if JAR exists:"
      echo "===================================="
      JAR_FILE="target/$(JAR_NAME)"
      
      if [ -f "$JAR_FILE" ]; then
        echo "✅ JAR file found: $JAR_FILE"
        ls -lh $JAR_FILE
      else
        echo "❌ JAR file not found: $JAR_FILE"
        echo "Available files in target:"
        ls -lh target/
        exit 1
      fi
      
      echo ""
      echo "===================================="
      echo "Checking JAR contents for config folder:"
      echo "===================================="
      
      # List all contents of the JAR
      echo "Full JAR contents:"
      jar tf $JAR_FILE
      
      echo ""
      echo "===================================="
      echo "Searching specifically for 'config' folder:"
      echo "===================================="
      
      if jar tf $JAR_FILE | grep -q "^config/"; then
        echo "❌ WARNING: Config folder FOUND in JAR!"
        echo ""
        echo "Config files present:"
        jar tf $JAR_FILE | grep "^config/"
        echo ""
        echo "Total config files found: $(jar tf $JAR_FILE | grep '^config/' | wc -l)"
      else
        echo "✅ SUCCESS: Config folder NOT found in JAR!"
      fi
      
    displayName: 'Verify Config Folder in JAR'
    condition: and(eq(variables['isMaven'], 'True'), eq(variables['isJava'], 'True'))