package com.dpw.runner.shipment.services.dto.response;

import com.dpw.runner.shipment.services.commons.responses.IRunnerResponse;
import com.dpw.runner.shipment.services.dto.request.*;
import com.dpw.runner.shipment.services.entity.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Data
public class ShipmentDetailsResponse implements IRunnerResponse {
    private Long id;
    private UUID guid;
    private String houseBill;
    private String transportMode;
    private String direction;
    private String shipmentType;
    private Integer status;
    private String source;
    private String jobType;
    private String serviceType;
    private String masterBill;
    private String bookingReference;
    private String consolRef;
    private Long salesAgent;
    private String paymentTerms;
    private String incoterms;
    private String shipmentId;
    private Boolean isDomestic;
    private Integer assignedTo;
    private String additionalTerms;
    private String goodsDescription;
    private BigDecimal weight;
    private String weightUnit;
    private BigDecimal volume;
    private String volumeUnit;
    private BigDecimal volumetricWeight;
    private String volumetricWeightUnit;
    private BigDecimal chargable;
    private String chargeableUnit;
    private BigDecimal netWeight;
    private String netWeightUnit;
    private Integer noOfPacks;
    private String packsUnit;
    private Integer innerPacks;
    private String innerPackUnit;
    private Integer freightLocal;
    private String freightLocalCurrency;
    private Integer freightOverseas;
    private String freightOverseasCurrency;
    private boolean autoUpdateWtVol;
    private boolean containerAutoWeightVolumeUpdate;
    private String marksNum;
    private String entryDetail;
    private boolean isLocked;
    private String lockedBy;
    private boolean isNotifyConsigneeEqual;
    private String bookingType;
    private boolean cargoFinanceBooking;
    private String bookingNumber;
    private String route;
    private long SourceTenantId;
    private long documentationPartner;
    private long triangulationPartner;
    private long receivingBranch;
    private boolean intraBranch;
    private Integer prevShipmentStatus;
    private boolean isShipmentReadOnly;
    private String shipmentCompletedBy;
    private LocalDateTime shipmentCompletedOn;
    private String financeClosedBy;
    private LocalDateTime financeClosedOn;
    private PartiesResponse client;
    private PartiesResponse consigner;
    private PartiesResponse consignee;
    private AdditionalDetailResponse additionalDetail;
    private CarrierDetailResponse carrierDetails;
    private List<PickupDeliveryDetailsResponse> pickupDeliveryDetailsList;
    private List<NotesResponse> notesList;
    private List<TruckDriverDetailsResponse> truckDriverDetails;
    private List<ServiceDetailsResponse> servicesList;
    private List<RoutingsResponse> routingsList;
    private List<ReferenceNumbersResponse> referenceNumbersList;
    private List<PackingResponse> packingList;
    private List<FileRepoResponse> fileRepoList;
    private List<EventsResponse> eventsList;
    private List<ELDetailsResponse> elDetailsList;
    private List<BookingCarriageResponse> bookingCarriagesList;
    private List<JobResponse> jobsList;
    private List<ContainerResponse> containersList;
    private Long container20Count;
    private Long container40Count;
    private Long container20GPCount;
    private Long container20RECount;
    private Long container40GPCount;
    private Long container40RECount;
}
