package com.dpw.runner.shipment.services.entity.enums;

public enum IntegrationType {
    PLATFORM_CREATE_BOOKING,
    PLATFORM_UPDATE_BOOKING,
    V1_SHIPMENT_CREATION,
    NPM_OFFER_FETCH_V2,
    NPM_OFFER_FETCH_V8,
    NPM_CONTRACT_FETCH,
    NPM_UPDATE_UTILISATION,
    NPM_FETCH_MULTI_LANG_CHARGE_CODE,
    CRP_LIST_CUSTOMER,
    CRP_RETRIEVE_CUSTOMER,
    V1_ORG_CREDIT_LIMIT_CREATION,
    V1_DATA_SYNC,
    MASTER_DATA_FETCH_FOR_SHIPMENT_LIST,
    MASTER_DATA_FETCH_FOR_NETWORK_TRANSFER_LIST,
    MASTER_DATA_FETCH_FOR_SHIPMENT_RETRIEVE,
    MASTER_DATA_FETCH_FOR_CONSOLIDATION_RETRIEVE,
    MASTER_DATA_FETCH_FOR_NOTIFICATION_LIST,
    MASTER_DATA_FETCH_FOR_PACKING_LIST;
}