package com.dpw.runner.shipment.services.entity.enums;

public enum LoggerEvent {
    MORE_TIME_TAKEN,
    USER_DEFINITION_RETRIEVAL,
    COMPLETE_API_TIME,
    BOOKING_RETRIEVAL,
    BOOKING_COMPLETE_MASTER_DATA_FETCH,
    MASTERDATA_CARRIER,
    MASTERDATA_VESSEL,
    MASTERDATA_KEY_VALUE,
    MASTERDATA_UNLOCATIONS,
    MASTERDATA_CHARGE_TYPE,
    MASTERDATA_CONTAINER_CODES,
    BOOKING_FETCH_JSON_CONVERTER
}