update parties set
 org_code = 'FRC00010895',
 address_code = 'FRO00011190',
 org_id = '126197',
 address_id = '164932',
 org_data =
 '{
      "Email": "Massimo.lin@reagens-group.com",
      "ReceivableTermsDate": 2,
      "ImportExportClearanceLock": false,
      "IsActive": 1,
      "TaxVendor": false,
      "InsertDate": "2024-07-17T17:21:40.000",
      "CustomerIdentifier": "1515469_001",
      "Payables": false,
      "VatRegNumber": "IT00605801208",
      "Guid": "50f160ac-a3e2-4f57-9453-2ccf59dcb40c",
      "ForworderAgent": false,
      "Source": "CRP",
      "IsV2PaymentTerm": false,
      "CurrencyCode": "EUR",
      "Consignee": true,
      "UpdateDate": "2024-08-23T04:47:02.000",
      "PANNumber": "IT00605801208",
      "Phone": "0516639225",
      "UpdateUserId": 1712,
      "OrganizationCode": "FRC00010895",
      "value": "FRC00010895",
      "InsertUserIdUsername": "p100serviceaccountegypt@dpworld.com",
      "Receivables": true,
      "Consigner": true,
      "CreditTermsOfConfigRow": "",
      "OrgQuoteValidityDays": 0,
      "CompanyId": 372,
      "EmailInvoice": false,
      "ZipPostCode": "40016",
      "City": "Bologna",
      "label": "Reagens Spa",
      "Address1": "Via Codronchi 4 San Giorgio di Piano",
      "InsertUserId": 1712,
      "IsSuspended": false,
      "ActiveClient": true,
      "UpdateUserIdUsername": "p100serviceaccountegypt@dpworld.com",
      "IsGSA": false,
      "TenantId": 442,
      "ExtraParam": "{}",
      "State": "Emilia-Romagna",
      "FullName": "Reagens Spa",
      "Country": "ITA",
      "Id": 126197,
      "IsCreditEnabled": false,
      "CreditLimitOfConfigRow": ""
  }',
 address_data = '{
                     "AddressShortCode": "FRO00011190",
                     "Email": "Massimo.lin@reagens-group.com",
                     "OrgFullName": "Reagens Spa",
                     "OrgSource": "CRP",
                     "ZipPostCode": "40016",
                     "OrgReceivables": true,
                     "City": "Bologna",
                     "label": "FRO00011190",
                     "Address1": "Via Codronchi 4 San Giorgio di Piano",
                     "OrgGuid": "50f160ac-a3e2-4f57-9453-2ccf59dcb40c",
                     "CompanyName": "Reagens Spa",
                     "TaxRegNumber": "IT00605801208",
                     "State": "Emilia-Romagna",
                     "OrgOrganizationCode": "FRC00010895",
                     "Country": "ITA",
                     "Id": 164932,
                     "OrgActiveClient": true,
                     "AddressType": 2,
                     "value": "FRO00011190",
                     "OrgPayables": false
                 }'
 where id IN (select client_id from shipment_details where shipment_id IN ('QINS24110311') and tenant_id = 602);