CREATE TABLE if not exists shipment_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid uuid,
    order_guid uuid NOT NULL,
    order_number varchar NOT NULL,
    shipment_id bigint NOT NULL,
    FOREIGN KEY (shipment_id) REFERENCES shipment_details(id),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR,
    updated_by VARCHAR,
    is_deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT Shipments_Orders UNIQUE (shipment_id, order_guid)
);