ALTER TABLE IF EXISTS shipment_details
ADD COLUMN IF NOT EXISTS cargo_ready_date TIMESTAMP DEFAULT NULL,
ADD COLUMN IF NOT EXISTS cargo_delivery_date TIMESTAMP DEFAULT NULL;

ALTER TABLE IF EXISTS consolidation_details
ADD COLUMN IF NOT EXISTS lat_date TIMESTAMP DEFAULT NULL;