CREATE TABLE IF NOT EXISTS date_time_change_logs (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by varchar,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by varchar,
    is_deleted BOOLEAN DEFAULT FALSE,
    tenant_id integer,
    current_value timestamp,
    date_type integer,
    shipment_id bigint,
    source_of_update varchar
);