CREATE TABLE IF NOT EXISTS evgm (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by varchar,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    is_deleted BOOLEAN DEFAULT FALSE,
    updated_at timestamp  NOT NULL,
    updated_by varchar,
    tenant_id INT,
    source_tenant_id INT,
    shipment_guid uuid,
    consolidation_guid uuid,
    booking_id BIGINT,
    shipping_instruction_id BIGINT,
    container_id BIGINT,
    status VARCHAR(50),
    carrier VARCHAR(255),
    responsible_party_id BIGINT,
    authorized_party_id BIGINT,
    approval_signature VARCHAR(255),
    approval_date_time TIMESTAMP,
    vgm_determination_date_time TIMESTAMP,
    delegate BOOLEAN DEFAULT FALSE,
    weight_method INT
);

 ALTER TABLE IF EXISTS carrier_booking
     ADD COLUMN IF NOT EXISTS shipping_instruction_status VARCHAR(50);
