CREATE TABLE IF NOT EXISTS logs_history (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    entity_id bigint,
    entity_type varchar,
    entity_guid uuid,
    entity_payload varchar,
    created_at timestamp  NOT NULL,
    created_by varchar,
    updated_at timestamp  NOT NULL,
    updated_by varchar,
    is_deleted BOOLEAN DEFAULT FALSE,
    tenant_id integer
);