ALTER TABLE shipment_details
    ADD COLUMN IF NOT EXISTS security_status VARCHAR(255);

DROP TABLE IF EXISTS screening_status;
CREATE TABLE IF NOT EXISTS screening_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid uuid,
    shipment_additional_details_id bigint NOT NULL,
    FOREIGN KEY (shipment_additional_details_id) REFERENCES shipment_additional_details(id),
    screening_status varchar NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by INT,
    updated_by INT
);