DROP TABLE IF EXISTS security_status;

CREATE TABLE IF NOT EXISTS security_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid uuid,
    shipment_id bigint NOT NULL,
    FOREIGN KEY (shipment_id) REFERENCES shipment_details(id),
    security_status varchar NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by INT,
    updated_by INT
);