CREATE TABLE IF NOT EXISTS air_messaging_logs (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    entity_guid uuid,
    error_message varchar,
    message_type varchar,
    xml_payload varchar,
    status varchar,
    tenant_id integer,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by varchar(64),
    updated_by varchar(64),
    is_deleted BOOLEAN DEFAULT FALSE
);