ALTER TABLE consolidation_details
    ADD COLUMN IF NOT EXISTS exemption_codes VARCHAR(255),
    ADD COLUMN IF NOT EXISTS aom_free_text VARCHAR(255),
    ADD COLUMN IF NOT EXISTS security_status VARCHAR(255);

CREATE TABLE IF NOT EXISTS screening_status_consol (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid uuid,
    consolidation_details_id bigint NOT NULL,
    FOREIGN KEY (consolidation_details_id) REFERENCES consolidation_details(id),
    screening_status varchar NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by INT,
    updated_by INT
);