CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE achieved_quantities (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    consolidated_volume numeric(19,2),
    consolidated_volume_unit varchar,
    consolidated_weight numeric(19,2),
    consolidated_weight_unit varchar,
    consolidation_charge_quantity numeric(19,2),
    consolidation_charge_quantity_unit varchar,
    weight_volume numeric(19,2),
    weight_volume_unit varchar
);

CREATE TABLE allocations (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    chargeable numeric(19,2),
    chargeable_unit varchar,
    cutoff_date timestamp ,
    hazardous boolean,
    is_temperature_controlled boolean,
    max_temp numeric(19,2),
    max_temp_unit varchar,
    min_temp numeric(19,2),
    min_temp_unit varchar,
    shipments_count integer,
    volume numeric(19,2),
    volume_unit varchar,
    weight numeric(19,2),
    weight_unit varchar
);

CREATE TABLE arrival_departure_details (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    arrival_first_arrival_port_arrival_date timestamp ,
    arrival_last_foreign_port_departure_date timestamp ,
    departure_first_foreign_port_arrival_date timestamp ,
    departure_last_foreign_port_departure_date timestamp ,
    arrival_container_yard_id bigint,
    arrival_first_arrival_port_id bigint,
    arrival_last_foreign_port_id bigint,
    arrival_transport_port_id bigint,
    departure_container_yard_id bigint,
    departure_first_foreign_port_id bigint,
    departure_last_foreign_port_id bigint,
    departure_transport_port_id bigint
);

CREATE TABLE booking_carriage (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    booking_id bigint,
    carriage_mode varchar,
    carriage_type varchar,
    eta timestamp ,
    etd timestamp ,
    pod_id bigint,
    pol_id bigint,
    shipment_id bigint,
    vessel varchar,
    vessel_id bigint,
    voyage varchar
);

CREATE TABLE carrier_details (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    aircraft_registration varchar,
    aircraft_type varchar,
    ata timestamp ,
    atd timestamp ,
    destination varchar,
    eta timestamp ,
    etd timestamp ,
    flight_number varchar,
    journey_number varchar,
    journey_ref_number varchar,
    origin varchar,
    shipping_line varchar,
    truck_ref_number varchar,
    vessel varchar,
    voyage varchar
);

CREATE TABLE consolidation_details (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    additional_terms varchar,
    booking_cutoff timestamp ,
    do_issue_date timestamp ,
    do_place_of_issue_id bigint,
    estimated_terminal_cutoff timestamp ,
    hazardous_booking_cutoff timestamp ,
    igm_file_date timestamp ,
    igm_inward_date timestamp ,
    is_sending_agent_freetext_address boolean,
    mawb varchar,
    marks_n_nums varchar,
    reefer_cutoff timestamp ,
    smtp_igm_date timestamp ,
    smtp_igm_number varchar,
    ship_instruction_cutoff timestamp ,
    source_tenant_id bigint,
    terminal_cutoff timestamp ,
    verified_gross_mass_cutoff timestamp ,
    agent_reference varchar,
    awb_dims varchar,
    bol varchar,
    bonded_warehouse_id bigint,
    booking_type varchar,
    cargo_closing_time timestamp ,
    co_load_booking_reference varchar,
    co_load_mbl varchar,
    consolidation_number varchar,
    consolidation_type varchar,
    container_category varchar,
    copy integer,
    declaration_type varchar,
    delivery_mode varchar,
    description varchar,
    docs_closing_time timestamp ,
    documentation_partner bigint,
    edi_transaction_id varchar,
    first_load varchar,
    igm_file_no varchar,
    intra_branch boolean,
    inward_date_and_time timestamp ,
    is_cargo_only boolean,
    is_charter boolean,
    is_domestic boolean,
    is_inland boolean,
    is_linked boolean,
    is_locked boolean,
    is_receiving_agent_freetext_address boolean,
    last_discharge varchar,
    locked_by varchar,
    manifest_print varchar,
    masterbill_issue_date timestamp ,
    mrn_number varchar,
    msn_number varchar,
    original integer,
    override boolean,
    package_type varchar,
    payment varchar,
    print_other_docs varchar,
    receiving_agent_freetext_address varchar,
    receiving_branch bigint,
    reference_number varchar,
    release_type varchar,
    sending_agent_freetext_address varchar,
    service_level varchar,
    shipment_type varchar,
    special_instructions varchar,
    transport_mode varchar,
    triangulation_partner bigint,
    volume_utilization varchar,
    warehouse_id bigint,
    weight_utilization varchar,
    achieved_quantities_id bigint,
    allocations_id bigint,
    arrival_departure_details_id bigint,
    carrier_detail_id bigint
);

CREATE TABLE containers (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    achieved_volume numeric(19,2),
    achieved_volume_unit varchar,
    achieved_weight numeric(19,2),
    achieved_weight_unit varchar,
    allocated_volume numeric(19,2),
    allocated_volume_unit_id varchar,
    allocated_weight numeric(19,2),
    allocated_weight_unit varchar,
    allocation_date timestamp ,
    carrier_seal_number varchar,
    chargeable numeric(19,2),
    chargeable_unit varchar,
    commodity_code varchar,
    consolidation_id bigint,
    container_code varchar,
    container_comments varchar,
    container_count bigint,
    container_number varchar,
    container_stuffing_location bigint,
    customs_release_code varchar,
    customs_seal_number varchar,
    description_of_goods varchar,
    dg_class varchar,
    extra_params varchar,
    gross_volume numeric(19,2),
    gross_volume_unit varchar,
    gross_weight numeric(19,2),
    gross_weight_unit varchar,
    hazardous boolean,
    hazardous_un varchar,
    hbl_delivery_mode varchar,
    hs_code varchar,
    inner_package_measurement_unit varchar,
    inner_package_number varchar,
    inner_package_type varchar,
    is_empty boolean,
    is_own_container boolean,
    is_reefer boolean,
    is_shipper_owned boolean,
    is_temperature_maintained boolean,
    logging_id bigint,
    marks_n_nums varchar,
    max_temp numeric(19,2),
    max_temp_unit varchar,
    measurement numeric(19,2),
    measurement_unit varchar,
    min_temp numeric(19,2),
    min_temp_unit_id varchar,
    net_weight numeric(19,2),
    net_weight_unit varchar,
    no_of_packages bigint,
    package_breadth numeric(19,2),
    package_height numeric(19,2),
    package_length numeric(19,2),
    packs varchar,
    packs_type varchar,
    pacr_number varchar,
    remarks varchar,
    seal_number varchar,
    serial_number varchar,
    shipper_seal_number varchar,
    status varchar,
    tare_weight numeric(19,2),
    tare_weight_unit varchar,
    terminal_operator_seal_number varchar,
    transport_mode varchar,
    veterinary_seal_number varchar,
    volume_utilization varchar,
    weight_utilization varchar,
    delivery_address_id bigint,
    pickup_address_id bigint
);

CREATE TABLE default_views (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    default_view_id bigint,
    entity varchar,
    guid uuid,
    username varchar
);

CREATE TABLE dg_mapping (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    class_name varchar,
    consolidation_id bigint,
    dg_class varchar,
    dg_substance_id bigint,
    packing_id bigint
);

CREATE TABLE el_details (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    el_number varchar,
    merge_class varchar,
    merge_package_unit varchar,
    merge_package bigint,
    packages bigint,
    partition boolean,
    partition_seq_number bigint,
    shipment_id bigint,
    unit varchar,
    weight numeric(19,2),
    weight_unit varchar
);

CREATE TABLE events (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    actual timestamp ,
    consolidation_id bigint,
    description varchar,
    estimated timestamp ,
    event_estimate_update_reasons varchar,
    is_public_tracking_event boolean,
    latitude varchar,
    longitude varchar,
    master_list varchar,
    place_description varchar,
    place_name varchar,
    shipment_id bigint,
    source varchar
);

CREATE TABLE file_repo (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    client_enabled boolean,
    doc_type varchar,
    entity_id bigint,
    entity_type varchar,
    event_code varchar,
    file_name varchar,
    is_posted boolean,
    path varchar
);

CREATE TABLE jobs (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    additional_terms varchar,
    buyer_id bigint,
    confirm_date timestamp ,
    confirm_number varchar,
    consolidation_id bigint,
    country_of_origin varchar,
    currency varchar,
    description varchar,
    follow_up_date timestamp ,
    inco_term varchar,
    invoice_date timestamp ,
    invoice_number varchar,
    order_date timestamp ,
    order_number varchar,
    order_status varchar,
    service_mode varchar,
    shipment_id bigint,
    transport_mode varchar,
    buyer_detail_id bigint,
    supplier_detail_id bigint
);

CREATE TABLE logs (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    action varchar,
    changed_on timestamp ,
    changes varchar,
    entity_id bigint,
    entity_name varchar,
    parent_id varchar,
    parent_type varchar,
    user_name varchar
);

CREATE TABLE notes (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    entity_id bigint,
    entity_type varchar,
    insert_date timestamp ,
    insert_user_display_name varchar,
    insert_user_id varchar,
    is_active boolean,
    is_public boolean,
    text varchar
);

CREATE TABLE packing (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    dg_class_id varchar,
    dg_goods_id integer,
    dg_substance_id integer,
    hs_code varchar,
    undg_contact varchar,
    chargeable numeric(19,2),
    chargeable_unit varchar,
    commodity varchar,
    commodity_id bigint,
    consolidation_id bigint,
    container_id bigint,
    container_number varchar,
    country_code varchar,
    customs_release_code varchar,
    flash_point varchar,
    goods_description varchar,
    hazardous boolean,
    height numeric(19,2),
    height_unit varchar,
    inner_package_number varchar,
    inner_package_type_id varchar,
    inner_packs_count bigint,
    inner_packs_id bigint,
    inspections varchar,
    is_temperature_controlled boolean,
    length numeric(19,2),
    length_unit varchar,
    marksn_nums varchar,
    max_temp numeric(19,2),
    max_temp_unit varchar,
    min_temp numeric(19,2),
    min_temp_unit_id varchar,
    net_weight numeric(19,2),
    net_weight_unit varchar,
    origin varchar,
    packing_order varchar,
    packs varchar,
    packs_type varchar,
    reference_number varchar,
    shipment_id bigint,
    shipment_number varchar,
    transport_mode varchar,
    vin_number varchar,
    volume numeric(19,2),
    volume_unit varchar,
    volume_weight numeric(19,2),
    volume_weight_unit varchar,
    weight numeric(19,2),
    weight_unit varchar,
    width numeric(19,2),
    width_unit varchar
);

CREATE TABLE parties (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    address_code varchar,
    address_data jsonb,
    entity_id bigint,
    entity_type varchar,
    org_code varchar,
    org_data jsonb,
    party_type varchar
);

CREATE TABLE pickup_delivery_details (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    actual_pickup_or_delivery timestamp ,
    estimated_pickup_or_delivery timestamp ,
    pickup_or_delivery timestamp ,
    port_transport_advised timestamp ,
    required_by timestamp ,
    shipment_id bigint,
    type varchar,
    agent_id bigint,
    broker_id bigint,
    destination_id bigint,
    source_id bigint,
    transporter_id bigint
);

CREATE TABLE reference_numbers (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    consolidation_id bigint,
    country_of_issue varchar,
    reference_number varchar,
    shipment_id bigint,
    type varchar
);

CREATE TABLE routings (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    aircraft_registration varchar,
    aircraft_type varchar,
    ata timestamp ,
    atd timestamp ,
    consolidation_id bigint,
    eta timestamp ,
    etd timestamp ,
    flight_number varchar,
    is_domestic boolean,
    is_linked boolean,
    leg bigint,
    mode varchar,
    pod_id bigint,
    pol_id bigint,
    route_leg_id bigint,
    routing_status varchar,
    shipment_id bigint,
    transit_days bigint,
    vessel_id bigint,
    vessel_name varchar,
    voyage varchar
);

CREATE TABLE services (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    booking_date timestamp ,
    completion_date timestamp ,
    consolidation_id bigint,
    ref_number varchar,
    service_count bigint,
    service_duration bigint,
    service_notes varchar,
    service_type varchar,
    shipment_id bigint,
    srv_location integer,
    contractor_id bigint
);

CREATE TABLE shipment_additional_details (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    ad_code varchar,
    be_type varchar,
    bl_charges_display varchar,
    bl_exporter_shipment varchar,
    boe_date timestamp ,
    boe_number varchar,
    cha_job_number varchar,
    cif_value numeric(19,2),
    ie_code varchar,
    igm_file_date timestamp ,
    igm_file_no varchar,
    igm_inward_date timestamp ,
    smtp_igm_date timestamp ,
    smtp_igm_number varchar,
    wbl_printed boolean,
    activity_type varchar,
    airway_bill_dims varchar,
    andes_response_date timestamp ,
    andes_status varchar,
    andes_status_response_text varchar,
    andes_ticket varchar,
    assess_value numeric(19,2),
    bonded_warehouse_id bigint,
    branch_si_number varchar,
    copy integer,
    custom_city varchar,
    custom_house varchar,
    custom_location varchar,
    customs_no_issue_date timestamp ,
    date_of_issue timestamp ,
    date_of_receipt timestamp ,
    delivery_mode_id varchar,
    draft_printed boolean,
    efreight_status varchar,
    expiry_date timestamp ,
    external_notes varchar,
    free_days numeric(19,2),
    goods_co_id varchar,
    house_bill_type varchar,
    hsn_number bigint,
    import_export_shipment_lock boolean,
    inspection varchar,
    invoice_value numeric(19,2),
    inward_date_and_time timestamp ,
    is_cms_hbl_sent boolean,
    is_credit_override_approved boolean,
    is_export_clearance boolean,
    is_import_clearance boolean,
    is_inland boolean,
    lgd_status varchar,
    line_number bigint,
    local_line_number bigint,
    on_board varchar,
    on_board_date timestamp ,
    original integer,
    ownership varchar,
    ownership_name varchar,
    paid_place bigint,
    passed_by varchar,
    passed_by_person varchar,
    peru_entry_exit_point varchar,
    phase varchar,
    place_of_issue_id bigint,
    place_of_supply bigint,
    printed_original boolean,
    release_type varchar,
    screening_status varchar,
    shipment_id bigint,
    shipper_cod numeric(19,2),
    shipper_cod_pm varchar,
    spot_rate numeric(19,2),
    spot_rate_type varchar,
    sub_line_number bigint,
    supplier_invoice_date timestamp ,
    supplier_invoice_number varchar,
    surrender_printed boolean,
    tipo_document_consignee varchar,
    tipo_document_consignor varchar,
    tipo_document_notify_party varchar,
    total_duty numeric(19,2),
    warehouse_id bigint,
    borrowed_from_id bigint,
    etailor_id bigint,
    export_broker_id bigint,
    import_broker_id bigint,
    notify_party_id bigint,
    receiving_agent_id bigint,
    receiving_forwarder_id bigint,
    sending_agent_id bigint,
    sending_forwarder_id bigint,
    trader_or_supplier_id bigint
);


CREATE TABLE shipment_details (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    source_tenant_id bigint,
    additional_terms varchar,
    assigned_to integer,
    auto_update_wt_vol boolean,
    booking_number varchar,
    booking_reference varchar,
    booking_type varchar,
    cargo_finance_booking boolean,
    chargable numeric(19,2),
    chargeable_unit varchar,
    console_ref varchar,
    container_auto_wv_update boolean,
    direction varchar,
    documentation_partner bigint,
    entry_detail varchar,
    finance_closed_by varchar,
    finance_closed_on timestamp ,
    freight_local integer,
    freight_local_currency varchar,
    freight_overseas integer,
    freight_overseas_currency varchar,
    goods_description varchar,
    house_bill varchar,
    incoterms varchar,
    inner_pack_unit varchar,
    inner_packs integer,
    intra_branch boolean,
    is_domestic boolean,
    is_locked boolean,
    is_notify_consignee_equal boolean,
    is_shipment_read_only boolean,
    job_type varchar,
    locked_by varchar,
    marks_num varchar,
    master_bill varchar,
    net_weight numeric(19,2),
    net_weight_unit varchar,
    no_of_packs integer,
    packs_unit varchar,
    payment_terms varchar,
    prev_shipment_status integer,
    receiving_branch bigint,
    route varchar,
    sales_agent bigint,
    service_type varchar,
    shipment_completed_by varchar,
    shipment_completed_on timestamp ,
    shipment_id varchar,
    shipment_type varchar,
    source varchar,
    status integer,
    transport_mode varchar,
    triangulation_partner bigint,
    volume numeric(19,2),
    volume_unit varchar,
    volumetric_weight numeric(19,2),
    volumetric_weight_unit varchar,
    weight numeric(19,2),
    weight_unit varchar,
    additional_details_id bigint,
    carrier_detail_id bigint,
    client_id bigint,
    consignee_id bigint,
    consigner_id bigint
);

CREATE TABLE shipment_setting (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    advance_period integer,
    ar_ap_flag boolean,
    auto_event_create boolean,
    billing_lite boolean,
    cooldown_time integer,
    enable_route_master boolean,
    footer_columns integer,
    house_bill_number_lock boolean,
    house_bill_number_generation varchar,
    house_bill_prefix varchar,
    is_atd_ata_auto_populate_enabled boolean,
    is_auto_populate_ship_type boolean,
    multiple_shipment_enabled boolean,
    partial_cloning_enabled boolean,
    print_phone_number boolean,
    restrict_hbl_gen boolean,
    restricted_locations_enabled boolean,
    ship_consolidation_container_enabled boolean,
    shipment_id_generation_counter integer,
    shipment_id_generation_prefix varchar,
    shipment_id_generation_type integer,
    shipment_import_approver_role varchar,
    shipment_lite boolean,
    shipment_ti_carges_linkage boolean
);

CREATE TABLE shipment_settings_details_restricted_locations (
    shipment_settings_details_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restricted_locations integer
);

CREATE TABLE truck_driver_details (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    consolidation_id bigint,
    container_id bigint,
    container_type_code varchar,
    driver_mobile_number varchar,
    driver_name varchar,
    self_transporter_name varchar,
    shipment_id bigint,
    trailer_number_plate varchar,
    transporter_name varchar,
    transporter_type varchar,
    truck_number_plate varchar,
    truck_or_trailer_type_id varchar
);

CREATE TABLE validations (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    entity varchar,
    schema_validator jsonb,
    lifecycle_hook varchar
);

CREATE TABLE views (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    columns jsonb,
    criteria jsonb,
    entity varchar,
    is_public boolean
);

ALTER TABLE ONLY arrival_departure_details
    ADD CONSTRAINT arrival_departure_departure_last_foreign FOREIGN KEY (departure_last_foreign_port_id) REFERENCES parties(id);


ALTER TABLE ONLY arrival_departure_details
    ADD CONSTRAINT arrival_departure_arrival_first_arrival FOREIGN KEY (arrival_first_arrival_port_id) REFERENCES parties(id);


ALTER TABLE ONLY shipment_additional_details
    ADD CONSTRAINT shipment_additional_etailor FOREIGN KEY (etailor_id) REFERENCES parties(id);


ALTER TABLE ONLY arrival_departure_details
    ADD CONSTRAINT arrival_departure_arrival_transport_port FOREIGN KEY (arrival_transport_port_id) REFERENCES parties(id);

ALTER TABLE ONLY containers
    ADD CONSTRAINT containers_pickup_address FOREIGN KEY (pickup_address_id) REFERENCES parties(id);


ALTER TABLE ONLY shipment_details
    ADD CONSTRAINT shipment_details_consignee FOREIGN KEY (consignee_id) REFERENCES parties(id);


ALTER TABLE ONLY arrival_departure_details
    ADD CONSTRAINT arrival_departure_arrival_container_yard FOREIGN KEY (arrival_container_yard_id) REFERENCES parties(id);


ALTER TABLE ONLY shipment_additional_details
    ADD CONSTRAINT shipment_additional_import_broker FOREIGN KEY (import_broker_id) REFERENCES parties(id);


ALTER TABLE ONLY shipment_additional_details
    ADD CONSTRAINT shipment_additional_export_broker FOREIGN KEY (export_broker_id) REFERENCES parties(id);


ALTER TABLE ONLY shipment_details
    ADD CONSTRAINT shipment_details_consigner FOREIGN KEY (consigner_id) REFERENCES parties(id);


ALTER TABLE ONLY jobs
    ADD CONSTRAINT jobs_supplier_detail FOREIGN KEY (supplier_detail_id) REFERENCES parties(id);


ALTER TABLE ONLY shipment_settings_details_restricted_locations
    ADD CONSTRAINT shipment_settings_details_restricted_locations_shipment_settings_details FOREIGN KEY (shipment_settings_details_id) REFERENCES shipment_setting(id);


ALTER TABLE ONLY arrival_departure_details
    ADD CONSTRAINT arrival_departure_departure_first_foreign_port FOREIGN KEY (departure_first_foreign_port_id) REFERENCES parties(id);


ALTER TABLE ONLY containers
    ADD CONSTRAINT containers_delivery_address_id FOREIGN KEY (delivery_address_id) REFERENCES parties(id);

ALTER TABLE ONLY shipment_details
    ADD CONSTRAINT shipment_details_additional_details FOREIGN KEY (additional_details_id) REFERENCES shipment_additional_details(id);


ALTER TABLE ONLY services
    ADD CONSTRAINT services_contractor FOREIGN KEY (contractor_id) REFERENCES parties(id);


ALTER TABLE ONLY shipment_additional_details
    ADD CONSTRAINT shipment_additional_details_receiving_agent FOREIGN KEY (receiving_agent_id) REFERENCES parties(id);

ALTER TABLE ONLY pickup_delivery_details
    ADD CONSTRAINT pickup_delivery_details_agent_id FOREIGN KEY (agent_id) REFERENCES parties(id);

ALTER TABLE ONLY pickup_delivery_details
    ADD CONSTRAINT pickup_delivery_details_broker FOREIGN KEY (broker_id) REFERENCES parties(id);


ALTER TABLE ONLY shipment_details
    ADD CONSTRAINT shipment_details_carrier_detail_id FOREIGN KEY (carrier_detail_id) REFERENCES carrier_details(id);

ALTER TABLE ONLY shipment_additional_details
    ADD CONSTRAINT shipment_additional_details_trader_or_supplier_id FOREIGN KEY (trader_or_supplier_id) REFERENCES parties(id);


ALTER TABLE ONLY arrival_departure_details
    ADD CONSTRAINT arrival_departure_details_departure_transport_port FOREIGN KEY (departure_transport_port_id) REFERENCES parties(id);

ALTER TABLE ONLY shipment_additional_details
    ADD CONSTRAINT shipment_additional_details_sending_agent_id FOREIGN KEY (sending_agent_id) REFERENCES parties(id);


ALTER TABLE ONLY consolidation_details
    ADD CONSTRAINT consolidation_details_arrival_departure_details FOREIGN KEY (arrival_departure_details_id) REFERENCES arrival_departure_details(id);

ALTER TABLE ONLY consolidation_details
    ADD CONSTRAINT consolidation_details_achieved_quantities_id FOREIGN KEY (achieved_quantities_id) REFERENCES achieved_quantities(id);


ALTER TABLE ONLY pickup_delivery_details
    ADD CONSTRAINT pickup_delivery_details_destination_id FOREIGN KEY (destination_id) REFERENCES parties(id);

ALTER TABLE ONLY pickup_delivery_details
    ADD CONSTRAINT pickup_delivery_details_transporter_id FOREIGN KEY (transporter_id) REFERENCES parties(id);

ALTER TABLE ONLY shipment_additional_details
    ADD CONSTRAINT shipment_additional_details_borrowed_from FOREIGN KEY (borrowed_from_id) REFERENCES parties(id);

ALTER TABLE ONLY pickup_delivery_details
    ADD CONSTRAINT pickup_delivery_details_source FOREIGN KEY (source_id) REFERENCES parties(id);

ALTER TABLE ONLY shipment_additional_details
    ADD CONSTRAINT shipment_additional_details_receiving_forwarder FOREIGN KEY (receiving_forwarder_id) REFERENCES parties(id);


ALTER TABLE ONLY shipment_additional_details
    ADD CONSTRAINT shipment_additional_details_sending_forwarder FOREIGN KEY (sending_forwarder_id) REFERENCES parties(id);


ALTER TABLE ONLY arrival_departure_details
    ADD CONSTRAINT arrival_departure_details_arrival_last_foreign_port FOREIGN KEY (arrival_last_foreign_port_id) REFERENCES parties(id);

ALTER TABLE ONLY consolidation_details
    ADD CONSTRAINT consolidation_details_carrier_detail_id FOREIGN KEY (carrier_detail_id) REFERENCES carrier_details(id);


ALTER TABLE ONLY consolidation_details
    ADD CONSTRAINT consolidation_details_allocations FOREIGN KEY (allocations_id) REFERENCES allocations(id);


ALTER TABLE ONLY shipment_additional_details
    ADD CONSTRAINT shipment_additional_notify_party FOREIGN KEY (notify_party_id) REFERENCES parties(id);


ALTER TABLE ONLY arrival_departure_details
    ADD CONSTRAINT arrival_departure_departure_container_yard FOREIGN KEY (departure_container_yard_id) REFERENCES parties(id);


ALTER TABLE ONLY jobs
    ADD CONSTRAINT jobs_buyer_detail FOREIGN KEY (buyer_detail_id) REFERENCES parties(id);

ALTER TABLE ONLY shipment_details
    ADD CONSTRAINT shipment_details_client FOREIGN KEY (client_id) REFERENCES parties(id);

CREATE TABLE IF NOT EXISTS shipments_containers_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid uuid,
    container_id bigint NOT NULL,
    FOREIGN KEY (container_id) REFERENCES containers(id),
    shipment_id bigint NOT NULL,
    FOREIGN KEY (shipment_id) REFERENCES shipment_details(id),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by INT,
    updated_by INT,
    CONSTRAINT Shipments_Containers UNIQUE (container_id, shipment_id)
)

CREATE TABLE IF NOT EXISTS validations (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp not null,
  created_by int4,
  guid uuid default uuid_generate_v4(),
  updated_at timestamp not null,
  updated_by int4,
  tenant_id int4,
  entity varchar(32) not null,
  schema_validator jsonb not null,
  lifecycle_hook varchar not null
)
