ALTER TABLE IF EXISTS pickup_delivery_details
    ADD COLUMN drop_mode varchar(255),
    ADD COLUMN labour_charge DECIMAL,
    ADD COLUMN labour_charge_unit varchar(10),
    ADD COLUMN labour_duration TIME,
    ADD COLUMN shipper_ref varchar(255),
    ADD COLUMN interim_receipt varchar(255),
    ADD COLUMN fcl_available_date TIMESTAMP,
    ADD COLUMN storage_date TIMESTAMP,
    ADD COLUMN truck_wait_time_charge DECIMAL,
    ADD COLUMN truck_wait_time_charge_unit varchar(10),
    ADD COLUMN truck_wait_duration TIME,
    ADD COLUMN storage_charge DECIMAL,
    ADD COLUMN storage_charge_unit varchar(10),
    ADD COLUMN storage_charge_duration TIME,
    ADD COLUMN ucr_reference varchar(50),
    ADD COLUMN empty_truck_in_date TIMESTAMP,
    ADD COLUMN loaded_truck_gate_out_date TIMESTAMP;