CREATE TABLE if not exists common_error_logs (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by varchar,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by varchar,
    is_deleted BOOLEAN DEFAULT FALSE,
    tenant_id integer,
    entity_type varchar(255),
    entity_id bigint,
    error_type varchar(255),
    error_message varchar
    );
