CREATE TABLE IF NOT EXISTS audit_log (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    operation varchar NULL,
    entity varchar NULL,
    entity_id bigint NULL,
    changes jsonb NULL,
    entity_type varchar NULL,
    parent_type varchar NULL,
    parent_id bigint NULL,
    tenant_id integer,
    created_at timestamp  NOT NULL,
    created_by  varchar (50),
    updated_at timestamp  NOT NULL,
    updated_by  varchar (50),
    is_deleted BOOLEAN DEFAULT FALSE
);