ALTER TABLE IF EXISTS events
    ADD COLUMN IF NOT EXISTS remarks VARCHAR(255),
    ADD COLUMN IF NOT EXISTS user_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS user_email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS branch VARCHAR(255);

ALTER TABLE IF EXISTS shipment_setting
    ADD COLUMN IF NOT EXISTS events_revamp_enabled BOOLEAN DEFAULT false;