CREATE TABLE IF NOT EXISTS section_details (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    section_name VARCHAR(100) NOT NULL UNIQUE,
    section_description TEXT NOT NULL,
    created_at timestamp  NOT NULL,
    updated_at timestamp  NOT NULL,
    created_by varchar,
    updated_by varchar,
    is_deleted boolean DEFAULT false
);


CREATE TABLE IF NOT EXISTS section_fields (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    field_name VARCHAR(100) NOT NULL UNIQUE,
    field_description TEXT NOT NULL,
    created_at timestamp  NOT NULL,
    updated_at timestamp  NOT NULL,
    created_by varchar,
    updated_by varchar,
    is_deleted boolean DEFAULT false
);


CREATE TABLE IF NOT EXISTS section_visibility (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    branch VARCHAR(100) NOT NULL,
    mode VARCHAR(100) NOT NULL,
    direction VARCHAR(100) NOT NULL,
    created_at timestamp  NOT NULL,
    updated_at timestamp  NOT NULL,
    created_by varchar,
    updated_by varchar,
    is_deleted boolean DEFAULT false,
    UNIQUE (branch, mode, direction) -- Unique constraint
);


CREATE TABLE IF NOT EXISTS section_details_fields (
    section_details_id BIGINT NOT NULL,
    section_fields_id BIGINT NOT NULL,
    PRIMARY KEY (section_details_id, section_fields_id),
    FOREIGN KEY (section_details_id) REFERENCES section_details(id) ON DELETE CASCADE,
    FOREIGN KEY (section_fields_id) REFERENCES section_fields(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS section_visibility_details (
    visibility_id BIGINT NOT NULL,
    section_id BIGINT NOT NULL,
    PRIMARY KEY (visibility_id, section_id),
    FOREIGN KEY (visibility_id) REFERENCES section_visibility(id) ON DELETE CASCADE,
    FOREIGN KEY (section_id) REFERENCES section_details(id) ON DELETE CASCADE
);
