CREATE TABLE if not exists quartz_job_info (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by varchar,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by varchar,
    is_deleted BOOLEAN DEFAULT FALSE,
    tenant_id integer,
    entity_type varchar(255),
    entity_id bigint,
    job_status varchar(255),
    job_type varchar(255),
    start_time timestamp,
    error_message varchar,
    retry_count bigint
    );
