create table if not exists doc_details (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp,
    created_by varchar (64),
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp,
    updated_by varchar (64),
    is_deleted BOOLEAN DEFAULT FALSE,
    tenant_id integer,
    version_number varchar(64),
    "type" varchar(64),
    entity_id bigint
)


ALTER TABLE IF EXISTS shipment_setting
  ADD COLUMN IF NOT EXISTS pre_alert_email_and_logs boolean DEFAULT false;