CREATE TABLE legs (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    sequence bigint,
    legType varchar,
    origin varchar,
    originAddress varchar,
    destination varchar,
    destinationAddress varchar,
    estimatedPickup varchar,
    estimatedDelivery timestamp,
    actualPickup timestamp,
    actualDelivery timestamp,
    requiredBy timestamp,
    dropMode varchar,
    remarks varchar
);

CREATE TABLE ti_containers (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    type varchar,
    number varchar,
    description varchar,
    noOfPackages varchar,
    grossWeight numeric(19,2),
    grossWeightUnit varchar,
    netWeight numeric(19,2),
    netWeightUnit varchar,
    volume numeric(19,2),
    volumeUnit varchar,
    dangerous boolean,
    substanceName varchar,
    unNumber varchar,
    dgClass varchar,
    tunnelRestrictionCode varchar
);

CREATE TABLE ti_packages (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    noOfPackages varchar,
    packageType varchar,
    description varchar,
    dimensions varchar,
    grossWeight numeric(19,2),
    grossWeightUnit varchar,
    netWeight numeric(19,2),
    netWeightUnit varchar,
    volume numeric(19,2),
    volumeUnit varchar,
    dangerous boolean,
    substanceName varchar,
    unNumber varchar,
    hazardLabel varchar,
    tunnelRestrictionCode varchar
);

CREATE TABLE ti_reference (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    type varchar,
    reference varchar
);

CREATE TABLE ti_truck_driver_details (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by integer,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by integer,
    tenant_id integer,
    driver_name varchar,
    driver_mobile_number varchar,
    truck_number_plate varchar,
    trailer_number_plate varchar,
    truckOrTrailerType varchar
);
