CREATE TABLE ti_legs (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by varchar (64),
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by varchar (64),
    is_deleted BOOLEAN DEFAULT FALSE
    tenant_id integer,
    sequence bigint,
    leg_type varchar,
    origin_id bigint,
    destination_id bigint,
    estimated_pickup timestamp,
    estimated_delivery timestamp,
    actual_pickup timestamp,
    actual_delivery timestamp,
    required_by timestamp,
    drop_mode varchar,
    remarks varchar,
    FOREIGN KEY (origin_id) REFERENCES parties(id),
    FOREIGN KEY (destination_id) REFERENCES parties(id)
);

CREATE TABLE ti_containers (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by varchar (64),
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by varchar (64),
    is_deleted BOOLEAN DEFAULT FALSE
    tenant_id integer,
    ti_leg_id bigint NOT NULL,
    type varchar,
    number varchar,
    description varchar,
    no_of_packages varchar,
    gross_weight numeric(19,2),
    gross_weight_unit varchar,
    net_weight numeric(19,2),
    net_weight_unit varchar,
    volume numeric(19,2),
    volume_unit varchar,
    dangerous boolean,
    substance_name varchar,
    un_number varchar,
    dg_class varchar,
    tunnel_restriction_code varchar,
    FOREIGN KEY (ti_leg_id) REFERENCES ti_legs(id)
);

CREATE TABLE ti_packages (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by varchar (64),
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by varchar (64),
    is_deleted BOOLEAN DEFAULT FALSE
    tenant_id integer,
    ti_leg_id bigint NOT NULL,
    no_of_packages varchar,
    package_type varchar,
    description varchar,
    dimensions varchar,
    gross_weight numeric(19,2),
    gross_weight_unit varchar,
    net_weight numeric(19,2),
    net_weight_unit varchar,
    volume numeric(19,2),
    volume_unit varchar,
    dangerous boolean,
    substance_name varchar,
    un_number varchar,
    hazard_label varchar,
    tunnel_restriction_code varchar,
    FOREIGN KEY (ti_leg_id) REFERENCES ti_legs(id)
);

CREATE TABLE ti_reference (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by varchar (50),
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by varchar (50),
    is_deleted BOOLEAN DEFAULT FALSE
    tenant_id integer,
    ti_leg_id bigint NOT NULL,
    type varchar,
    reference varchar,
    FOREIGN KEY (ti_leg_id) REFERENCES ti_legs(id)
);

CREATE TABLE ti_truck_driver_details (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by varchar (64),
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by varchar (64),
    is_deleted BOOLEAN DEFAULT FALSE
    tenant_id integer,
    ti_leg_id bigint NOT NULL,
    driver_name varchar,
    driver_mobile_number varchar,
    truck_number_plate varchar,
    trailer_number_plate varchar,
    truck_or_trailer_type varchar,
    FOREIGN KEY (ti_leg_id) REFERENCES ti_legs(id)
);
