CREATE TABLE if not exists network_transfer (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by varchar,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by varchar,
    is_deleted BOOLEAN DEFAULT FALSE,
    tenant_id integer,
    entity_type varchar(255),
    entity_number varchar(255),
    entity_id bigint,
    created_entity_id bigint,
    transport_mode varchar(255),
    source_branch_id integer,
    status varchar(255),
    job_type varchar(255),
    entity_payload jsonb
);