-- add notification table
CREATE TABLE if not exists notification (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp  NOT NULL,
    created_by varchar,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp  NOT NULL,
    updated_by varchar,
    is_deleted BOOLEAN DEFAULT FALSE,
    tenant_id integer,
    entity_type varchar(255),
    entity_id bigint,
    requested_branch_id integer,
    requested_user varchar(255),
    requested_on timestamp,
    request_type varchar(255),
    reason varchar(512),
    reassigned_to_branch_id integer
);