ALTER TABLE IF EXISTS events
    ADD COLUMN IF NOT EXISTS remarks VARCHAR(255),
    ADD COLUMN IF NOT EXISTS user_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS user_email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS branch VARCHAR(255);
