CREATE TABLE IF NOT EXISTS container_charges_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid uuid,
    container_id bigint NOT NULL,
    FOREIGN KEY (container_id) REFERENCES containers(id),
    charge_id bigint NOT NULL,
    FOREIGN KEY (charge_id) REFERENCES booking_charges(id),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR,
    updated_by VARCHAR,
    CONSTRAINT Containers_Charges UNIQUE (container_id, charge_id),
    is_deleted BOOLEAN DEFAULT FALSE
);

ALTER TABLE IF EXISTS customer_booking
    ADD COLUMN is_platform_booking_created BOOLEAN DEFAULT FALSE;