-- Drop existing tables if they exist
DROP TABLE IF EXISTS dps_event_condition_message CASCADE;
DROP TABLE IF EXISTS dps_event_implication CASCADE;
DROP TABLE IF EXISTS dps_event_rule_matched_field CASCADE;
DROP TABLE IF EXISTS dps_event CASCADE;
ALTER TABLE shipment_details DROP COLUMN IF EXISTS dps_state;

-- Create the 'dps_event' table
CREATE TABLE IF NOT EXISTS dps_event (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid UUID NOT NULL,
    execution_id UUID NOT NULL,
    entity_id TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    workflow_type TEXT,
    state TEXT,
    status TEXT,
    text TEXT,
    dps_field_data JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    event_timestamp TIMESTAMP,
    username_list JSONB,
    matching_condition TEXT,
    transaction_id VARCHAR(255) NOT NULL,
    tasks JSONB
);

-- Create the 'dps_event_condition_message' table
CREATE TABLE IF NOT EXISTS dps_event_condition_message (
    dps_event_id BIGINT NOT NULL,
    condition_message TEXT NOT NULL,
    PRIMARY KEY (dps_event_id, condition_message),
    CONSTRAINT fk_dps_event_condition_message FOREIGN KEY (dps_event_id) REFERENCES dps_event (id) ON DELETE CASCADE
);

-- Create the 'dps_event_implication' table
CREATE TABLE IF NOT EXISTS dps_event_implication (
    dps_event_id BIGINT NOT NULL,
    implication TEXT NOT NULL,
    PRIMARY KEY (dps_event_id, implication),
    CONSTRAINT fk_dps_event_implication FOREIGN KEY (dps_event_id) REFERENCES dps_event (id) ON DELETE CASCADE
);

-- Create the 'dps_event_rule_matched_field' table
CREATE TABLE IF NOT EXISTS dps_event_rule_matched_field (
    dps_event_id BIGINT NOT NULL,
    rule_matched_field TEXT NOT NULL,
    PRIMARY KEY (dps_event_id, rule_matched_field),
    CONSTRAINT fk_dps_event FOREIGN KEY (dps_event_id) REFERENCES dps_event (id) ON DELETE CASCADE
);

-- Add the 'dps_state' column to the 'shipment_details' table
ALTER TABLE shipment_details ADD COLUMN dps_state TEXT;