--views
CREATE TABLE IF NOT EXISTS views(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guid uuid NOT NULL,
  tenant_id INT NOT NULL,
  columns  jsonb,
  criteria jsonb,
  is_public BOOLEAN,
  entity VARCHAR,
  created_by BIGINT,
  created_at TIMESTAMP,
  updated_by BIGINT,
  updated_at TIMESTAMP,
  deleted_by BIGINT,
  deleted_at TIMESTAMP,
  is_deleted BOOLEAN,
  UNIQUE(guid)
);

--default views
CREATE TABLE IF NOT EXISTS default_views(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guid uuid NOT NULL,
  default_view_id BIGINT,
  username VARCHAR NOT NULL,
  entity VARCHAR,
  is_deleted BOOLEAN,
  CONSTRAINT FK_view_id FOREIGN KEY(default_view_id) REFERENCES views(id),
  UNIQUE(guid)
);