CREATE TABLE if not exists hbl (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp  NOT NULL,
  created_by integer,
  guid uuid NOT NULL DEFAULT uuid_generate_v4(),
  updated_at timestamp  NOT NULL,
  updated_by integer,
  tenant_id integer,
  is_deleted BOOLEAN DEFAULT FALSE,
  hbl_data jsonb,
  container_data jsonb,
  cargo_data jsonb,
  notify_party_data jsonb,
  shipment_id bigint NOT NULL
);