CREATE TABLE IF NOT EXISTS sequence_incrementor (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    shipment_increment_id SERIAL ,
    entity_id bigint NULL,
    tenant_id integer,
    created_at timestamp  NOT NULL,
    created_by  varchar (50),
    updated_at timestamp  NOT NULL,
    updated_by  varchar (50),
    is_deleted BOOLEAN DEFAULT FALSE
);

-- alter sequence if exists sequence_incrementor_shipment_increment_id_seq restart with 9889;