CREATE TABLE IF NOT EXISTS order_number (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    tenant_id integer,
    created_at timestamp  NOT NULL,
    created_by varchar (50),
    updated_at timestamp  NOT NULL,
    updated_by varchar (50),
    is_deleted BOOLEAN DEFAULT FALSE,
    order_number BIGINT
    );

ALTER TABLE order_number
ALTER COLUMN created_by TYPE varchar (50),
   ALTER COLUMN updated_by TYPE varchar (50);