CREATE TABLE IF NOT EXISTS console_shipment_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid uuid,
    consolidation_id bigint NOT NULL,
    FOREIGN KEY (consolidation_id) REFERENCES consolidation_details(id),
    shipment_id bigint NOT NULL,
    FOREIGN KEY (shipment_id) REFERENCES shipment_details(id),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by INT,
    updated_by INT,
    CONSTRAINT Shipments_Consolidations UNIQUE (consolidation_id, shipment_id),
    is_deleted BOOLEAN DEFAULT FALSE
)