CREATE TABLE IF NOT EXISTS hbl_release_type_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid uuid,
    tenant_id integer,
    hbl_id bigint NOT NULL,
    FOREIGN KEY (hbl_id) REFERENCES hbl(id),
    release_type varchar(32) NOT NULL,
    copies_printed int NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by varchar(64),
    updated_by varchar(64),
    is_deleted BOOLEAN DEFAULT FALSE
);