CREATE TABLE IF NOT EXISTS sync_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guid uuid,
    tenant_id integer,
    sync_tenant_id integer,
    module_type varchar(64) not null,
    module_id varchar(64) not null,
    sync_data jsonb not null,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by varchar(64),
    updated_by varchar(64),
    is_deleted BOOLEAN DEFAULT FALSE
);