CREATE TABLE history_detail_meta (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp without time zone NOT NULL,
    created_by varchar,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp without time zone NOT NULL,
    updated_by varchar,
    is_deleted boolean DEFAULT false,
    entity_type VARCHAR(255) NOT NULL,
    entity_id BIGINT NOT NULL,
    changed_by_user VARCHAR(255),
    changed_by_user_email VARCHAR(255),
    change_source VARCHAR(255),
    change_timestamp TIMESTAMP NOT NULL,
    action VARCHAR(50) NOT NULL
);

CREATE TABLE history_detail (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp without time zone NOT NULL,
    created_by varchar,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp without time zone NOT NULL,
    updated_by varchar,
    is_deleted boolean DEFAULT false,
    history_meta_id BIGINT NOT NULL,
    FOREIGN KEY (history_meta_id) REFERENCES history_detail_meta(id),
    field_name VARCHAR(255) NOT NULL,
    old_value TEXT,
    new_value TEXT
);
