CREATE TABLE if not exists consolidation_backup (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	tenant_id int4 NULL,
	guid uuid DEFAULT uuid_generate_v4() NOT NULL,
	consolidation_id int8 NULL,
	consolidation_guid uuid NULL,
	consolidation_details text NULL,
	console_shipment_mapping_details text NULL,
	created_at timestamp NOT NULL,
	created_by varchar(50) NULL,
	updated_at timestamp NOT NULL,
	updated_by varchar(50) NULL,
	is_deleted bool DEFAULT false NULL,
	back_up_time_utc timestamptz NULL,
	network_transfer_details text NULL
);

CREATE TABLE if not exists customer_booking_backup (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	tenant_id int4 NULL,
	guid uuid DEFAULT uuid_generate_v4() NOT NULL,
	booking_id int8 NULL,
	customer_booking_details text NULL,
	booking_guid uuid NULL,
	created_at timestamp NOT NULL,
	created_by varchar(50) NULL,
	updated_at timestamp NOT NULL,
	updated_by varchar(50) NULL,
	is_deleted bool DEFAULT false NULL,
	back_up_time_utc timestamptz NULL
);

CREATE TABLE if not exists shipment_backup (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	tenant_id int4 NULL,
	guid uuid DEFAULT uuid_generate_v4() NOT NULL,
	shipment_id int8 NULL,
	shipment_guid uuid NULL,
	shipment_details text NULL,
	pickup_delivery_details text NULL,
	is_shipment_attached bool NULL,
	created_at timestamp NOT NULL,
	created_by varchar(50) NULL,
	updated_at timestamp NOT NULL,
	updated_by varchar(50) NULL,
	is_deleted bool DEFAULT false NULL,
	back_up_time_utc timestamptz NULL,
	network_transfer_details text NULL
);