CREATE TABLE if not exists network_transfer_backup (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	tenant_id int4 NULL,
	guid uuid DEFAULT uuid_generate_v4() NOT NULL,
	network_transfer_id int8 NULL,
	network_transfer_guid uuid NULL,
	network_transfer_details text NULL,
	created_at timestamp NOT NULL,
    created_by varchar(50) NULL,
    updated_at timestamp NOT NULL,
    updated_by varchar(50) NULL,
    is_deleted bool DEFAULT false NULL,
    back_up_time_utc timestamptz NULL,
);