CREATE TABLE IF NOT EXISTS internal_events (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id BIGINT NOT NULL,
    entity_type VARCHAR(255) NOT NULL,
    payload TEXT,
    published_status VARCHAR(255),
    published_timestamp TIMESTAMP NULL,
    consumed_status VARCHAR(255),
    consumed_timestamp TIMESTAMP NULL
);