ALTER TABLE IF EXISTS customer_booking
    ADD COLUMN IF NOT EXISTS incoterms_location varchar(64),
    ADD COLUMN IF NOT EXISTS controlled BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS controlled_reference_number varchar(64),
    ADD COLUMN IF NOT EXISTS partner varchar(64),
    ADD COLUMN IF NOT EXISTS partner_bkg_number varchar(64),
    ADD COLUMN IF NOT EXISTS partner_bl_or_awb_number varchar(64),
    ADD COLUMN IF NOT EXISTS carrier_bkg_number varchar(64),
    ADD COLUMN IF NOT EXISTS booking_agent bigint,
    ADD COLUMN IF NOT EXISTS pickup_at_origin_type varchar(64),
    ADD COLUMN IF NOT EXISTS delivery_at_destination_type varchar(64),
    ADD COLUMN IF NOT EXISTS brokerage_at_origin_type varchar(64),
    ADD COLUMN IF NOT EXISTS brokerage_at_destination_type varchar(64),
    ADD COLUMN IF NOT EXISTS pickup_at_origin timestamp,
    ADD COLUMN IF NOT EXISTS delivery_at_destination timestamp,
    ADD COLUMN IF NOT EXISTS brokerage_at_origin bigint,
    ADD COLUMN IF NOT EXISTS brokerage_at_destination bigint,
    ADD COLUMN IF NOT EXISTS brokerage_at_origin_date timestamp,
    ADD COLUMN IF NOT EXISTS brokerage_at_destination_date timestamp,
    ADD COLUMN IF NOT EXISTS terminal_cut_off timestamp,
    ADD COLUMN IF NOT EXISTS verified_gross_mass_cut_off timestamp,
    ADD COLUMN IF NOT EXISTS shipping_instruction_cutoff timestamp,
    ADD COLUMN IF NOT EXISTS dg_cut_off timestamp,
    ADD COLUMN IF NOT EXISTS reefer_cut_off timestamp,
    ADD COLUMN IF NOT EXISTS earliest_empty_equipment_pickup timestamp,
    ADD COLUMN IF NOT EXISTS latest_full_equipment_delivered_to_carrier timestamp,
    ADD COLUMN IF NOT EXISTS earliest_drop_off_full_equipment_to_carrier timestamp,
    ADD COLUMN IF NOT EXISTS latest_arrival_time timestamp,
    ADD COLUMN IF NOT EXISTS is_reefer BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS cargo_readiness_date timestamp;