CREATE TABLE IF NOT EXISTS network_transfer_shipments_mapping (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp without time zone NOT NULL,
    created_by varchar,
    guid uuid NOT NULL DEFAULT uuid_generate_v4(),
    updated_at timestamp without time zone NOT NULL,
    updated_by varchar,
    is_deleted boolean DEFAULT false,
    network_transfer_id BIGINT NOT NULL,
    FOREIGN KEY (network_transfer_id) REFERENCES network_transfer(id),
    entity_type VARCHAR(255),
    entity_number VARCHAR(255),
    shipment_number VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS network_transfer_id_idx ON network_transfer_shipments_mapping(network_transfer_id);
CREATE INDEX IF NOT EXISTS shipment_number_idx ON network_transfer_shipments_mapping(shipment_number);