package com.dpw.runner.shipment.services.entitytransfer.dto;

import com.dpw.runner.shipment.services.entity.enums.AndesStatus;
import com.dpw.runner.shipment.services.entity.enums.LGDStatus;
import com.dpw.runner.shipment.services.entity.enums.Ownership;
import com.dpw.runner.shipment.services.entitytransfer.common.request.IEntityTranferBaseEntity;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

@Data
@ToString
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class EntityTransferAdditionalDetails implements IEntityTranferBaseEntity {
    private LocalDateTime customsNoIssueDate;
    private LocalDateTime expiryDate;
    private String inspection;
    private String airwayBillDims;
    private BigDecimal shipperCOD;
    private String shipperCODPM;
    private String phase;
    private BigDecimal spotRate;
    private String spotRateType;
    private String efreightStatus;
    private Boolean importExportShipmentLock;
    public String CHAJobNumber;
    public String ADCode;
    public String BEType;
    private String customLocation;
    private String customCity;
    private Boolean isImportClearance;
    private Boolean isExportClearance;
    public String IGMFileNo;
    public String IECode;
    private String branchSINumber;
    private AndesStatus andesStatus;
    private LocalDateTime andesResponseDate;
    private String andesStatusResponseText;
    private String peruEntryExitPoint;
    private String tipoDocumentNotifyParty;
    private String tipoDocumentConsignee;
    private String tipoDocumentConsignor;
    private String andesTicket;
    private Long warehouseId;
    private String activityType;
    private Long hsnNumber;
    public LocalDateTime IGMFileDate;
    public LocalDateTime IGMInwardDate;
    private LocalDateTime inwardDateAndTime;
    private Long lineNumber;
    private Long subLineNumber;
    private Long localLineNumber;
    public String SMTPIGMNumber;
    public LocalDateTime SMTPIGMDate;
    private Boolean isInland;
    private Ownership ownership;
    private String ownershipName;
    private Ownership passedBy;
    private String passedByPerson;
    private LGDStatus lgdStatus;
    private Boolean isCmsHBLSent;
    private Boolean isCreditOverrideApproved;
    private BigDecimal freeDays;
    private String customHouse;
    private String supplierInvoiceNumber;
    private LocalDateTime supplierInvoiceDate;
    private BigDecimal invoiceValue;
    private BigDecimal assessValue;
    public BigDecimal CIFValue;
    private BigDecimal totalDuty;
    private String externalNotes;
    private Long bondedWarehouseId;
    private String releaseType;
    private String houseBillType;
    private String onBoard;
    private LocalDateTime onBoardDate;
    private String deliveryMode;
    private Integer original;
    private Integer copy;
    public String BLChargesDisplay;
    public String BLExporterShipment;
    private List<String> screeningStatus;
    private String paidPlace;
    private String placeOfIssue;
    private String placeOfSupply;
    private LocalDateTime dateOfIssue;
    private LocalDateTime dateOfReceipt;
    private String goodsCO;
    public String BOENumber;
    public LocalDateTime BOEDate;
    private Boolean printedOriginal;
    public Boolean WBLPrinted;
    private Boolean draftPrinted;
    private Boolean surrenderPrinted;
    private EntityTransferParties notifyParty;
    private EntityTransferParties importBroker;
    private EntityTransferParties exportBroker;
    private EntityTransferParties sendingForwarder;
    private EntityTransferParties receivingForwarder;
    private EntityTransferParties traderOrSupplier;
    private EntityTransferParties eTailor;
    private EntityTransferParties borrowedFrom;
    private EntityTransferParties sendingAgent;
    private EntityTransferParties receivingAgent;
    private Map<String, EntityTransferMasterLists> masterData;
    private Map<String, EntityTransferUnLocations> unlocationData;
}
