UPDATE parties
SET
    org_code = 'FRC00019093',
    address_code = 'FRO00019676',
    org_id = '135730',
    address_id = '200263',
    updated_at = NOW(),
    org_data = '{
                    "Id": 135730,
                    "City": "Trappes",
                    "Guid": "a14cbe2b-dc59-490e-800d-233e5e92240e",
                    "Email": "c.clet@georgecannon.fr",
                    "IsGSA": false,
                    "Phone": "130168106",
                    "State": "Ile-de-France",
                    "label": "Ets George Cannon",
                    "value": "FRC00019093",
                    "Source": "CRP",
                    "Country": "FRA",
                    "Address1": "25 Avenue Georges Politzer",
                    "FullName": "Ets George Cannon",
                    "IsActive": 1,
                    "Payables": false,
                    "TenantId": 442,
                    "CompanyId": 372,
                    "Consignee": true,
                    "Consigner": true,
                    "PANNumber": "FR27572106102",
                    "TaxVendor": false,
                    "ExtraParam": "{}",
                    "InsertDate": "2024-11-06T11:42:38.000",
                    "UpdateDate": "2025-02-05T16:33:01.000",
                    "IsSuspended": false,
                    "Receivables": true,
                    "ZipPostCode": "78190",
                    "ActiveClient": true,
                    "CurrencyCode": "EUR",
                    "EmailInvoice": false,
                    "InsertUserId": 1712,
                    "UpdateUserId": 1712,
                    "VatRegNumber": "FR27572106102",
                    "ForworderAgent": false,
                    "IsCreditEnabled": false,
                    "IsV2PaymentTerm": false,
                    "OrganizationCode": "FRC00019093",
                    "EnableBulkInvoice": false,
                    "CustomerIdentifier": "781826",
                    "ReceivableTermsDate": 2,
                    "InsertUserIdUsername": "p100serviceaccountegypt@dpworld.com",
                    "OrgQuoteValidityDays": 0,
                    "UpdateUserIdUsername": "p100serviceaccountegypt@dpworld.com",
                    "CreditLimitOfConfigRow": "",
                    "CreditTermsOfConfigRow": "",
                    "IsClientEInvoiceEnabled": false,
                    "ImportExportClearanceLock": false
                }',
    address_data = '{
                        "Id": 200263,
                        "City": "Trappes",
                        "Email": "c.clet@georgecannon.fr",
                        "State": "Ile-de-France",
                        "label": "FRO00019676",
                        "value": "FRO00019676",
                        "Country": "FRA",
                        "OrgGuid": "a14cbe2b-dc59-490e-800d-233e5e92240e",
                        "Address1": "25 Avenue Georges Politzer",
                        "OrgSource": "CRP",
                        "AddressType": 1,
                        "CompanyName": "Ets George Cannon",
                        "OrgFullName": "Ets George Cannon",
                        "OrgPayables": false,
                        "ZipPostCode": "78190",
                        "TaxRegNumber": "FR27572106102",
                        "OrgReceivables": true,
                        "SiteIdentifier": "3815431_B",
                        "OrgActiveClient": true,
                        "AddressShortCode": "FRO00019676",
                        "OrgOrganizationCode": "FRC00019093"
                    }'
where
    id = 1376790 and tenant_id = 706;

update
    shipment_details
set
    client_dps_address_id = 109310,
    updated_at = NOW()
where
    id = 87437 and tenant_id = 706;
