UPDATE parties
SET
    org_code = 'FRC00028172',
    address_code = 'FRO00029077',
    org_id = '144437',
    address_id = '230767',
    updated_at = NOW(),
    org_data = '{
                    "Id": 144437,
                    "City": "Hamburg",
                    "Guid": "059f602e-cb84-4403-ab6a-c7df0b5f1770",
                    "Email": "germkt@maersk.com",
                    "IsGSA": false,
                    "Phone": "40235210",
                    "label": "Maersk Deutschland A/S & Co. KG",
                    "value": "FRC00028172",
                    "Broker": false,
                    "Source": "CRP",
                    "Carrier": false,
                    "Country": "DEU",
                    "Address1": "Johanniswall 7,",
                    "Address2": "",
                    "FullName": "Maersk Deutschland A/S & Co. KG",
                    "IsActive": 1,
                    "Payables": false,
                    "Services": false,
                    "TenantId": 442,
                    "CompanyId": 372,
                    "Consignee": true,
                    "Consigner": true,
                    "IsParnter": false,
                    "PANNumber": "HRA105094",
                    "TaxVendor": false,
                    "WareHouse": false,
                    "AirCarrier": false,
                    "ExtraParam": "",
                    "InsertDate": "2025-02-28T11:41:02.000",
                    "SeaCarrier": false,
                    "UpdateDate": "2025-06-24T05:13:15.000",
                    "IsSuspended": false,
                    "RailCarrier": false,
                    "Receivables": true,
                    "RoadCarrier": false,
                    "ZipPostCode": "20095",
                    "ActiveClient": true,
                    "CurrencyCode": "EUR",
                    "EmailInvoice": false,
                    "InsertUserId": 1712,
                    "UpdateUserId": 1712,
                    "VatRegNumber": "DE256518614",
                    "ForworderAgent": false,
                    "IsCreditEnabled": false,
                    "IsV2PaymentTerm": false,
                    "TransportClient": false,
                    "IsWalkInCustomer": false,
                    "OrganizationCode": "FRC00028172",
                    "EnableBulkInvoice": false,
                    "CustomerIdentifier": "1792317_001",
                    "ReceivableTermsDate": 2,
                    "InsertUserIdUsername": "p100serviceaccountegypt@dpworld.com",
                    "UpdateUserIdUsername": "p100serviceaccountegypt@dpworld.com",
                    "IsClientEInvoiceEnabled": false,
                    "ImportExportClearanceLock": false,
                    "FusionCreditlimitOverrideApproved": false
                }',
    address_data = '{
                        "Id": 230767,
                        "City": "Hamburg",
                        "Email": "germkt@maersk.com",
                        "label": "FRO00029077",
                        "value": "FRO00029077",
                        "Country": "DEU",
                        "OrgGuid": "059f602e-cb84-4403-ab6a-c7df0b5f1770",
                        "Address1": "Johanniswall 7,",
                        "Address2": "",
                        "OrgSource": "CRP",
                        "AddressType": 2,
                        "CompanyName": "Maersk Deutschland A/S & Co. KG",
                        "OrgFullName": "Maersk Deutschland A/S & Co. KG",
                        "OrgPayables": false,
                        "ZipPostCode": "20095",
                        "TaxRegNumber": "DE256518614",
                        "OrgReceivables": true,
                        "OrgActiveClient": true,
                        "AddressShortCode": "FRO00029077",
                        "OrgOrganizationCode": "FRC00028172"
                    }'
    where
        id in (select client_id from shipment_details where shipment_id='HAMS25093122' and tenant_id = 474);

    update
        shipment_details
    set
        client_dps_address_id = 108058,
        updated_at = NOW()
    where
        shipment_id='HAMS25093122' and tenant_id = 474;

