UPDATE parties
SET
  address_code ='FRO00021749',
  org_id = '136799',
  org_code = 'FRC00021117',
  address_id ='204944',
  address_data ='{
                     "Id": 204944,
                     "City": "Siegendorf",
                     "Email": "Izabella.Molnar@melecs.com",
                     "State": "Burgenland",
                     "label": "FRO00021749",
                     "value": "FRO00021749",
                     "Country": "AUT",
                     "OrgGuid": "08e7c8a3-a293-4847-8668-d228f82c2b30",
                     "Address1": "GZO-Technologiestrabe 1",
                     "OrgSource": "CRP",
                     "AddressType": 2,
                     "CompanyName": "MELECS EWS GmbH",
                     "OrgFullName": "MELECS EWS GmbH",
                     "OrgPayables": false,
                     "ZipPostCode": "7011",
                     "TaxRegNumber": "ATU69932727",
                     "OrgReceivables": true,
                     "OrgActiveClient": true,
                     "AddressShortCode": "FRO00021749",
                     "OrgOrganizationCode": "FRC00021117"
                 }'
                 ,
  org_data ='{
                 "Id": 136799,
                 "City": "Siegendorf",
                 "Guid": "08e7c8a3-a293-4847-8668-d228f82c2b30",
                 "Email": "Izabella.Molnar@melecs.com",
                 "IsGSA": false,
                 "Phone": "436763008008",
                 "State": "Burgenland",
                 "label": "MELECS EWS GmbH",
                 "value": "FRC00021117",
                 "Source": "CRP",
                 "Country": "AUT",
                 "Address1": "GZO-Technologiestrabe 1",
                 "FullName": "MELECS EWS GmbH",
                 "IsActive": 1,
                 "Payables": false,
                 "TenantId": 442,
                 "CompanyId": 372,
                 "Consignee": true,
                 "Consigner": true,
                 "PANNumber": "ATU69932727",
                 "TaxVendor": false,
                 "ExtraParam": "{}",
                 "InsertDate": "2024-11-19T06:28:00.000",
                 "UpdateDate": "2024-11-20T17:32:42.000",
                 "IsSuspended": false,
                 "Receivables": true,
                 "ZipPostCode": "7011",
                 "ActiveClient": true,
                 "CurrencyCode": "EUR",
                 "EmailInvoice": false,
                 "InsertUserId": 1712,
                 "UpdateUserId": 1712,
                 "VatRegNumber": "ATU69932727",
                 "ForworderAgent": false,
                 "IsCreditEnabled": false,
                 "IsV2PaymentTerm": false,
                 "OrganizationCode": "FRC00021117",
                 "CustomerIdentifier": "1683536_001",
                 "ReceivableTermsDate": 2,
                 "InsertUserIdUsername": "p100serviceaccountegypt@dpworld.com",
                 "OrgQuoteValidityDays": 0,
                 "UpdateUserIdUsername": "p100serviceaccountegypt@dpworld.com",
                 "CreditLimitOfConfigRow": "",
                 "CreditTermsOfConfigRow": "",
                 "ImportExportClearanceLock": false
             }'::jsonb
WHERE id = '1073557';